pkg/console/console.go

Problem:
Set up console log in init may affect k3os' logging behavior
Solution:
Move it out and do init specifically.

move log setup out of init

---

scripts/build

rename the built iso image from k3os-amd64.iso to harvester-amd64.iso

Rename built image

---

pkg/console/dashboard_panels.go
pkg/console/util.go
pkg/console/util_test.go

https://github.com/rancher/harvester/issues/254
Show unknown status when the node is not present in the cluster

update status in console dashboard

---

k3os/images/05-base/Dockerfile

This reverts commit 114373c8604504d216bca4035f8714ad38ae8e1d.
The issue is fixed on the Longhorn side so this workaround is not needed with longhorn-v1.1.0-rc2+

Revert "K3OS: change sh symlink"

---

pkg/console/util.go

The namespace creation is handled in the chart

Remove longhorn namespace in manifests

---

go.mod
k3os/images/output/01-full/Dockerfile
k3os/install.sh
pkg/config/config.go
pkg/config/config_test.go
pkg/config/read.go
pkg/config/read_test.go
pkg/config/schemas_test.go
pkg/config/testdata/harvester-config.yaml
pkg/config/write.go
pkg/console/console.go
pkg/console/install_panels.go
pkg/console/testdata/create-cc.yaml
pkg/console/testdata/create.yaml
pkg/console/testdata/join-cc.yaml
pkg/console/testdata/join.yaml
pkg/console/util.go
pkg/console/util_test.go
pkg/console/validator.go
pkg/console/validator_test.go
pkg/util/cloud_config.go
pkg/util/test.go
scripts/build

Partially fixed: https://github.com/rancher/harvester/issues/217
Support automatic installation
- Add Harvester config
- The installer now accepts Harvester config and converts the config to any internal form if needed. (e.g., k3os CloudConfig).
- Add kernel parameters to support automatic installation
- `harvester.install.automatic=true`. If this parameter is specified, then the installer is in automatic mode. No questions will be asked.
- `harvester.install.config_url=http://to.my/config`. The installer will fetch the config at this URL and perform the automatic installation.
*iPXE script*
```
kernel harvester/vmlinuz k3os.mode=install console=ttyS0 console=tty1 harvester.install.automatic=true harvester.install.config_url=http://10.100.0.10/config-create.yaml
initrd harvester/initrd …
```

Support automatic installation

---

Dockerfile.dapper
k3os/install.sh
k3os/scripts/images
scripts/build

Support configure http_proxy and exclude offline images by env to speed up local  build.
Docker Desktop eg:
```bash
export http_proxy=http://host.docker.internal:1087
export https_proxy=http://host.docker.internal:1087
export HARVESTER_INSTALLER_OFFLINE_BUILD=1
make
```

Support http proxy and exclude offline images

---

k3os/images/70-iso/Dockerfile
manifests/harvester.yaml
pkg/console/testdata/create-cc.yaml
pkg/console/util.go
pkg/console/util_test.go
scripts/build

package manifests and remove writeFiles configurations
Problem:
1. chart version mismatches the chart manifest spec
2. WriteFiles session is mounted read-only and inappropriate for upgrade.
Issue: https://github.com/rancher/harvester/issues/509

Fix mismatching chart version

---

pkg/console/console.go
pkg/console/install_panels.go
pkg/console/util.go

**Problem**
1. After network page closed, some `unknow view` error show on `/var/log/console.log`
2. After network page closed, network will be not available a few seconds, ping serverURL will be fail.
https://github.com/rancher/harvester/issues/490#issuecomment-792701862
**Solution**
1. Check error msg， if error msg is `unknow view`, ignore it
2. Add retry warp to `getURL`, set retrynum=3, retryinterval=2 to ping serverURL
rancher/harvester#490

Add retry to ping serverURL

---

.drone.yml

Publish the latest artifacts to `releases.rancher.com` given that ISO image exceeds the Github file size limit.

publish latest artifacts

---

k3os/overlay/bin/start-harvester-console.sh
k3os/overlay/libexec/k3os/boot
k3os/pkg/cc/apply.go

- Use getty to spawn the harvester-installer. By doing this, we can define a
default window dimension. This prevents installer cui initialization
failure on a serial console.
- Use the last `console=` kernel parameter value as the TTY which the installer
and Dashboard should be displayed on.
- Do not run `k3os install` in ccapply.
**Relate issue**
https://github.com/rancher/harvester/issues/485

K3OS: support various TTYs

---

scripts/build

The version opens TTY device in non-blocking mode and it can prevent
stuck problem on serial consoles.
https://github.com/rancher/harvester/issues/485

Update termbox-go dependency

---

manifests/cert-manager.yaml
manifests/harvester.yaml
manifests/rancher.yaml
scripts/build
scripts/images/cert-manager-images.txt
scripts/images/rancher-images.txt

**Problem:**
Add Rancher deployment manifest to the Harvester and enable by default on HCI mode.
**Solution:**
1. add Rancher & cert-manager manifests
2. expose Rancher by NodePort with the same IP address as the Harvester
3. package offline images
https://github.com/rancher/harvester/issues/513

Add rancher deployment

---

k3os/images/20-rootfs/Dockerfile
k3os/install.sh
k3os/shutdown.sh
pkg/config/config.go
pkg/console/install_panels.go
pkg/console/util.go
pkg/console/webhooks.go
pkg/console/webhooks_test.go
pkg/util/common.go

**Relate issue**
https://github.com/rancher/harvester/issues/469
With this change, the user can add webhooks in the config and the installer will send HTTP
requests to custom URLs on some predefined events.
The user can add webhooks under the `install` key of the [harvester configuration file](https://github.com/rancher/harvester/blob/fef31431c43b3abcde96c8b4209e6cd27a10048d/docs/harvester-configuration.md):
The following is a configuration example:
```yaml
install:
webhooks:
- event: SUCCEEDED
method: GET
url: http://10.100.0.100/cblr/svc/op/nopxe/system/{{.Hostname}}
- event: STARTED
method: GET
url: https://10.100.0.100/started/{{.Hostname}}
insecure: true
basicAuth:
user: admin
password: p@assword
- event: FAILED
method: POST
url: http://10.100.0.100/record
headers:
Content-Type:
- …
```

Allow specifying webhooks to get installer event notifications

---

k3os/pkg/system/component.go

https://github.com/harvester/harvester/issues/383
Problem:
After an upgrade completes, the terminal console still shows the previous version. k3os does not upgrade itself if the version does not change. 
Solution:
Since we compile the console into the k3os binary we need to upgrade it anyway. Also, rename the previous directory to a unique name so that it does not conflict after multiple upgrades.

k3os: always copy k3os for upgrade

---

pkg/console/install_panels.go
pkg/console/util.go

It's possible that the system's network stack is not ready before the installer is started. Add a retry loop to workaround this situation.
The retry interval is 10 seconds and the retries count is 30 times (5 minutes timeout).
**Related issue**:
https://github.com/harvester/harvester/issues/907
**Screenshot**

Retry if fetching remote config fails

---

manifests/harvester.yaml

The pull policy need to be "IfNotPresent" to use the pre-loaded images.
Related issue: https://github.com/harvester/harvester/issues/962

Fix webhook pods fail to start in air gapped environment

---

pkg/console/install_panels.go
pkg/console/util.go
pkg/widgets/panel.go

We need to adjust Y-axis movement because lone-lines are wrapped in the install panel (new feature in https://github.com/harvester/harvester-installer/pull/88.).
The `Autoscroll` flag of a View seems to work well, I remove the manually movement and turn the flag on.
**Before**
**After**
- Install harvester and make sure no messages are dropped in the install (last) panel.
Developer can apply this [patch](https://gist.github.com/bk201/40d8655f0a5f08bc95ae0f585ee23d43) to artificially generate some output without really running the installation.

Autoscroll install panel

---

manifests/harvester.yaml
manifests/rancher.yaml
scripts/build
scripts/images/rancher-images.txt

- Use default 30443 port for the Rancher server https://github.com/harvester/harvester/issues/755
- Bump k3s to v1.21.3 to with runC v1.0.0 support of https://github.com/harvester/harvester/pull/990

Update server port to rancher

---

Dockerfile.dapper
package/harvester-os/iso.yaml

The new version allows specifying compression.
It might be useful to developers by changing the compressor to `zstd` to speed up the building process.
```diff
diff --git a/package/harvester-os/iso.yaml b/package/harvester-os/iso.yaml
index 694f8bf..7fe320e 100644
--- a/package/harvester-os/iso.yaml
+++ b/package/harvester-os/iso.yaml
@@ -19,4 +19,4 @@ luet:
- quay.io/costoolkit/releases-green
type: docker
squashfs_options:
-  compression: xz
+  compression: zstd
```

Bump luet-makeiso version

---

package/harvester-os/files/usr/sbin/harv-install
pkg/config/cos.go

The previous way to set name servers in the image preloading phase
removes the symbolic link:
```
/etc/resolv.conf -> /var/run/netconfig/resolv.conf
```
This makes netconfig fail to update name servers from DHCP protocol.
Using netconfig to keep the link.
**Depends on**: https://github.com/harvester/os2/pull/8
**Related**: harvester/harvester#1137

Fix netconfig fail to update name servers in target OS

---

package/harvester-os/files/usr/sbin/harv-install
pkg/console/util.go

Saving harvester configuration file to OEM partition after installation.
This might be helpful for debugging.
```
/oem/
/oem/lost+found
/oem/harvester.config    <-- Harvester configuration file. Generated from installer or provided by users (PXE boot installation)
/oem/99_custom.yaml      <-- the cOS-toolkit config, converted from harvester.config
```

Save Harvester configuration after installation

---

pkg/config/templates/rke2-canal-config.yaml

It's a temporary solution before the bond solution completes.
issue: https://github.com/harvester/harvester/issues/1207

Use default route device as the interface of canal

---

package/harvester-os/files/system/oem/90_network.yaml

Create booting interface configuration files in PXE boot installation
The configuration files are needed to let wicked correctly apply DNS
settings.
For booting parameter `ip=dhcp`, the script creates DHCP configuration files for the booting interface(s).
If a machine has multiple network interfaces and more than one of them receive DHCP IPs, the booting interfaces are undetermined. Sometimes it's the first interface that receives a DHCP IP, sometimes all interfaces are listed.
For booting parameter `ip=ens5:dhcp ip=ens6:dhcp`, the script creates DHCP configuration files for interface `ens5` and `ens6`
**Why do we need this?**
A PXE-booted Live OS can be divided into 3 stages, each has its own network configuration.
- PXE firmware: The firmware sends DHCP requests to get an IP to download …

Create booting interface configuration files in PXE boot installation

---

pkg/console/install_panels.go
pkg/console/spinner.go

https://github.com/harvester/harvester/issues/1212
* Add functionality to the spinner for trapping the cursor focus so
users can't adjust settings while we're configuring the system:
`NewFocusSpinner`.
* Set up the focus spinner while we're requesting IP through DHCP and
setting up networking.
* For other types of message, call `updateValidatorMessage` to prevent
trapping focus.
* Fix spinner behavior: When it can't find the view, don't do anything.
* Update `validateDHCPAddresses`: Calls `getIPThroughDHCP` to validate
DHCP. No need to call `setupNetwork` at this time because it will be
called when we go to next page.
**Note**
I didn't change the way how IP is shown after it's received from DHCP.

Report status while configuring network

---

pkg/config/cos.go

The `systemd-timesyncd` service should be enabled to make time sync work.
https://rancher-sandbox.github.io/cos-toolkit-docs/docs/reference/cloud_init/#stagesstage_idstep_nametimesyncd

Fix systemd-timesyncd is not enabled

---

manifests/harvester.yaml
manifests/monitoring-crd.yaml
manifests/monitoring-dashboard.yaml
manifests/monitoring.yaml
scripts/build-bundle
scripts/images/rancher-images.txt

https://github.com/harvester/harvester/issues/576
Add built-in monitoring integration 
**What does this PR do:**
- Add built-in monitoring integration by leveraging the rancher monitoring chart and [kubevirt monitoring integration with the prometheus-operator](https://kubevirt.io/user-guide/operations/component_monitoring/#integrating-with-the-prometheus-operator)
- Add default Harvester monitoring dashboards, one for the dashboard page and the other for the VM instance details page.
**Testing Plan:**
1. harvester monitoring should be enabled by default when installed from the ISO
2. check if the monitoring pod are up and running
```
$kubectl get pod -n cattle-monitoring-system
NAME                                                     READY   STATUS    RESTARTS   AGE …
```

Add monitoring integation

---

pkg/console/dashboard_panels.go
pkg/version/version.go
scripts/build
scripts/build-bundle
scripts/version
scripts/version-harvester

* Add a new version variable `HarvesterVersion` to store version of harvester. Console dashboard shows this version, instead of the installer version.
* Add a new script `version-harvester` to determine and set up `HARVESTER_VERSION` variable for later use.
* Update script `version`: Unset variable `DIRTY` in case it was set somewhere else.
* Update script `build`:
- Pull harvester source from github if not exists. This will happen if we're calling `make` from harvester-installer, but not from calling `make build-iso` from harvester.
- Source "version-harvester" script to get the version of harvester.
- Update both harvester and harvester-installer version variables using ldflags, `HarvesterVersion` and `Version` respectively.
Tested by calling `make` from harvester-installer and `make …

Show harvester version on console dashboard

---

pkg/console/install_panels.go
pkg/console/validator.go

Follow Kubernetes node name validation method.
Issue: https://github.com/harvester/harvester/issues/1277

fix(install_panels.go): use IsDNS1123Subdomain to validate hostname

---

package/harvester-os/files/usr/share/rancher/rancherd/config.yaml.d/50-defaults.yaml
scripts/images/rancher-images.txt
scripts/images/rancherd-bootstrap-images.txt
scripts/version-rke2

- Bump RKE2 to `v1.21.5+rke2r1` https://github.com/harvester/harvester/issues/991
- Bump Rancher to `v2.6-1-rc5` https://github.com/harvester/harvester/issues/1243

Bump rke2 to v1.21.5+rke2r1

---

scripts/build-bundle

Related: https://github.com/harvester/harvester/pull/1336#discussion_r720286413
Need to accept image repository with more than three subpaths, e.g. `registry.suse.com/suse/sles/15.3/virt-operator`

Accept image repository with more than 3 subpaths

---

scripts/package-harvester-os

* Make daily build name consistent with git tag build. `harvester-$tag-$arch.iso`
* Add checksum for each output to `harvester-$tag-$arch.sha256`
issue: https://github.com/harvester/harvester/issues/1211

Use consistent iso name and add checksum for each file

---

pkg/config/constants.go
pkg/config/cos.go
pkg/console/validator.go

Related: https://github.com/harvester/harvester/issues/1325
- Add a new network method `none` to bypass configuring any DHCP or static network

Add a new network method none to bypass network configuration

---

package/harvester-os/files/etc/cos/bootargs.cfg
package/harvester-os/files/etc/cos/grub.cfg
package/harvester-os/files/etc/systemd/system/kdump.service.d/override.conf
package/harvester-os/files/system/oem/07_kdump.yaml
package/harvester-os/files/usr/sbin/gen-kdump-initrd
package/harvester-os/files/usr/sbin/harv-install

- Calculate crash kernel memory parameters at post-installation time.
- Generate a kdump initrd file before kdump service starts.
mkdumprd and dracut kdump module don't work well with current file system layout.
Customize the fstab file in the result initrd by ourself.
Required OS change: https://github.com/harvester/os2/pull/17
Related issue: https://github.com/harvester/harvester/issues/1335
** How to test **
Build a new ISO with the change and boot into the OS

Enable crash kernel for target OS

---

pkg/config/config.go
pkg/config/cos.go
pkg/console/install_panels.go

The current implementation is to add default bonding options for every network interfaces listed in the config. If we want to add default options **only** to bonding interfaces, we have to inspect those network configs. So I moved the adding action to the place where we have finished the inspection.

Fix todo: Add default bonding options in updateBond

---

pkg/console/validator.go

Problem:
When iso_url is left blank in harvester automatic installation like iPXE, no proper check is done, system goes into unexpected state
Solution:
Add check in validator, when iso_url is blank in automatic mode, stop installation and show related error message.
Related issue: harvester/harvester#1439
Test plan:
Set proper iPXE boot environment
In config file (e.g. config-create.yaml), set iso_url be blank; (BTW: given the iso_url is wrong/unreachable, there has already been some checks and error/info prompt)
Boot the VM / baremetal via iPXE
Expect: Install will stop, and show info `iso_url is required in automatic installation`

Check iso_url in automatic install mode like iPXE

---

pkg/config/config.go
pkg/config/config_test.go
pkg/config/templates.go
pkg/config/templates/rke2-90-harvester-agent.yaml
pkg/config/templates/rke2-90-harvester-server.yaml
pkg/console/validator.go

* Use `kubelet-arg` in RKE2 config to bootstrap node labels. See https://github.com/rancher/rancherd/issues/16.
* Remove `node-label+` from `rke2-90-harvester-agent.yaml` because we already have those default labels defined in `rancherd-config.yaml`.
- https://github.com/harvester/harvester/issues/1416

Add Node labels config

---

package/harvester-os/files/usr/sbin/harv-install
pkg/console/validator.go

Users can use a symbolic link like `/dev/disk/by-id/xxx` to select an install device.
This is useful when device enumeration (`/dev/sda`...) is not persistent across reboots.
https://github.com/harvester/harvester/issues/1462
**Test plan**
1. In a running OS, select a symbolic link to a disk. You can run the following command to see the links:
```
ls /dev/disk/by-id -alh
```
To test in a VM with Virtio disks, you can choose links in `/dev/disk/by-path/` because Virtio disks don't have ID.
2. Use symbolic link name as `os.install.device` to perform a PXE boot installation.

Support using symbolic link as the install device

---

pkg/config/config.go
pkg/config/config_test.go
pkg/config/cos.go
pkg/config/templates/rancherd-10-harvester.yaml
pkg/config/templates/rancherd-20-harvester-settings.yaml

Now we have `ManagedChart`, we could easily deploy these Setting CR not worrying RKE2 manifests reboot overwriting issue.

Use managedchart to deploy setting CR

---

package/harvester-os/files/etc/systemd/system/rke2-agent.service.d/override.conf
package/harvester-os/files/etc/systemd/system/rke2-server.service.d/override.conf
package/harvester-os/files/usr/sbin/harv-update-rke2-server-url

An agent node should use VIP to reach HA server nodes because
a server node might fail.
https://github.com/harvester/harvester/issues/1521

Use VIP in RKE2 Server URL for agent nodes

---

pkg/console/constant.go

Users should use VIP to join a cluster because a server node might fail.
https://github.com/harvester/harvester/issues/1521

Prompt users to use VIP to join a cluster

---

scripts/package-harvester-os

- Partition creation is enhanced in yip.
- Depends on a fixed OS snapshot image instead of the unpredictable `dev-head` tag.

Bump OS base image to 20211130

---

pkg/console/install_panels.go
pkg/console/util.go

Issue https://github.com/harvester/harvester/issues/1410
* Comment `vip` and `vip_hw_addr` in `ipxe-examples/vagrant-pxe-harvester/ansible/roles/harvester/templates/config-create.yaml.j2`
* Start vagrant-pxe-harvester
* Run `kubectl get cm -n harvester-system vip`
* Check whether we can get `ip` and `hwAddress` in it
* Run `ip a show harvester-mgmt`
* Check whether there is two IP in it and one is vip.

Get VIP through DHCP for PXE boot

---

pkg/config/config_test.go
pkg/config/templates/rancherd-config.yaml
pkg/console/install_panels.go
pkg/console/validator.go
pkg/console/validator_test.go

Properly escape the token value to allow using OWASP password special characters as cluster token value.
See https://owasp.org/www-community/password-special-characters
1. Use ISO to install Harvester in "create" mode
2. Enter any combination of alphanumeric and [OWASP password special characters](https://owasp.org/www-community/password-special-characters) as Cluster Token
3. Use ISO to install Harvester in "join" mode
4. Enter the same cluster token.
5. Make sure it can join a cluster using the same token value.
**NOTE:** It's not that easy to enter non-ASCII characters using installer GUI, so here I recommend using iPXE to perform the negative test case.
1. Use iPXE to install Harvester: Change the token value of config file to something invalid, such as `Äöê`
2. Verify that the …

Allow OWASP password special characters as token 

---

ci/run_vagrant_install_test.yml

If a job exited abruptly, there could be old vagrants leftovers which must be
cleaned up prior to starting the next provisioning job.

Cleanup vagrants leftovers before provisioning a new cluster

---

package/harvester-os/files/etc/cos/bootargs.cfg

Increase the timeout value because it takes longer for a device to appear
on some systems.
https://github.com/harvester/harvester/issues/1667

Increase OEM partition waiting timeout to 120s

---

package/harvester-os/files/usr/sbin/harv-install
scripts/build-bundle
scripts/lib/image
scripts/package-harvester-os
scripts/package-harvester-repo

The PR contains two features:
- Appending versions to archives file names, this makes image clean-up possible.
- Record image archives with a metadata file. When preloading a node, it's easier
to get what's included in an ISO. e.g.:
```
$ cat /srv/www/htdocs/harvester/iso/bundle/metadata.yaml
images:
common:
- list: /harvester/images/rancher-images-v2.6-638b29a687f3818e7de676a573ec9b9156f193a9-head.txt
archive: /harvester/images/rancher-images-v2.6-638b29a687f3818e7de676a573ec9b9156f193a9-head.tar.zst
- list: /harvester/images/harvester-images-b62f9f8-dirty.txt
archive: /harvester/images/harvester-images-b62f9f8-dirty.tar.zst
- list: /harvester/images/harvester-repo-images-b62f9f8-dirty.txt
archive: /harvester/images/harvester-repo-images-b62f9f8-dirty.tar.zst
rke2:
- list: …
```

Add upgrade repository feature

---

scripts/package-harvester-os

The OS update contains the files to bring up an upgrade repo VM. https://github.com/harvester/os2/pull/27

Bump harvester-os version to 20211214

---

package/harvester-os/files/usr/bin/setup-installer.sh

The systemd messages can be hidden with the kernel parameter `systemd.show_status=0`.
But I don't think it's a good idea because the booting messages prior to the Harvester dashboard/installer are quite useful.
So the idea is to turn off the messager before starting the installer and turn it on after the installer is stooped. This makes messages before shutdown or reboots visible.
References:
https://www.freedesktop.org/software/systemd/man/systemd.html#systemd.show_status
https://www.freedesktop.org/software/systemd/man/systemd.html#SIGRTMIN+21
To get current show status:
```
b false
```
**Related Issue**
https://github.com/harvester/harvester/issues/1132

Disable systemd messages before starting the installer

---

scripts/package-harvester-os
scripts/version

Problem:
Generated file name uses installer tag instead of master when the head commit is tagged.
https://drone-publish.rancher.io/harvester/harvester/500/3/3
Solution:
Use branch name for the version when DRONE_TAG is not available.

Use branch name instead of installer tag for artifacts version

---

scripts/version

Fix the vagrant CI failure. See https://github.com/harvester/harvester-installer/pull/200#issuecomment-997611719

Build version defaults to master

---

Dockerfile.dapper

- Bump outdated versions.
- Use binaries from cOS repository because they are tested with cOS and are not UPXed. It might resolve the [CI error](http://drone-publish.rancher.io/harvester/harvester-installer/514/1/2):
```
Removing intermediate container a3c87f3f8e38
--
535 | ---> 2bce42bbf2bd
536 | Successfully built 2bce42bbf2bd
537 | Successfully tagged rancher/harvester-os:v1.0.0
538 | 7b9685fdc8ef5dc79412452020a5fa115c17ed1c8cf3361aea8768016378d42a
539 | 7b9685fdc8ef5dc79412452020a5fa115c17ed1c8cf3361aea8768016378d42a
540 | time="2021-12-21T09:23:42Z" level=info msg="🔍  Preparing folders"
541 | time="2021-12-21T09:23:42Z" level=info msg="🍜  Installing Overlay packages"
542 | time="2021-12-21T09:23:42Z" level=info msg="Image 'rancher/harvester-os:v1.0.0' found locally, using it"
543 | …
```

Bump luet and luet-makeiso

---

package/harvester-os/files/usr/sbin/harv-install
pkg/console/install_panels.go
pkg/console/network.go

- Set hostname before configure network using `hostnamectl`
- Copy wicked runtime data (`/var/lib/wicked`) to the installed system.
- https://github.com/harvester/harvester/issues/1682

Preserve DHCP IP received during installation time

---

pkg/console/constant.go
pkg/console/install_panels.go
pkg/console/validator.go

If DNS servers are not provided by the config file in PXE installation or from ISO Installer while the management network has static IP, the installer would stop users from proceeding with the installation.
1. Install Harvester using ISO
2. While configuring networking, set up a **static IP address**
3. Verify that while configuring DNS servers, if no DNS servers are provided, the installer will **show a warning message and stop users from proceeding with the installation**
4. Verify that if DNS servers are given, installation can proceed
5. Go back to the network configuration page. This time set it up with **DHCP**
6. Verify that if no DNS servers are provided, the installer would still allow users to proceed
1. Create a config file with static networking, such as:
```
...
install:
... …
```

Stop installer if DNS is unset for static IP

---

package/harvester-os/files/usr/sbin/cos-installer-shutdown
package/harvester-os/files/usr/sbin/harv-install
pkg/config/cos.go
pkg/console/util.go
scripts/package-harvester-os

- Bump OS to `20220110`.
- Catch up upstream changes:
- Environment variable prefix changes: `COS_` to `_COS_`.
- Use `_COS_BOOTING_FROM_LIVE="true"` to prevent `cos` script from
downloading OS image from channels.

Bump OS version

---

package/harvester-os/files/etc/cos/bootargs.cfg

The label needs to be explicitly specified after this change in cOS:
https://github.com/rancher-sandbox/cOS-toolkit/pull/894
This fixes the problem that partition with `HARV_LH_DEFAULT` label is not mounted to `/var/lib/longhorn`.

Specify OEM label in kernel parameter

---

pkg/config/templates/rancherd-10-harvester.yaml

After kube-vip v0.4.1, since the kube-vip can use the VIP based on the default route automatically, the VIP interface parameter is not required anymore.
Related issue: 
https://github.com/harvester/harvester/issues/1681
Dependency: https://github.com/harvester/harvester/pull/1805

VIP interface isn't needed after kube-vip v0.4.1

---

scripts/build-bundle

In a master ISO build, the loaded upgrade image tag is:
```
docker.io/rancher/harvester-upgrade:master-head
```
But because the result ISO has a commit hash version like `ebde990-dirty`, during an upgrade the image `harvester-upgrade:ebde990-dirty` is not found.
```
harvester: ebde990-dirty
harvesterChart: 0.0.0-dev
os: Harvester 9f07d38-dirty
kubernetes: v1.21.7+rke2r1
rancher: v2.6.3-harvester1
monitoringChart: 100.0.0+up16.6.0
```
The PR tag `harvester-upgrade:master-head` to `harvester-upgrade:<version>` and save the new image in the result ISO.

Preload harvester-upgrade image with master build version tag

---

package/harvester-os/files/usr/sbin/harv-install
pkg/console/util.go

For PXE installation, we need to download and mount the ISO in order to preload container images. However, as the ISO gets larger, we can no longer download it into the /tmp folder on machines with little RAM installed. We would have to download it somewhere else.
* Download the ISO onto the system disk, after we mounted it for the purpose of preloading images. The ISO is too large to fit into /tmp for machines with little RAM installed.
* Fix the issue of the installer won't error out if encountered errors while running `harv-install` script.
Signed-off-by: John Liu <john.liu@suse.com>

Download ISO to OS system disk

---

package/harvester-os/files/usr/sbin/harv-update-rke2-server-url
pkg/console/util.go
pkg/console/util_test.go

VIP:8443 doesn't work when VIP doesn't coexist with rancher pods.
**Related Issue**
https://github.com/harvester/harvester/issues/1830

Use VIP:443 to join a cluster

---

pkg/config/read.go
pkg/util/cmdline.go
pkg/util/cmdline_test.go

The PR is in relation to feature request: https://github.com/harvester/harvester/issues/1889
With this minor tweak to the harvester-installer, the mass PXE booting of nodes is easier as the ${net0/mac} PXE variable can be passed to kernel arguments to allow harvester-installer to use hwAddr based address lookup to find the correct interface.
This makes it easy to PXE boot a full multi node harvester cluster quickly using something like terraform. A sample of the same using a custom squashfs build is here: https://github.com/ibrokethecloud/harvester-equinix-terraform-sample

Ability to process kernel arguments containing harvester-mgmt NetworkInterface details

---

pkg/config/config.go
pkg/config/cos.go
pkg/config/templates/rancherd-21-harvester-clusternetworks.yaml

cluster network only allow one type of entry in same cluster.
also check dup name or not
address https://github.com/harvester/harvester/issues/1739
1. Install a node of new cluster with ISO or PXE and put the config below into `config.yaml` and provide it to installer 
```yaml
cluster_networks:
vlan:
enable: true
description: "some description about this cluster network"
config:
defaultPhysicalNIC: ens3
```
2. verify no error occurs and finish the installation
3. verify `ClusterNetwork` resource named `vlan` is created.
```bash
kubectl get clusternetworks.network.harvesterhci.io vlan -o yaml
```
4. verify the fields of `ClusterNetwork` resource named `vlan`  are correct.
```bash
kubectl get clusternetworks.network.harvesterhci.io vlan -o yaml
```
Result should contain `name`, `enable`, …

add ClusterNetworks config in installer

---

pkg/config/cos.go
pkg/config/cos_test.go

Move the configuration of SSH keys to the "network" stage, to ensure network is available in case remote SSH key fetching is required.
Also add some unit tests.
1. Prepare a PXE installation environment
2. Ensure the config.yaml requires fetching SSH key remotely from GitHub:
```
...
os:
ssh_authorized_keys:
- github:<A GitHub Username>
...
```
3. Run the PXE installation
4. After installation is finished, SSH into the Harvester and make sure the file `/home/rancher/.ssh/authorized_keys` existed and contains the public keys of the GitHub user specified in the config.
See https://docs.harvesterhci.io/v1.0/install/harvester-configuration/#osssh_authorized_keys for information about the config.
- https://github.com/harvester/harvester/issues/1903
- `yip` command for configuring SSH keys: …

Move SSH key configuration stage to "network"

---

package/harvester-os/files/usr/bin/start-installer.sh

The shell is started without using the /bin/login command so $HOME is not configured. Need to set it up manually.
1. Install Harvester
2. Wait until terminal dashboard is shown (the one with the following logo:)
```
██╗░░██╗░█████╗░██████╗░██╗░░░██╗███████╗░██████╗████████╗███████╗██████╗░
██║░░██║██╔══██╗██╔══██╗██║░░░██║██╔════╝██╔════╝╚══██╔══╝██╔════╝██╔══██╗
███████║███████║█████╔╝╚██╗░░██╔╝█████╗░░╚█████╗░░░░██║░░░█████╗░░██████╔╝
██╔══██║██╔══██║██╔══██╗░╚████╔╝░██╔══╝░░░╚═══██╗░░░██║░░░██╔══╝░░██╔══██╗
██║░░██║██║░░██║██║░░██║░░╚██╔╝░░███████╗██████╔╝░░░██║░░░███████╗██║░░██║
╚═╝░░╚═╝╚═╝░░╚═╝╚═╝░░╚═╝░░░╚═╝░░░╚══════╝╚═════╝░░░░╚═╝░░░╚══════╝╚═╝░░╚═╝`
```
3. Press F12 to switch to shell
4. Enter command `kubectl get nodes` and verify that **no error messages are shown** and **the …

Set HOME env. var. while switching to terminal

---

package/harvester-os/files/usr/sbin/harv-install
pkg/console/util.go

- Record the harv-install output into installer log.
Example:
```
time="2022-02-23T16:55:58Z" level=info msg="[stdout]: Formatting drives.."
time="2022-02-23T16:55:58Z" level=info msg="[stderr]: 1+0 records in"
time="2022-02-23T16:55:58Z" level=info msg="[stderr]: 1+0 records out"
time="2022-02-23T16:55:58Z" level=info msg="[stderr]: 1048576 bytes (1.0 MB, 1.0 MiB) copied, 0.00506754 s, 207 MB/s"
time="2022-02-23T16:55:58Z" level=info msg="[stderr]: Warning: The resulting partition is not properly aligned for best performance."
time="2022-02-23T16:56:03Z" level=info msg="[stdout]: time=\"2022-02-23T16:56:03Z\" level=info msg=\"Running stage: partitioning\\n\""
time="2022-02-23T16:56:03Z" level=info msg="[stdout]: time=\"2022-02-23T16:56:03Z\" level=info msg=\"Executing …
```

Record install panel output in the installer log

---

pkg/config/config.go
pkg/config/config_test.go
pkg/config/templates/wicked-ifcfg-bond-master
pkg/config/templates/wicked-ifcfg-eth
pkg/console/install_panels.go

- Add config `MTU` to Network configuration
- Support merging the "Networks" field of HarvesterConfig (because [Mergo](https://github.com/imdario/mergo#usage) does not support merging struct inside maps)
> **NOTE**: Users can only configure MTU via Harvester Configurations. They can't configure this value using Installer UI.
1. Boot the machine via Harvester ISO
2. Supply a remote config with the following YAML:
```
install:
networks:
harvester-mgmt:
mtu: 1400
```
This will set the `harvester-mgmt` interface to have MTU `1400`. Change this value as you wish (default is `1500`).
3. Proceed with the installation
4. SSH into the Harvester node and use the command `ip link show <interface>` to verify:
- `harvester-mgmt` interface has the MTU `1400` (or whatever value you provided)
- `enp1s0` …

Support MTU config

---

scripts/build-bundle

Bump Windows VMDP driver image due to old image will encounter the `not verified digital signature` issue.
Related Issue: https://github.com/harvester/harvester/issues/1767
Related PR: https://github.com/harvester/harvester/pull/1960

Bump vmdp driver image

---

Dockerfile.dapper
package/harvester-repo/Dockerfile

- Build environment:
- Switch to BCI image and use zypper to install packages.
- Drop `GO111MODULE=off`.
- Add go pkg and cache volumes.
- harvester-cluster-repo: switch to BCI image and install nginx.
https://github.com/harvester/harvester/issues/1868

Switch BCI images

---

pkg/config/config.go
pkg/config/config_test.go
pkg/config/templates/cos-rootfs.yaml
pkg/console/install_panels.go
pkg/console/util.go

- Remove a user-configurable config "Install.NoDataPartition" to reduce system complexity. It's now a derived setting from other config fields: "ForceMBR" and "DataDisk".
- Add methods "ShouldCreateDataPartitionOnOsDisk" and "ShouldMountDataPartition" for accessing the derived setting.
- https://github.com/harvester/harvester/issues/1907

Remove config "NoDataPartition"

---

pkg/config/templates/rancherd-13-monitoring.yaml

Harvester will open setting of monitoring for user config from UI, it is necessary to have init values for all fields, avoid blank values in WebUI.
Those values are same with (helm) charts in Harvester now, different value will overwrite (helm) charts and finally be effective in the POD setting.
Harvester issue:
https://github.com/harvester/harvester/issues/1531

fix1531 sync init value from charts for UI config usage

---

scripts/build-bundle
scripts/patch-harvester
scripts/version
scripts/version-harvester

We want to build iso for [harvester v1.0 branch](https://github.com/harvester/harvester/tree/v1.0)
**Problem:**
1. If not a harvester-installer release, the default version of harvester-installer is always `master`. 
each iso build on different branches has the same name.
1. If not a harvester release, the default image tag of harvester chart is always `master-head`. 
1. If not a harvester release, the default chart version of harvester chart is always `0.0.0-dev`. 
1. If not a harvester release, the default chart appVersion of harvester chart is always `v0.0.0-dev`. 
**Solution:**
1. In harvester, build chart version, image tag in `script/version`
1. In harvester-installer, try to use `DRONE_BRANCH` as the iso version
1. In harvester-installer, Add a script `patch-harvester` to patch …

Use harvester code info to patch harvester chart version and harvester image tag

---

pkg/config/templates/rancherd-13-monitoring.yaml

Related issue:
https://github.com/harvester/harvester/issues/1531
https://github.com/harvester/harvester/issues/1531#issuecomment-1068183732
https://github.com/harvester/harvester/issues/1531#issuecomment-1073812670
The CPU and memory limit of prometheus-node-exporter need also be customized in Harvester, they are exposed to managedchart now, WebUI may also add configuration for it.
The default memoy limit of prometheus-node-exporter, `50Mi`, is not fully fit for Harvester usage, which is increased to 180Mi.
**Validation**:
The managedchart has those config, the memory limit is increased for the prometheus-node-exporter POD.
```
harv41:~ # kubectl get managedchart rancher-monitoring -n fleet-local -o JSON | more
{
"apiVersion": "management.cattle.io/v3",
"kind": "ManagedChart",
}, …
```

fix 1531: expose resource config of prometheus-node-exporter and increase memory limit

---

Dockerfile.dapper
scripts/collect-deps.sh
scripts/package-harvester-os
scripts/version-harvester

During an upgrade, the upgrade script will check if various components
are upgraded to target versions.
`harvester-release.yaml` sample:
```
harvester: 2a65703
harvesterChart: 0.0.0-master-2a65703
os: Harvester e49d98d-dirty
kubernetes: v1.22.7+rke2r1
rancher: v2.6.4-rc10
monitoringChart: 100.1.0+up19.0.3
kubevirt: 0.49.0-2
rancherDependencies:
fleet:
chart: 100.0.3+up0.3.9-rc6
app: 0.3.9-rc6
fleet-crd:
chart: 100.0.3+up0.3.9-rc6
app: 0.3.9-rc6
rancher-webhook:
chart: 1.0.4+up0.2.5-rc3
app: 0.2.5-rc3
```
**Related Issue**
https://github.com/harvester/harvester/issues/1982

Add versions of rancher dependencies and KubeVirt to release file

---

Dockerfile.dapper

Bump `luet-makeiso` to 0.4.0 to generate a valid hybrid ISO.
Hopefully, it solves the issue that some users can't boot a USB installation media.
For more information, see https://github.com/rancher-sandbox/cOS-toolkit/issues/1148

Generate hybrid ISO

---

pkg/console/dashboard_panels.go
pkg/console/util.go

Signed-off-by: futuretea <Hang.Yu@suse.com>
- check the Ready status by
```bash
curl -fk https://managementURL/version
```
- remove unused logics: `getFirstReadyMasterIP`
**Related issues**
https://github.com/harvester/harvester/issues/2022
**Test plan**
- Install harvester on a machine
- wait for it to show the 1st ready status
- try to access harvester via the URL
- harvester should only show ready status once it is fully ready.

Fix Ready status

---

scripts/package-harvester-os

Include https://github.com/harvester/os2/pull/34 and various security fixes.

Bump OS to 20220323

---

scripts/package-harvester-os

Generate `version.yaml` when we have a released tag for it.
Related issue: https://github.com/harvester/harvester/issues/2091
Test steps:
1. `export DRONE_TAG=v1.0.1`.
2. `make ci`
3. Check whether we have `version.yaml` under `dist/artifacts` and it format should be like the following.
```
apiVersion: harvesterhci.io/v1beta1
kind: Version
metadata:
name: v1.0.1
namespace: harvester-system
spec:
isoChecksum: cf8d14804fedeae564a881344865357110d32fc03614bc9337518b814e23f46f6979d59ef0c04199f4bed2c88be187541e46f0bf168af8bcce9dc1def3d906ff
isoURL: https://releases.rancher.com/harvester/v1.0.1/harvester-v1.0.1-amd64.iso
```

Add version.yaml

---

package/harvester-os/files/usr/share/rancher/rancherd/config.yaml.d/50-defaults.yaml
scripts/images/rancher-images.txt
scripts/images/rancherd-bootstrap-images.txt
scripts/version-rancher

Bump rancher to `v2.6.4-harvester1`.
Known issues
- https://github.com/rancher/rancher/issues/37113
- https://github.com/rancher/rancher/issues/37114
- **Need to test the PR with Internet connectivity**

Bump rancher to v2.6.4-harvester1

---

package/harvester-os/files/usr/share/rancher/rancherd/config.yaml.d/50-defaults.yaml
scripts/collect-deps.sh

- We need to temporarily hard-code the generated rancher-webhook versions in harvester-release.yaml.
- Also specify the minimum rancher-webhook chart versions via env variables when creating applying the rancher chart.
To test upgrade, the PR is needed: https://github.com/harvester/harvester/pull/2097

Add workaround for https://github.com/rancher/rancher/issues/37113

---

package/harvester-os/files/usr/share/rancher/rancherd/config.yaml.d/50-defaults.yaml
scripts/collect-deps.sh
scripts/images/rancher-images.txt
scripts/images/rancherd-bootstrap-images.txt
scripts/version-rancher

- Bump rancher to v2.6.4-rc15
- Remove workaround https://github.com/harvester/harvester-installer/pull/259 because issues are resolved.
To test upgrade, please include https://github.com/harvester/harvester/pull/2100

Bump Rancher to v2.6.4-rc15 

---

scripts/package-harvester-os

Fix error:
```
╰─$ kubectl apply -f https://releases.rancher.com/harvester/v1.0.1-rc2/version.yaml
The Version "v1.0.1-rc2" is invalid: spec.releaseDate: Invalid value: "integer": spec.releaseDate in body must be of type string: "integer"
```

Quote releaseDate as string in version file

---

pkg/console/install_panels.go

1. Install Harvester by ISO.
2. In the NTP page, remove default input.
3. Press Enter and we can see a warning message "Empty NTP Server is not recommended. Press Enter to continue.".
4. Press Enter again and we can go to the next page.
5. Press Esc and we can go back to the NTP page.
6. Press Enter and we can see the warning message.
7. Input a valid NTP server.
8. Press Enter. There should not have any error message and we can go to next page.
related issue:
https://github.com/harvester/harvester/issues/2119

Check whether ntpServers input is empty

---

package/harvester-os/files/usr/sbin/cos-installer-shutdown
package/harvester-os/files/usr/sbin/harv-install
pkg/config/cos.go
pkg/console/util.go
scripts/package-harvester-os

Update the environment variables passed to the `harv-install` and `cos-installer-shutdown` script for `elemental` command. Do notice that elemental uses different names for several installation options, so we also need to adapt these new names in harv-install script.
~~We don't have to update the base-os version yet because `elemental` already exists in the current base-os: https://github.com/harvester/os2/releases/tag/20220407.~~
We do have to update the base OS version for the fix of https://github.com/rancher-sandbox/elemental/issues/164
- ForceEFI: `ELEMENTAL_FORCE_EFI`
- Device: Positional arg or `ELEMENTAL_TARGET`
- ConfigURL: `ELEMENTAL_CLOUD_INIT`
- Silent: No env var. Must be specified by CLI arg `--quiet`
- ISOURL: `ELEMENTAL_ISO`
- PowerOff: `ELEMENTAL_POWEROFF`
- NoFormat: …

Update environment variables passed to harv-install script

---

package/harvester-os/files/usr/lib/supportconfig/plugins/harvester_plugin_console
package/harvester-os/files/usr/lib/supportconfig/plugins/harvester_plugin_rke2
pkg/console/util.go

This PR is related to issue: https://github.com/harvester/harvester/issues/1864
The aim is to auto generate a supportconfig when `debug` is enabled in the installation, and the installation fails.
The PR also introduces two custom plugins to copy the rke2.log and console.log into the generated supportconfig to make it easier to troubleshoot failures.
To test:
* patch /usr/sbin/harv-install to `exit 1`
* pass a minimal config via a http endpoint to enable debug. This would look as follows:
```yaml
install:
debug: true
```
* on installation failure, harvester-installer will trigger the generation of support config, and also run the two packaged plugins

Generate supportconfig for failed installations

---

pkg/config/templates/rancherd-13-monitoring.yaml

The PR adds a diff to the managed chart for monitoring and allows fleet to ignore changes to CA certificate injected at runtime.
This is related to issue: https://github.com/harvester/harvester/issues/2152
Post this change the fleet bundle associated with monitoring managed chart is reconciled correctly.

Added a diff to monitoring managed chart

---

pkg/config/cos.go

Without resolving it first, elemental installation would fail.
1. Install Harvester with any node using PXE boot installation with setting `install.device` to /dev/disk/by-path instead of `/dev/vda`
2. Make sure installation succeeded
- https://github.com/harvester/harvester/issues/2256

Resolve the device path before generating partition layout

---

scripts/collect-deps.sh

Remove the container that is used to know Rancher catalog hash.
Otherwise, over time the system will have lots of stale containers like this:
```
$ docker ps -a
CONTAINER ID   IMAGE                               COMMAND                  CREATED             STATUS                         PORTS                                                                                  NAMES
30aaaeabb1f6   rancher/rancher:v2.6.4-harvester3   "/bin/bash -c 'ls /v…"   About an hour ago   Exited (0) About an hour ago                                                                                          wonderful_lamport
```

Remove unused intermediate container

---

package/harvester-os/templates/91-harvester-bootstrap-repo.yaml
pkg/config/config.go
pkg/config/config_test.go
pkg/config/cos.go
pkg/config/templates/rancherd-10-harvester.yaml
pkg/config/templates/rancherd-11-monitoring-crd.yaml
pkg/config/templates/rancherd-12-monitoring-dashboard.yaml
pkg/config/templates/rancherd-13-monitoring.yaml
pkg/config/templates/rancherd-20-harvester-settings.yaml
pkg/config/templates/rancherd-21-harvester-clusternetworks.yaml
pkg/config/templates/rancherd-config.yaml
scripts/build
scripts/package-harvester-os

- Bump harvester-os version
- Specify Rancher version in rancherd config
- Replace `bootstrapResources` with `resources` for Rancherd configs
- Fix testing
https://github.com/harvester/harvester/issues/1933
- https://github.com/harvester/os2/pull/38

Update for the latest Rancherd (v0.0.1-alpha13)

---

pkg/console/install_panels.go

The response message from DHCP servers could be more than one line.
Allow the panel to wrap text.
Related issue: https://github.com/harvester/harvester/issues/2224
**Test plans**
- Disable DHCPD and select `Automatic (DHCP)` method in the VIP panel. The error message should wrap.
- Select the `Static` method and enter a very long text, the error message should wrap too.
- This PR also cleans the left-over error messages when jumping back to the DNS panel and jumping to the VIP panel again
-  In the VIP panel, enter some error text in Static mode. An error message should display.
-  Jump back to the DNS panel.
-  Jump to the VIP panel. The error message should be clear.

VIP panel: wrap info panel

---

pkg/console/install_panels.go

related: https://github.com/harvester/harvester/issues/2229
Assert the difference between VIP and management NIC's IP.
0. Build the installer and run it.
1. Select `Static` as your IPv4 Method
2. Type a IP for management NIC
3. Select `Static` as your VIP mode
4. Type the same IP as NIC management IP
5. Expect to see the error message **"VIP must not be the same as management NIC's IP"**.

VIP must be different from management NIC's IP

---

pkg/console/install_panels.go

related backport issue: https://github.com/harvester/harvester/issues/2377
parent pr: https://github.com/harvester/harvester-installer/pull/283
0. Build the installer and run it.
1. Select `Static` as your IPv4 Method
2. Type a IP for management NIC
3. Select `Static` as your VIP mode
4. Type the same IP as NIC management IP
5. Expect to see the error message **"VIP must not be the same as management NIC's IP"**.

[Backport v1.0.3] VIP must be different from management NIC's IP

---

package/harvester-os/files/usr/sbin/harv-install

If the target device is occupied, the partitioning could fail.
Related Issue: https://github.com/harvester/harvester/issues/2230
**How to test**
- Install Centos or Ubuntu on a disk and choose LVM scheme. Note you can also manually create some LVs on a disk first, the key is to have LVs on the target disk. Here is an example:
```
rancher:~ # pvcreate /dev/vda
Physical volume "/dev/vda" successfully created.
rancher:~ # vgcreate test_vg /dev/vda
Volume group "test_vg" successfully created
rancher:~ # lvcreate -n test_lv -l 100%FREE test_vg
Logical volume "test_lv" created.
```
- Reboot the system with Harvester ISO
- Check the LV is activated:
```
rancher:~ # ls /dev/test_vg/test_lv -l
lrwxrwxrwx 1 root root 7 May 24 09:53 /dev/test_vg/test_lv -> ../dm-0
```
- Install Harvester and the …

Deactivate LVM and MD devices before installation

---

scripts/build
scripts/build-bundle

Make sure we use the correct backend code when building from the `v1.0` branch.

Use correct harvester/harvester branch

---

package/harvester-os/files/usr/sbin/harv-install
scripts/build-bundle
scripts/images/rancher-images.txt
scripts/package-harvester-os
scripts/package-harvester-repo
scripts/version-rke2

ref: https://github.com/harvester/harvester/issues/2336
**Test Steps**:
* Create a cluster.
* Check whether `kube-system/rke2-coredns-rke2-coredns-autoscaler` resources are
```
limits:
cpu: 100m
memory: 64Mi
requests:
cpu: 25m
memory: 16Mi
```

[WIP] bump rke2 to v1.22.12-rc3+rke2r1

---

scripts/build-bundle

We need to make sure the `harvester/deploy/charts` is reset before exiting
this script. Otherwise it will intervene version values in other scripts.
This PR is to make the speed up tip https://github.com/harvester/harvester/wiki/Speed-up-Harvester-ISO-build#skip-images-pulling-in-build-bundle-stage easier.

build-bundle: reset chart workspace in bundle cache path

---

scripts/version-rke2

**Description:**
Bump the rke2 to the official [v1.22.12 release](https://github.com/rancher/rke2/releases/tag/v1.22.12%2Brke2r1) and it is identical to the previous [rc3 release](https://github.com/rancher/rke2/releases/tag/v1.22.12-rc3%2Brke2r1).

Bump the rke2 to official v1.22.12 release

---

pkg/console/install_panels.go

`mgmtNetwork.BondOptions` will `nil` until `askBondModeVConfirm` is executed first time.
`PreShow` will be executed multiple times and set BondMode back to the default value in the first time.
While setting default bond mode, let installer set BondOptions to non-null map to avoid.
https://github.com/harvester/harvester-installer/pull/320
Choose bond mode twice or more to set the correct value.
1. select other bond mode than default one
2. continue install option until showing all config yaml before installation
3. check installation yaml has correct bond mode.
related: https://github.com/harvester/harvester/issues/2675
test plan: https://github.com/harvester/harvester/issues/2675

console: install: bond: make a map to avoid execute set default bondMode

---

pkg/config/templates/rancherd-13-monitoring.yaml

(1) Expose grafana pod resource setting managedchart rancher-monitoring 
(2) Increase grafana pod resource setting
current:
```
resources:
limits:
memory: 200Mi --
cpu: 200m
requests:
memory: 100Mi --
cpu: 100m
```
after:
```
resources: 
limits:
cpu: 200m
memory: 500Mi --
requests:
cpu: 100m
memory: 200Mi --
```
https://github.com/harvester/harvester/issues/2361

fix2361 increase grafana resource limit

---

pkg/config/templates/rancherd-13-monitoring.yaml
scripts/images/allow.yaml
scripts/images/rancher-images.txt

Enable alertmanager in managedchart
Export essential parameters
Use PVC to store alert data
Export externalUrl for return access
Signed-off-by: Jian Wang <w13915984028@gmail.com>
**Problem:**
Harvester support alertmanager.
**Solution:**
Default enable. (It's very helpful to know all the alerts right from system startsup). User can disable in Harvester dashboard setting `monitoring`.  cc:  @DaiYuzeng @guangbochen @bk201 
Alertmanager has one POD in the cluster, it takes around `50Mi` of memory.
```
harv1:~ # kubectl top pod -A
..
NAMESPACE                   NAME                                                     CPU(cores)   MEMORY(bytes)   
cattle-monitoring-system    alertmanager-rancher-monitoring-alertmanager-0           1m           50Mi            
cattle-monitoring-system …
```

feat2517 Harvester-installer support alertmanager

---

pkg/config/templates/rancherd-13-monitoring.yaml

Signed-off-by: Jian Wang <w13915984028@gmail.com>
fix2282 adjust grafana POD PVC size to 2GiB
https://github.com/harvester/harvester/issues/2282
Upgrade patch:
https://github.com/harvester/harvester/pull/2711
Note:
The upgrade patch will make sure the claimed `PVC size` is 2Gi after upgrading. But the existing grafana PVC is not affected, it is still 10Mb (the smallest size LH gives)
How to patch existing PVC, needs more investigation.
(more scripts like disable grafana, delete PVC, re-enable grafana; or accordging to PVC reset steps as per LH's document; both of them are more than quick inheritage from current upgrading framework @bk201 @guangbochen
)

fix2282 adjust grafana POD PVC size to 2GiB

---

package/harvester-os/files/etc/cos/bootargs.cfg
package/harvester-os/files/usr/sbin/harv-install

This sets the necessary kernel parameters for [PCI Passthrough](https://github.com/harvester/harvester/issues/992). 
I built and installed this on my bare metal Dell T7500 server. I rebooted and verified that the `intel_iommu=on` boot args are in the grub config.

Set iommu=on for Intel or AMD

---

package/harvester-os/files/system/oem/99_ca.yaml
pkg/config/cos.go

ref: https://github.com/harvester/harvester/issues/2736
**Create first node**
* Use [vagrant-pxe-harvester](https://github.com/harvester/ipxe-examples/tree/main/vagrant-pxe-harvester) to setup 1-node cluster.
* Generate self-signed certificate. Remember to change `IP.1` value to your VIP.
```console
cat <<EOF > ssl.conf
[req]
prompt = no
default_md = sha256
default_bits = 2048
distinguished_name = dn
x509_extensions = v3_req
[dn]
C = TW
ST = Taiwan
L = Taipei
O = Test Inc.
OU = IT Department
emailAddress = admin@example.com
CN = localhost
[v3_req]
subjectAltName = @alt_names
basicConstraints = CA:TRUE
[alt_names]
IP.1 = 192.168.0.30
EOF
openssl req -x509 -new -nodes -sha256 -utf8 -days 3650 -newkey rsa:2048 -keyout server.key -out server.crt -config ssl.conf
```
* Upload `server.crt` to …

fix: change update ca stage

---

scripts/package-harvester-os

Only zypper update.
baseos's Dockerfile isn't changed.

baseos: upgrade latest SLE Micro package

---

pkg/config/cos_test.go
pkg/console/dashboard_panels.go
pkg/util/cmdline_test.go

current logic:
if one pod has labels "app.kubernetes.io/name=harvester" is ready, then harvester is ready.
problem:
if no harvester pod is ready, only harvester-webhook (has labels "app.kubernetes.io/name=harvester") is ready. console still show `Ready`
solution:
change logic to "harvester pod ready and harvester-webhook pod ready"
**Related issues**
https://github.com/harvester/harvester/issues/2778
**Test Plan**
1. scale down harvester
+ remove annotation "management.cattle.io/scale-available" in deployment harvester 
+ set deploy harvester replicas to 0 (need first)
```bash
kubectl -n harvester-system edit deploy harvester
```
2. check the `Status` in `Harvester Cluster`

Fix harvester ready check

---

pkg/console/constant.go
pkg/console/install_panels.go
pkg/console/validator.go

**Problem:**
Users are not able to configure `harvester-mgmt` bond with the desired MTU value via ISO installation. This could be a problem while the target machine being provisioned resides on a network whose path MTU is below 1500 bytes.
**Solution:**
Along with the ISO installation, users can configure the bond's MTU on the network configuration page when choosing the "Static" option for "IPv4 Method".
Configure MTU value:
Confirm that the MTU is shown on the page:
Press <Alt+F2> and execute `ip addr` after applied the network config to see if the MTU is being set:
harvester/harvester#2437
**Test plan:**
1. Spin up a node with Harvester ISO installation
2. Go through installation steps
3. On the network configuration page, select "Static" in the network method field …

fix(install_panels): add a field for MTU config

---

scripts/package-harvester-os
scripts/version-harvester

A version string specifying the minimum version required to be able to upgrade is injected into `harvester-release.yaml` for further usage.
Related issue: harvester/harvester#2431
Related PR: harvester/harvester#2777
Signed-off-by: Zespre Chang <zespre.chang@suse.com>

feat(upgrade): inject minUpgradableVersion into OS image

---

ci/run_vagrant_install_test.yml

We've made the v1.0 branch as the default branch in ipxe-example, and it doesn't work with the installer's master branch.
Use the `main` branch instead.

CI: Use main branch for ipxe-examples

---

scripts/package-harvester-os

Include rancherd update: https://github.com/rancher/rancherd/pull/25.

Bump OS to 20221005

---

pkg/config/templates/rancherd-22-vm-import-controller.yaml
scripts/build-bundle

The PR introduces a new version of the harvester-vm-import-controller, which addresses a number of issues fixed by PR: https://github.com/harvester/vm-import-controller/pull/5

bump up image for harvester-vm-import-controller

---

pkg/console/install_panels.go
pkg/util/cmdline.go
pkg/util/cmdline_test.go

The PR fixes how management_interfaces and scheme_version are parsed via kernel_arguments in v1.1.x images.
related to: https://github.com/harvester/harvester/issues/2964

change to lookup interfaces using management_interface post v1.1.0

---

package/harvester-os/files/usr/sbin/harv-install

This adds a parameter to the grub bootloader which boosts performance of PCI devices enabled for passthrough by removing the need to do DMA translation.

Add iommu=pt for PCI passthrough

---

pkg/config/config.go

This PR contains some missing harvester settings in the GetSystemSettingsAllowList since Harvester v1.1.0. We need the containerd-registry setting during installation otherwise pulling the rancher-agent will fail when registering the Harvester cluster in Rancher in an air gapped environment.

added some missing harvester settings

---

package/harvester-os/iso/boot/grub2/grub.cfg

Related issue: https://github.com/harvester/harvester/issues/2937
Users can try to boot this entry if he or she sees resolution issues.
`vga=792` is deprecated, switch to `gfxpayload` variable.

ISO: add a GRUB menuentry to boot VGA with 1024x768 resolution

---

package/harvester-os/files/usr/sbin/harv-install

related issue: https://github.com/harvester/harvester/issues/2115
1. Test the installation with the ISO that contains this commit.
2. Make sure the installation is complete and boots up normally.
3. Check the path `/oem/grubenv`. The file should exist.

OS/grub: add default `grubenv` to prevent search hang

---

package/harvester-os/files/etc/cos/bootargs.cfg
package/harvester-os/files/usr/sbin/harv-install

PR superseedes: https://github.com/harvester/harvester-installer/pull/380
It fixes issue: https://github.com/harvester/harvester/issues/2973 by moving the iommu argument definition out of harv-installer and into bootargs.cfg.
This will ensure args are applied during both install and upgrade.

addition of iommu arguments to kernel boot args

---

scripts/package-harvester-os

Related issue: https://github.com/harvester/harvester/issues/3159
Update packages:
```
-----RPM-----
Packages found only in docker.io/rancher/harvester-os:20221123: None
Packages found only in docker.io/rancher/harvester-os:20221128-cdaa061: None
PACKAGE                  IMAGE1 (docker.io/rancher/harvester-os:20221123)        IMAGE2 (docker.io/rancher/harvester-os:20221128-cdaa061)
-grub2                   2.04-150300.22.20.2, 24.3M                              2.04-150300.22.25.1, 24.3M
-grub2-i386-pc           2.04-150300.22.20.2, 2.2M                               2.04-150300.22.25.1, 2.2M
-grub2-x86_64-efi        2.04-150300.22.20.2, 6.2M                               2.04-150300.22.25.1, 6.2M
-nginx                   1.19.8-3.6.1, 2.2M …
```

Bump OS to 20221128

---

scripts/package-harvester-os

```
PACKAGE                        IMAGE1 (docker.io/rancher/harvester-os:20221128)        IMAGE2 (docker.io/rancher/harvester-os:20221201)
-device-mapper                 1.02.163-8.42.1, 263.8K                                 2.03.05_1.02.163-150200.8.49.1, 263.8K
-libdevmapper-event1_03        1.02.163-8.42.1, 26.5K                                  2.03.05_1.02.163-150200.8.49.1, 26.5K
-libdevmapper1_03              1.02.163-8.42.1, 349.8K                                 2.03.05_1.02.163-150200.8.49.1, 349.8K
-libgcc_s1                     11.3.0+git1637-150000.1.11.2, 98.7K                     12.2.1+git416-150000.1.5.1, 122.7K
-liblvm2cmd2_03                2.03.05-8.42.1, 2.2M                                    2.03.05-150200.8.49.1, 2.2M
-libpython3_6m1_0 …
```

Bump OS 20221201

---

pkg/console/install_panels.go
pkg/console/util.go
pkg/console/util_test.go

[#2737](https://github.com/harvester/harvester/issues/2737)
**Test steps**
1. Build an ISO with this branch;
2. Use the artifacts built with this branch to construct a PXE server, configure a `join` configuration and use a server URL without port, like `https://172.16.0.240`;
3. Use the PXE server to boot up a node and start automatic installation;
4. Complete the installation and see if node successfully joined cluster;
5. Get into console, run `yq '.serverurl' < /oem/harvester.config` to see if server URL is correctly configured.
Signed-off-by: Yanhong Yang <yanhong.yang@suse.com>

Allow server_url without port and https prefix.

---

pkg/console/install_panels.go
pkg/console/util.go
pkg/console/util_test.go

[#3273](https://github.com/harvester/harvester/issues/3273)
Signed-off-by: Yanhong Yang <yanhong.yang@suse.com>

[Backport v1.1] Allow server_url without port and https prefix.

---

scripts/build-bundle

If we set environment variable REPO and PUSH, and run `make build-iso` from the harvester/harvester repo, the upgrade image is not found during an upgrade because the upgrade controller still uses the `rancher/harvester-upgrade:xxx` images. Fix this by not using the repository in the REPO variable.

Fix upgrade image is not found with build-iso

---

.drone.yml

Only trigger pipelines on these branches:
- master
- v*
This avoids running publish pipeline on mergify backport PR branches (e.g. `mergify/bp/v1.1/pr-385` of PR https://github.com/harvester/harvester-installer/pull/391. [Error](https://drone-publish.rancher.io/harvester/harvester-installer/1074))

Drone: specify branches to trigger pipelines

---

package/harvester-os/files/etc/systemd/system/rancherd.service.d/override.conf
package/harvester-os/files/etc/systemd/system/rke2-agent.service.d/override.conf
package/harvester-os/files/etc/systemd/system/rke2-server.service.d/override.conf
package/harvester-os/files/etc/systemd/system/systemd-time-wait-sync.service.d/override.conf
package/harvester-os/files/system/oem/06_ntp.yaml
pkg/config/cos.go

use time-sync.target
wait for 3 min to sync time
if time sync took more 3 min, skip it and start rancherd, rke2-server and rke2-agent directly.
issue: https://github.com/harvester/harvester/issues/2860

ntp: rancher, rke2-server rke2-agent need to wait for time sync

---

package/harvester-os/files/etc/systemd/system/rancherd.service.d/override.conf
package/harvester-os/files/etc/systemd/system/rke2-agent.service.d/override.conf
package/harvester-os/files/etc/systemd/system/rke2-server.service.d/override.conf
package/harvester-os/files/etc/systemd/system/systemd-time-wait-sync.service.d/override.conf
package/harvester-os/files/system/oem/06_ntp.yaml
pkg/config/cos.go

backport PR https://github.com/harvester/harvester-installer/pull/373
use time-sync.target
wait for 3 min to sync time
if time sync took more 3 min, skip it and start rancherd, rke2-server and rke2-agent directly.

[Backport v1.1] ntp: rancher, rke2-server rke2-agent need to wait for time sync

---

package/harvester-os/files/usr/sbin/cos-installer-shutdown
package/harvester-os/files/usr/sbin/harv-install
pkg/config/cos.go
pkg/config/schemas_test.go
pkg/console/util.go
scripts/package-harvester-os

We cannot use Elemental-cli InstallSpec struct to generate config.yaml. Because there are not all entry with "omitempty", it will cause generated config.yaml will have several empty entry but didn't be omitted.
Elemental-cli will treat those empty entry as user-specific value and override the default value.
Use ElementalInstallSpec to ensure that all entry will be "omitempty".
We must to use patched OS2 image to build iso
`git clone -b elemental https://github.com/tjjh89017/os2`
https://github.com/harvester/os2/pull/51

elemental: bump elemental-cli to v0.1.0

---

.drone.yml

Attempt to fix CI error: 
```
/usr/local/bin/docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "./scripts/entry": stat ./scripts/entry: no such file or directory: unknown.
time="2023-02-03T00:50:51Z" level=error msg="error waiting for container: context canceled"
```
The source is not copied to the home we set:
```
#6 [2/2] COPY . /source/
```
- https://drone-pr.rancher.io/harvester/harvester-installer/1181/1/2

CI: bump dapper version to v0.5.8

---

scripts/package-harvester-os

- change the baseOS to SLE Micro for Rancher 5.3
- add sysvinit-tools back
- add wicked back and remove the NetworkManager
- add k9s (v0.26.7)
Signed-off-by: Vicente Cheng <vicente.cheng@suse.com>

OS: bump OS to 20230207

---

scripts/package-harvester-os

- change the baseOS to SLE Micro for Rancher 5.3
- add sysvinit-tools back
- add wicked back and remove the NetworkManager
- add k9s (v0.26.7)
Signed-off-by: Vicente Cheng <vicente.cheng@suse.com>
(cherry picked from commit d8930db4be133cf516ee931629dde6a7679b09b2)
related to: https://github.com/harvester/harvester/issues/3280

[v1.1 backport] OS: bump OS to 20230207

---

pkg/console/dashboard_panels.go
pkg/console/install_panels.go
pkg/util/crypt.go
pkg/util/crypt_test.go
vendor/github.com/tredoe/osutil/user/crypt/apr1_crypt/apr1_crypt.go
vendor/github.com/tredoe/osutil/user/crypt/md5_crypt/md5_crypt.go
vendor/github.com/tredoe/osutil/user/crypt/sha256_crypt/sha256_crypt.go

**Related issue:**
[#3051](https://github.com/harvester/harvester/issues/3051)
**Test steps:**
1. Prepare an iPXE installation environment, set the password using `openssl passwd -1` for MD5 based password;
2. Install a Harvester instance using iPXE;
3. After boot up, try to use the password set in `config.yaml` to get into the console.

Add compatibility for password hashing algorithms rather than only SHA-512

---

ci/run_vagrant_install_test.yml
ci/terraform/enable_soft_emulation.sh
ci/terraform/in-scripts/patch-kubevirt.sh
ci/terraform/test_terraform_vm.sh

Enable soft-emulation, the new kernel seems not to play well with the Equinix EPYC instance.
- Set the configuration in KubeVirt CR. Do this in VM to avoid downloading kubectl.
```
spec:
configuration:
developerConfiguration:
useEmulation: true
```
- Update pinging code to a checking loop (timeout 5 minutes).
Related issue: https://github.com/harvester/harvester/issues/3447

CI: Enable software-emulation for nested VMs

---

scripts/package-harvester-os

Base OS changes:
```
-----RPM-----
Packages found only in docker.io/rancher/harvester-os:20230207: None
Packages found only in docker.io/rancher/harvester-os:20230209: None
PACKAGE               IMAGE1 (docker.io/rancher/harvester-os:20230207)        IMAGE2 (docker.io/rancher/harvester-os:20230209)
-libopenssl1_1        1.1.1l-150400.7.19.1, 3.9M                              1.1.1l-150400.7.22.1, 3.9M
-openssl-1_1          1.1.1l-150400.7.19.1, 1.6M                              1.1.1l-150400.7.22.1, 1.6M
```

Bump OS to 20230209

---

pkg/config/cos.go

Signed-off-by: Yanhong Yang <yanhong.yang@suse.com>
**Related issue:**
[#3366](https://github.com/harvester/harvester/issues/3366)
**Test steps:**
1. Prepare a iPXE installation environment, in `config.yaml` add these modules:
```
os:
modules:
- kvm
- nvme
- vhost_net
```
2. Install a Harvester instance using iPXE;
3. After boot up, enter the console and use command `lsmod | grep nvme` to check if nvme module loaded;
4. Use command `lsmod | grep vhost_net` to check if vhost_net module loaded;

Use modprobe to load modules at initramfs stage instead of using cloud-init.

---

pkg/config/cos.go

**Related issue:**
[#3367](https://github.com/harvester/harvester/issues/3367)

[v1.1 backport] Use modprobe to load modules at initramfs stage instead of using cloud-init.

---

scripts/package-harvester-os

- Serval packages update on the SLE-Mircro-for-Rancher 5.3

os: bump OS to 20230220

---

package/harvester-os/files/system/oem/91_installer.yaml

**Problem:**
Add the parameter to disable the installer
**Solution:**
add `harvester.installer.disable` to control the installer setup
https://github.com/harvester/harvester/issues/2663
**Test plan:**
Test the following three cases:
1. Do not change /proc/cmdline -> should go into installer
2. Add `harvester.installer.disable=false` to /proc/cmdline -> should go into installer
3. Add `harvester.installer.disable=true` to /proc/cmdline -> should not go into installer 
How to modify `/proc/cmdline`, you can refer the following steps:
1. when you enter the grub, press `esc` to stop on this console
2. then press `e` to modify `/proc/cmdline`, the following picture is original
3. modify the `/proc/cmdline` like the above test cases
4. finally, press `ctrl + x` to bootup, …

installer: add parameter to disable installer

---

ci/run_vagrant_install_test.yml
ci/terraform/check_services_status.sh
package/harvester-os/files/system/oem/10_services.yaml

**Problem:**
We need to disable avahi-daemon for the security scan.
**Solution:**
Disable avahi-daemon by default
https://github.com/harvester/harvester/issues/3573
**Test plan:**
Check the avahi-daemon should not be enabled

Disable avahi daemon

---

scripts/package-harvester-os

bump os to 20230302 for various packages updated
```
PACKAGE                  IMAGE1 (docker.io/rancher/harvester-os:20230220)        IMAGE2 (docker.io/rancher/harvester-os:20230302)
-kdump                   1.0.2+git18.g615d6ab-150400.3.8.1, 1M                   1.0.2+git20.g64239cc-150400.3.11.1, 1M
-libopenssl1_1           1.1.1l-150400.7.22.1, 3.9M                              1.1.1l-150400.7.25.1, 3.9M
-libpython3_6m1_0        3.6.15-150300.10.37.2, 2.7M                             3.6.15-150300.10.40.1, 2.7M
-libsystemd0             249.14-150400.8.19.1, 926.9K                            249.15-150400.8.22.1, 926.9K
-libudev1                249.14-150400.8.19.1, 240.4K                            249.15-150400.8.22.1, 240.4K
-libxslt1 …
```

build: bump os to 20230302

---

scripts/package-harvester-os

**Problem:**
Can not install harvester by interactive installation because we remove the yip command
**Solution:**
add yip back
https://github.com/harvester/harvester/issues/3584
**Test plan:**
Ensure the interactive installation is workable.

build: bump os to 20230303

---

scripts/build-bundle
scripts/version-harvester

**Problem:**
Sometimes we need to verify the bug fixes or feature deliveries in the upgrade area, it's essential to upgrade from the master-head to master-head with the exact same ISO image downloaded from `https://releases.rancher.com/harvester/master/harvester-master-amd64.iso`. But the `server-version` does not match with the image tag for `rancher/harvester-upgrade` image for such cases. The upgrade will then fail at the image-preloading phase as it cannot find the right image on the node nor on the Internet (if not air-gapped).
This is due to a different `VERSION` argument passed into the `harvester-upgrade` `docker build` command in `.drone.yaml`:
```
...
- name: docker-publish-upgrade-branch
image: plugins/docker
settings:
build_args:
- ARCH=amd64
- …
```

fix(upgrade): make upgrades from master to master possible

---

scripts/version-rke2

Bump RKE2 to `v1.24.11+rke2r1`.
There is no change after v1.24.11-rc1+rke2r1, just to change to the formal release version.

Bump RKE2 to v1.24.11+rke2r1

---

scripts/build
scripts/build-bundle

Make sure we use the correct backend code when building from the v1.1 branch.
Fix the ISO using the wrong harvester/harvester code if its build is triggered from the `harvester/harvester-installer` repo.

Use the v1.1 harvester branch

---

pkg/config/templates/cos-rootfs.yaml

**Problem:**
The default rook ceph cluster data path on the host is '/var/lib/rook'. However, this path is non-persistent on Harvester OS, which will cause the osd of rook ceph to crash after the node restarts.
We need a directory to store data for a third-party component like rook
**Solution:**
Add /var/lib/third-party to PERSISTENT_STATE_PATHS
https://github.com/harvester/harvester/issues/2405
**Test plan:**
Refer to https://github.com/harvester/harvester/pull/3566

Add /var/lib/third-party to PERSISTENT_STATE_PATHS

---

scripts/package-harvester-os

**Problem:**
base os needs to update
**Solution:**
bump to the latest base os `20230323`
**Test plan:**
**Additional appendix:**
The whole updated packages are below.
```
PACKAGE                   IMAGE1 (docker.io/rancher/harvester-os:20230303)        IMAGE2 (docker.io/rancher/harvester-os:20230323)
-grub2                    2.06-150400.11.17.1, 25M                                2.06-150400.11.23.2, 25M
-grub2-i386-pc            2.06-150400.11.17.1, 2.4M                               2.06-150400.11.23.2, 2.3M
-grub2-x86_64-efi         2.06-150400.11.17.1, 6.6M                               2.06-150400.11.23.2, 6.5M
-k9s                      0.26.7-150400.6.3, 74.8M                                0.26.7-150400.6.5, 74.8M
-kbd …
```

build: bump base os to 20230323

---

scripts/package-harvester-os

**Problem:**
Some packages of harvester base os need to update
**Solution:**
bump harvester base os to the latest
**Test plan:**
**Additional appendix:**
The whole updated packages are below.
```
PACKAGE                    IMAGE1 (docker.io/rancher/harvester-os:20230323)        IMAGE2 (docker.io/rancher/harvester-os:20230328)
-curl                      7.79.1-150400.5.15.1, 729.5K                            7.79.1-150400.5.18.1, 729.5K
-libcurl4                  7.79.1-150400.5.15.1, 630.7K                            7.79.1-150400.5.18.1, 630.7K
-libndctl6                 71.1-150400.8.5, 253.9K                                 71.1-150400.10.3.1, 253.9K
-librados2                 16.2.9.536+g41a9f9a5573-150400.3.3.1, 12.5M …
```

build: bump base os to 20230328

---

scripts/package-harvester-os

**Problem:**
Some packages of harvester base os need to update
**Solution:**
bump harvester base os to the latest
**Test plan:**
**Additional appendix:**
The whole updated packages are below.
```
-----RPM-----
Packages found only in docker.io/rancher/harvester-os:20230406: None
Packages found only in docker.io/rancher/harvester-os:20230413: None
PACKAGE                  IMAGE1 (docker.io/rancher/harvester-os:20230406)        IMAGE2 (docker.io/rancher/harvester-os:20230413)
-haveged                 1.9.14-150400.1.5, 72.2K                                1.9.14-150400.3.3.1, 72.2K
-libhavege2              1.9.14-150400.1.5, 132.5K                               1.9.14-150400.3.3.1, 132.5K
-libsystemd0             249.15-150400.8.22.1, 926.9K …
```

build: bump base os to 20230413

---

pkg/config/config.go
pkg/config/config_test.go
pkg/config/cos.go
pkg/config/templates/cos-after-install-chroot.yaml

**Problem:**
Harvester OS does not support users adding additional software packages.
**Solution:**
To support this requirement, elemental-toolkit provides a stage called [after-install-chroot](https://rancher.github.io/elemental-toolkit/docs/customizing/stages/#after-install-chroot). Commands executed in this stage do not encounter file system write issues and the results of user commands are persistent and will not be lost due to a reboot. We can use this mechanism and expose it through Harvester Configuration.
https://github.com/harvester/harvester/issues/3689
**Test plan:**
1.  build iso from this PR
2.  install node use the following Harvester configuration example:
```yaml
os:
afterInstallChrootCommands:
- mkdir /bin/justatestdir
- cd /bin/justatestdir
- touch …
```

Support os.afterInstallChrootCommands in Harvester configuration

---

pkg/config/config.go
pkg/config/config_test.go
pkg/config/templates/cos-rootfs.yaml

**Problem:**
Currently, Harvester OS does not support custom paths for persistent storage or read-write paths. This means that any changes made to files not in default persistentStatePaths will be lost upon reboot.
**Solution:**
To address this issue, this pull request adds a  new options to the Harvester OS configuration in Harvester config. 
The `os.persistentStatePaths` option allows users to configure custom paths where modifications made to files will persist across reboots. This means that any changes made to files in these paths will not be lost upon reboot.
an config example for install rook-ceph in Harvester
```yaml
os:
persistentStatePaths:
- /var/lib/rook
modules:
- rbd
- nbd
``` 
Without this PR, users can achieve the same effect by modifying `/oem/90_custom.yaml` and then …

Support os.persistentStatePaths in Harvester configuration

---

pkg/config/templates/rancherd-10-harvester.yaml

**Problem:**
The `mcc-harvester` bundle CR will contain an errApplied status after setting a different default storageClass.
**Solution:**
Ignore the patch diff since Harvester is allowing users to config different default storageClass.
https://github.com/harvester/harvester/issues/3802
**Test plan:**
- spin up a new harvester cluster with the new ISO image.
- config a new storage class and set it as the default one.
- check the bundle status of the `mcc-harvester` later, it should not contain any errors like below:
```
ks get bundles -n fleet-local
NAME                                          BUNDLEDEPLOYMENTS-READY   STATUS
fleet-agent-local                             1/1
local-managed-system-agent                    1/1
mcc-harvester …
```

fix: ignore harvester patch diff of default sc

---

pkg/console/validator.go
pkg/console/validator_test.go

Add a check to the user input path that was missing from the previous PR 
https://github.com/harvester/harvester/issues/3688
**Test plan:**
**case 1**: The pathes used in the Harvester configuration os.persistentStatePaths is always the allowed path when installing
```yaml
os:
persistentStatePaths:
- /var/lib/rook
```
online url: https://bit.ly/420wRs3
The installation will be successful
**case 2**: Contain Nonabsolute path in the Harvester configuration os.persistentStatePaths when installing
```yaml
os:
persistentStatePaths:
- var/lib/rook
```
online url: https://bit.ly/3NcWjpP
An error `Invalid path. PersistentStatePath must be an absolute path` will be reported during installation
**case 3**: Contain disallowed path `/tmp` in the Harvester configuration …

Add checkPersistentStatePaths

---

package/harvester-os/files/usr/sbin/harv-install

**Problem:**
Originally, the installer places the tarballs under a specific location and brings up RKE2 server then import the container images by itself. This seems convenient, but when bad things happen it could be hard to diagnose/address.
**Solution:**
Now, the installer will bring up containerd only and actively import the images if it's an ISO installation (iPXE installation will be the same as usual). This prevents the hardcoded 15 mins timeout of RKE2 from happening on a slow-speed media installation such as IPMI and USB. And it also provides better observability for users to know the progress of an installation.
harvester/harvester#2651
**Test plan:**
ISO mode (the installation could take much longer than expected, but it should success eventually)
1. Install …

fix(install): bring up containerd only

---

Dockerfile.dapper
scripts/images/cache.yaml
scripts/lib/image

Add the support to skip image pulling if images are already on the system.
Note images with the repository or tag in the following exclude list are always pulled:
```
╰─$ cat scripts/images/cache.yaml
exclude:
repos:
- docker.io/rancher/harvester
- docker.io/rancher/harvester-webhook
- docker.io/rancher/harvester-upgrade
tags: []
```
Images with `*-head` tags are always pulled.
Usage:
```
USE_LOCAL_IMAGES=true make
```
If env `USE_LOCAL_IMAGES` is not provided, we'll try pull images as usual.

Speedup image pulling process

---

package/harvester-os/files/etc/systemd/system/rke2-shutdown.service
package/harvester-os/files/system/oem/91_rke2-shutdown.yaml
package/harvester-os/files/usr/sbin/rke2-kill-containers.sh

**Problem:**
https://github.com/harvester/harvester/issues/1876
**Solution:**
Create a rke2-shutdown.service to run rke2-kill-containers.sh to stop all the running pods (containers) before the system shutdown or reboots. 
The script executes the systemd stop(--kill-who=all) container unit in parallel. Systemd sends a SIGTERM signal to the process first, and if there is no response within the timeout, it will send a SIGKILL signal to the process. 
Through testing, there has been a significant improvement in ext4 errors during container unmounting, but some ext4 errors still occur, which are not fundamentally related to the container program. The following is the ext4 log recorded during the reboot:
```
Apr 19 09:40:40 localhost dracut-initqueue[871]: The superblock could not be read or …
```

Fixed umount error during shutdown

---

pkg/config/config.go
pkg/console/install_panels.go
pkg/console/util.go

**Problem:**
If we can config the NTP server on UI, we need to make it consistent after the first node creation.
**Solution:**
write the related setting with the mechanism of updating the system settings
https://github.com/harvester/harvester/issues/3133
**Test plan:**
Make sure we have `20-harvester-settings.yaml` and it should contain the ntp-servers information

config: update NTP to SystemSettings

---

pkg/config/templates/patch/rancher-monitoring/102.0.0+up40.1.2/nginx-config.yaml
scripts/hack/patch-rancher-monitoring

fix grafana dashboard 404 issue
Signed-off-by: Jian Wang <w13915984028@gmail.com>
**Problem:**
The `grafana` dashboard does not show correctly in local mode and rancher managed multi-cluster mode
**Solution:**
Config grafana nginx to generate `appSubUrl` dynamically.
https://github.com/harvester/harvester/issues/4087
The previous issue https://github.com/harvester/harvester/issues/3780 and PR https://github.com/harvester/harvester-installer/pull/492.  Can work for local mode, but not for multi-cluster mode.
**Test plan:**
1. install Harvester
2. enable `rancher-monitoring` addon
3. view cluster metrics, vm metrics from Harvester dashboard
4. click `grafana` to open indepedent window
5. import this Harvester into Rancher
6. repeat 3 in Rancher
7. repeat 4 in Rancher
all …

fix grafana dashboard 404 issue

---

package/harvester-os/files/usr/sbin/gen-kdump-initrd

**Problem:**
By default `dracut` uses Zstandard to compress initrd, and we're trying to use xzcat to decompress initrd which makes `kdump.service` fail to start.
**Solution:**
Add `--xz` when calling dracut to use xz compression.
https://github.com/harvester/harvester/issues/3928
**Test plan:**
1. Build an ISO from this branch and deploy;
2. Select debug mode when booting;
3. After booted up, use command `systemctl status kdump.service` to confirm `kdump.service` is up and running;
4. After `kdump.service` exited, use command `echo c > /proc/sysrq-trigger` to trigger a kernel crash manually;
5. The system should reboot automatically and a progress bar (sort of) of kernel dump should show up;
6. After rebooted, select debug mode again, and see if anything under …

Specify --xz explicitly when calling dracut to make initrd.

---

pkg/config/templates/rancherd-22-addons.yaml
scripts/build-bundle

**Problem:**
PR introduces pcidevices controller addon v0.2.5-rc2 chart.
PCIDevices Addon is no longer label experimental.
**Solution:**
**Test plan:**

update pcidevices addon to v0.2.5-rc2

---

Dockerfile.dapper
package/harvester-os/files/usr/sbin/harv-dummy-iface
package/harvester-os/files/usr/sbin/harv-restart-services
package/harvester-os/files/usr/sbin/stream-disk
package/harvester-os/iso/boot/grub2/grub.cfg
pkg/config/config.go
pkg/config/constants.go
pkg/config/cos.go
pkg/config/cos_test.go
pkg/config/read.go
pkg/config/read_test.go
pkg/config/testdata/userdata.yaml
pkg/console/console.go
pkg/console/dashboard_panels.go
pkg/console/helper.go
pkg/console/install_panels.go
pkg/console/util.go
pkg/console/validator.go
scripts/package-harvester-os

**Problem:**
Support ability to install harvester to a machine without configuring the node.
**Solution:**
PR introduces a new install mode, which allows users to install the harvester binaries to disk, without configuring the k8s components.
This allows users to install harvester and ship devices to remote location for configuration on first boot.
In addition, the PR also introduces generation of a pre-installed qcow2 image which can be later used with the new install mode and automatic installation to stream disk to image, there by improving provisioning times in public cloud providers like equinix metal.
In automatic install mode, if a config_url is provided, then the same is also written to disk, and node will auto configure on the first boot, ensuring faster provisioning.
**Related …

Install mode

---

Dockerfile.dapper

**Problem:**
install image build is not triggered via https://github.com/harvester/harvester-installer/pull/530
**Solution:**
pass `DRONE_BUILD_EVENT` to dapper
**Test plan:**
need to re-run the Drone cron job to validate it.

pass DRONE_BUILD_EVENT to dapper

---

pkg/console/install_panels.go

**Problem:**
PR introduces a minor change to the installer to direct panel flow to password panel when node has multiple disks.
When multiple disks are present the disk choose page, after choosing the installation disk, the installer guides user to hostname panel even when install node is present.
**Solution:**
The PR changes the workflow when additional disks are present on the node.
**Test plan:**

minor change to panel flow when machine has multiple disks

---

.drone.yml
scripts/package-harvester-repo

Related issue: https://github.com/harvester/harvester/issues/2670
The image is published when:
- merging codes to master and stable branches in the harvester-installer repo (this PR).
- cron CI job runs in the harvester-installer repo (this PR).
- merging codes to master and stable branches in the harvester/harvester repo (https://github.com/harvester/harvester/pull/4223).

Publish harvester-cluster-repo image

---

pkg/config/config.go
pkg/console/constant.go
pkg/console/helper.go
pkg/console/install_panels.go
pkg/console/util.go
pkg/console/validator.go
pkg/widgets/dropdown.go

**Problem:**
When selecting different disk for data, 250Gi limit for installation disk is too large.
**Solution:**
Change the limit to 180Gi when using different disk for data.
https://github.com/harvester/harvester/issues/4133
**Test plan:**
1. Build an ISO from this branch;
2. Boot into the installer, the installer should limit the installation disk at 250Gi minimum.
1. Build an ISO from this branch;
2. Boot into the installer, and use the same disk for installation disk and data disk;
3. The installer should limit the installation disk at 250Gi minimum;
4. When choosing different disk for installation and data, the installer should limit the installation disk at 180Gi minimum.
1. Build artifacts from this branch;
2. Use PXE to install Harvester artifacts you just …

Change installation disk space limit to 180Gi when using different disk for data.

---

scripts/images/harvester-additional-images.txt

**Problem:**
bump the vmdp driver to the newer version that SUSE supports https://www.suse.com/lifecycle#product-suse-linux-enterprise-virtual-machine-driver-pack
**Solution:**
bump vmdp Windows driver image to [v2.5.4.2](https://github.com/SUSE/vmdp/releases/tag/v2.5.4.2)
https://github.com/harvester/harvester/issues/4365
**Test plan:**
Refer to https://github.com/harvester/harvester/pull/4351#issue-1830684793 VMDP test, also the image is preloaded in the OS.

bump vmdp image

---

pkg/config/templates/patch/rancher-monitoring/102.0.0+up40.1.2/nginx-config.yaml

When accessing vm metrics from Rancher to Harvester to VM, 404 error is return due to wrong appSubUrl
**Problem:**
When accessing vm metrics from Rancher to Harvester to VM, 404 error is return. 
Such a field is returned:
>"appSubUrl": "/k8s/clusters/c-m-8zxqjrgg/kubevirt.io.virtualmachine/default/api/v1/namespaces/cattle-monitoring-system/services/http:rancher-monitoring-grafana:80/proxy",
The expected value is:
>"appSubUrl": "/k8s/clusters/c-m-8zxqjrgg/api/v1/namespaces/cattle-monitoring-system/services/http:rancher-monitoring-grafana:80/proxy",
**Solution:**
In nginx config, add long match for http referer field, to filter the path like `kubevirt.io.virtualmachine/default/vm2`
```
Referer:
https://VIP/dashboard/harvester/c/c-m-8zxqjrgg/kubevirt.io.virtualmachine/default/vm2
```
is …

Fix grafana vm metrics 404 error in multi cluster

---

scripts/package-harvester-os

**Problem:**
Harvester puts all container image names into a tarball `image-lists.tar.gz`, and this file is not published.
It is not very convenient to check if an image is packed into ISO file.
**Solution:**
Generate an additional single txt file, which includes all images in the ISO, and `also publish this file`.
https://github.com/harvester/harvester/issues/4176
**Test plan:**
1. Build the Harvester ISO
2. Check if the `image-all.txt` is existing in the path `dist/artifacts`
3. Check all images are listed in this file
4. Check the first line of this file, the timestamp should be updated after each successful building
> cat dist/artifacts/image-all.txt 
```
docker.io/rancher/harvester-upgrade:04c258b9
docker.io/rancher/harvester-upgrade:master-04c258b9-head …
```

Collect all images into one single txt file

---

pkg/config/cos.go

Elemental calculates the image size automatically now. Change the image size back to 3G for consistency.
**Problem:**
Elemental calculates the image size automatically. So right now the image is near 1.5 G, which is inconsistent with previous versions.
**Solution:**
Use elemental config and change the image size back to 3G.
https://github.com/harvester/harvester/issues/4479
**Test plan:**
- Create a new installation.
- Check active.img and passive.img size is 3G.
```
node1:~ # ls -alh /run/initramfs/cos-state/cOS/*
-rw-r--r-- 1 root root 3.0G Sep  5 16:15 /run/initramfs/cos-state/cOS/active.img
-rw-r--r-- 1 root root 3.0G Sep  5 16:15 /run/initramfs/cos-state/cOS/passive.img
```

Change the active.img size to 3G

---

scripts/package-harvester-os

**Problem:**
The boot partition changed after we repacked to support the legacy BIOS.
That would make the installation hang because of the wrong partition. We depend on the COS_LIVE to mount the data partition on installation.
**Solution:**
Keep the boot partition has the `COS_GRUB` label
https://github.com/harvester/harvester/issues/4510
**Test plan:**
Make sure the whole installation works as usual.

build: keep the boot partition with label COS_GRUB

---

pkg/config/cos.go

**Problem:**
Invalid setup when setting partition table type to MBR in the installer. The string in the elemental `config.yaml` should be `msdos`, not `mbr`
**Solution:**
Change the string in `PartTable` to the correct value
harvester/harvester#4515
**Test plan:**

Fix partition table type

---

package/harvester-os/files/usr/sbin/harv-install

**Problem:**
We might stuck in `Welcome to GRUB!` message for ~30min when installing Harvester on baremetal machines with Dell's [BOSS-S1 RAID card](https://www.dell.com/support/manuals/en-us/poweredge-r7425/boss_s1_ug_publication).
**Solution:**
Add `/oem/grubcustom` manually to prevent long time search for this file when booting up.
https://github.com/harvester/harvester/issues/4334
**Test plan:**
1. Find a server with BOSS-S1 card, and some M.2 disks installed on the card;
2. Build an ISO using this branch;
3. Use the ISO just built to install Harvester on this server, must be installed on the disk installed on BOSS-S1 card;
4. Boot up the machine, and it should not stuck on `Welcome to GRUB!` for too long.
**Additional context:**
If you want to test this on Equinix …

Add grubcustom manually to prevent stuck on GRUB menu when using BOSS-S1 RAID card.

---

package/harvester-os/iso/boot/grub2/grub.cfg

Some machines have a hard time booting with the parameter on.
**Problem:**
Some machines have a hard time booting with the parameter on.
**Solution:**
Remove the parameter. If the user needs it, he or she can add it manually in the GRUB menu.
https://github.com/harvester/harvester/issues/4586
**Test plan:**
- Boot the ISO.
- check `console=ttyS0` isn't present in `/proc/cmdline`.

ISO boot: do not set ttyS0 as console

---

scripts/images/harvester-additional-images.txt

**Problem:**
bump the vmdp driver to the newer version that SUSE supports https://www.suse.com/lifecycle#product-suse-linux-enterprise-virtual-machine-driver-pack
**Solution:**
bump vmdp Windows driver image to [v2.5.4.2](https://github.com/SUSE/vmdp/releases/tag/v2.5.4.2)
https://github.com/harvester/harvester/issues/4367
**Test plan:**
Refer to https://github.com/harvester/harvester/pull/4351#issue-1830684793 VMDP test, also the image is preloaded in the OS.

feat: update vmdp version to 2.5.4.2

---

package/harvester-os/Dockerfile

**Problem:**
We used latest version to get wharfie. The CI may be broken if latest version doesn't have artifacts like https://github.com/rancher/wharfie/releases/tag/v0.6.3.
**Solution:**
Use number version.
https://github.com/harvester/harvester/issues/4676
**Test plan:**
N/A

feat: use number version in harvester-os Dockerfile

---

package/harvester-os/files/usr/sbin/harv-install

**Problem:**
Try to get more logs when we use the elemental command.
**Solution:**
Add debug parameter
https://github.com/harvester/harvester/issues/4541
**Test plan:**
make sure the installation as usual

common: always set log level to debug when we install

---

pkg/config/templates/rancherd-13-monitoring.yaml

**Problem:**
When apply storagenetwork in Harvester, CRD objects prometheus and alertmanager are changed, and prometheus will complain, which may even block upgrade.
**Solution:**
Add them into fleet diff path.
Due to there are big amount of differences imported by the storagenetwork fix, to be sure, we skip the `/spec` and `/status` of those 2 objects.
```
- apiVersion: monitoring.coreos.com/v1
fieldsType: FieldsV1
fieldsV1:
f:spec:
f:arbitraryFSAccessThroughSMs: {}
f:containers: {}
f:replicas: {}
f:resources:
f:limits:
f:cpu: {}
f:rules:
.: {}
f:alert: {}
f:storage:
f:volumeClaimTemplate:
f:metadata: {}
f:status: {}
f:status:
.: {}
f:availableReplicas: {}
f:paused: {}
f:replicas: {}
f:unavailableReplicas: {}
f:updatedReplicas: {}
manager: harvester
``` …

fix 3979 3839 add prometheus and alertmanager to diff list

---

package/harvester-os/files/system/oem/91_installer.yaml
package/harvester-os/files/usr/bin/setup-installer.sh

related issue: https://github.com/harvester/harvester/issues/4648

installer: reorder the patch operation for tty service

---

package/Dockerfile
package/harvester-repo/Dockerfile

**Problem:**
SLE 15 SP4 general ends on 31 Dec 2023.
**Solution:**
Bump SLE BCI images to to 15.5.
https://github.com/harvester/harvester/issues/4757
**Test plan:**
Test basic operation can work.

feat: bump SLE to 15.5

---

pkg/config/cos_test.go
pkg/console/install_panels.go
pkg/console/util.go
pkg/util/disk.go
pkg/util/disk_test.go

**Problem:**
The error messages are sometimes unclear when one has an installation disk that's too small.
**Solution:**
This commit adds disk size validation in the calls to `diskConfirm()` and `dataDiskConfirm()`, so that as you walk through the fields you'll see potential error messages as you go, rather than having to wait until leaving the last field on the page.  The error message clears if you press the up arrow to go to previous fields.
The persistent partition size check remains where it is, i.e. it's only done when you try to move to the next page.  I couldn't figure out a neat way to incorporate this into the `validateAllDiskSizes()` function, which gets called before the default persistent size is set in `persistentSizeV.PreShow()`.
This commit also changes the wording of the …

console: validate disk size earlier, update error wording

---

Dockerfile.dapper
package/harvester-os/manifest.yaml
scripts/package-harvester-os

**Problem:**
We want to bump elemental to the newer version and drop luet.
**Solution:**
update the build flow to match the new elemental binary
**Test plan:**
1. Make sure the installation work as usual
2. Make sure the cluster operation as susal

build: use newer elemental to build iso

---

package/harvester-os/files/etc/systemd/system/rancher-system-agent.service.d/env.conf

**Problem:**
Run `journalctl -u rancher-system-agent.service` in harvester node and we can see log like:
```
Dec 01 02:27:39 harvester-node-0 rancher-system-agent[15569]: time="2023-12-01T02:27:39Z" level=info msg="[Applyinator] Running command: sh [-c rke2 etcd-snapshot list --etcd-s3=false 2>/dev/null]"
Dec 01 02:27:39 harvester-node-0 rancher-system-agent[15569]: time="2023-12-01T02:27:39Z" level=info msg="[Applyinator] Command sh [-c rke2 etcd-snapshot list --etcd-s3=false 2>/dev/null] finished with err: <nil> and exit code: 127"
```
**Solution:**
Add `/opt/rke2/bin` to rancher-system-agent `PATH`.
https://github.com/harvester/harvester/issues/4803
**Test plan:**
1. Install harvester.
2. Run `journalctl -u rancher-system-agent.service` and see `rke2 etcd-snapshot …

feat: add rancher-system-agent env.conf

---

Dockerfile.dapper

**Problem:**
The golangci-lint version before v1.51.0 may have OOM issue with golang v1.20.
**Solution:**
Bump golangci-lint to a version after v1.51.0.
https://github.com/harvester/harvester/issues/4938

feat: bump golangci-lint to v1.55.2

---

pkg/config/templates/patch/rancher-monitoring/102.0.0+up40.1.2/nginx-config.yaml

**Problem:**
The `grafana` login page showed 404.
A main reason is, when accesing grafana from the local cluster, the general URL is `https://1.2.3.4/k8s/clusters/local/api/v1/....`, the Rancher will trim `/k8s/clusters/local/`, this works fine for normal link. But for `login`, it is another story, the `grafana` will return a `302` code with a new `Location`, unfortunately, the `Rancher` will NOT add `/k8s/clusters/local` back to the `Location`. When grafana's front page code runs, it will get a different `appSubUrl` and assume error, then showed 404 page.
For rancher managed cluster, the regex processing in appSubUrl is not perfect to deal with `302`.
**Solution:**
(1) For local cluster, add a fallback item in the nginx sub-filter
(2) For rancher-managed cluster, use long match in regex …

Fix grafana login issue

---

pkg/config/config.go
pkg/config/cos.go

**Problem:**
Give the way to config `sftp` dynamically
**Solution:**
We could set up the `harvester.os.sshd.sftp` to true.
The harvester-installer would create the related config file by stage `AfterInstallChrootCommands`
We also need the https://github.com/harvester/os2/pull/78
That would include the customer config that we would like to add.
https://github.com/harvester/harvester/issues/4480
**Test plan:**
- Perform an ipxe-example installation with this config
```
os:
sshd:
sftp: true
```
- Try to access sftp
```
sftp rancher@192.168.0.30
(rancher@192.168.0.30) Password:
Connected to 192.168.0.30.
sftp> 
```

config: make sftp could be configured dynamically

---

pkg/config/config.go
pkg/config/constants.go
pkg/config/cos.go
pkg/config/templates/rke2-99-harvester-witness.yaml
pkg/console/install_panels.go
pkg/console/util.go
pkg/util/common.go

**Problem:**
We can use `witness` instead `etcd`. The `witness` seems more suitable for the configuration.
**Solution:**
Change the console and label content. 
https://github.com/harvester/harvester/issues/4840
**Test plan:**
Make sure the interactive console show the `Witness Role`.
And node label should be `node-role.harvesterhci.io/witness: true`

installer: rename the role name witness instead etcd

---

pkg/widgets/select.go

**Problem:**
There's an off-by-one (or possibly off-by-two) error in the current implementation of the select widget, when there's content in the panel above it.  This means the last line of text in the panel is overwritten by the select widget (i.e. the select widget is one line too high). See the below screenshot where the text finishes with `Your disk will be formatted and Harvester will be installed with`:
**Solution:**
This commit changes the logic slightly to offset the select widget by the number of lines of panel content plus one, allowing all the text in the panel to be shown. Now we can see the full confirmation message plus a blank line above the select widget:
None (should I open one, or is it OK to just randomly fix things?)
**Test plan:**
- Run through the …

Don't cut off last line of text in panel above select widget

---

pkg/config/constants.go
pkg/console/install_panels.go
pkg/console/util.go
pkg/util/common.go

**Problem:**
We tried to support various roles, so the installer need the related changes.
**Solution:**
Add an interactive part for role selection. Also, we need to add the related label for it.
https://github.com/harvester/harvester/issues/4786
**Test plan:**
We can check this feature with two parts as below.
1. 3 node cluster with one worker node. (Should only have one management(master) in the cluster)
- create a cluster with three nodes
- choose `worker` role on the second or third node
- make sure the final cluster only has one management(master)
2. 5 node cluster (to test promote will promote the management role first)
- create a cluster with five nodes
- choose `management` role on the fifth node
- remove the second or third management (master) node
- it should …

installer/config: add the role setup

---

README.md
pkg/config/config.go
pkg/console/console.go
pkg/console/constant.go
pkg/console/install_panels.go
pkg/preflight/checks.go
pkg/preflight/checks_test.go
pkg/preflight/testdata/meminfo-32GiB
pkg/preflight/testdata/meminfo-512MiB
pkg/preflight/testdata/meminfo-64GiB
pkg/widgets/panel.go
pkg/widgets/util.go

**Problem:**
We need to run some checks to ensure harvester is being installed on minimum supported hardware.
**Solution:**
This adds three preflight checks:
- Number of CPU cores
- Available memory
- Whether the system is running virtualized or not
Each check will result in a warning message if it doesn't pass. If there are any warning messages, a new page is inserted at the start of the installer listing the warnings and asking the user if they wish to proceed.  If the user selects "no", the system is rebooted. If there are no warnings, this page does not appear.
Outstanding issues:
- There are no unit tests.
- The warning messages are quite long, and wrap oddly on very small screens/terminal windows.
- The preflight checks have no effect for PXE/automated installs. For this path we …

Add hardware spec preflight checks

---

scripts/archive-images-lists.sh
scripts/package-harvester-os

**Problem:**
There's no way for Harvester itself to know the image list of each release. Such information is useful for the image cleanup mechanism introduced in harvester/harvester#4995.
**Solution:**
This will add all the previous versions' published image lists into the ISO image according to the upgrade matrix file in harvester repo
Based on [upgrade-helpers/bin/harv-purge-images.sh at d490e51c76b107c8d5df2df71d0e9b7000b392d6 · harvester/upgrade-helpers](https://github.com/harvester/upgrade-helpers/blob/d490e51c76b107c8d5df2df71d0e9b7000b392d6/bin/harv-purge-images.sh), downloading and adding all the previous versions' published image lists into the ISO image that is going to be built. These image lists will be used later for the upgrade controller to purge the unneeded container …

feat: add precedent image lists into iso image

---

pkg/console/console.go
pkg/preflight/checks.go
pkg/preflight/checks_test.go

**Problem:**
We need to make sure the host we're installing on supports hardware-assisted virtualization.
**Solution:**
This is pretty quick and dirty, but I hope should not be unreasonable. https://help.ubuntu.com/community/KVM/Installation tells us that we need to run `egrep -c '(vmx|svm)' /proc/cpuinfo` to check for hardware-assisted virtualization on x86_64 systems, but I think we can short-circuit that.
I reviewed the kvm-ok script (https://bazaar.launchpad.net/~cpu-checker-dev/cpu-checker/trunk/view/head:/kvm-ok) and it first checks for those CPU flags, and then next checks for the existence of /dev/kvm.  If both succeed, we're good.  But I don't think we actually need the CPU flag check, at least on SUSE distros.  I did some testing, and AFAICT if the CPU supports hardware …

Add preflight check for hardware-assisted virtualization

---

package/harvester-os/files/usr/sbin/harv-install
package/harvester-os/iso/boot/grub2/grub.cfg
pkg/config/config.go
pkg/console/install_panels.go
scripts/lib/iso
scripts/package-harvester-os

**Problem:**
To create a net-install ISO.
- Save time for downloading the installation medium.
- (hopefully) Prevent issues on buggy BMC ISO redirection feature: https://github.com/harvester/harvester/issues/2651
**Solution:**
We can ship a net-install ISO without image tarballs since we already https://github.com/harvester/harvester/issues/2670.
https://github.com/harvester/harvester/issues/4295
**Test plan:**
- Build the code
- Boot the net-install ISO (Its name is similar to `harvester-74e9450-dirty-amd64-net-install.iso`) and verify the installation. Both interactive mode and ipxe mode should work.
**Additional context**
- Add a kernel parameter `harvester.install.with_net_images=true` to GRUB menuentry in the net-install ISO. The installer only preloads the …

Feat: create a net-install ISO

---

package/harvester-os/files/usr/sbin/harv-install

**Problem:**
Because this is running without a TTY, it may be affecting IPMI-based installs that take hours to read the zst files off of virtual media.  
**Solution:**
This patch removes the progress flag from rsync in the hopes that it prevents rsync from freezing during install.
harvester/harvester#2651
**Test plan:**
Test install on slow IPMI virtual media

silence rsync progress in harv-install

---

pkg/preflight/checks.go
pkg/preflight/checks_test.go
pkg/widgets/panel.go

**Problem:**
When running under virtualization the current warning message says "System is virtualized (kvm) which is not supported", but should say "not supported in production". Also, in some cases, there's extra linebreaks in the warning messages, e.g.:
**Solution:**
This PR
https://github.com/harvester/harvester/issues/1154
**Test plan:**
N/A

Clarify wording of VirtCheck failure, fix weird line wrapping

---

package/harvester-os/files/usr/sbin/harv-install
pkg/config/config.go

**Problem:**
During out internal automation testing it is possible different disks were used to install of harvester.
When the disk is changed the older installation is left intact which can cause unexpected results during reboots.
To ensure this does not happen we need to be able to allow wiping of disks via the installer.
**Solution:**
PR adds an additional option in harvester config `wipeDisks` which can be passed via a config url or kernel arguments `harvester.install.wipe_disks=true` and will result in the harv-install script wiping all disks on the node.
https://github.com/harvester/harvester/issues/2066
https://github.com/harvester/harvester/issues/2781
https://github.com/harvester/harvester/issues/4527
**Test plan:**

additional installer option to wipe all disks before install

---

scripts/package-harvester-os

**Problem:**
Currently CI for arm64 and amd64 images overwrites the harvester-images-list.text and image-lists.tar.gz file.
**Solution:**
The PR adds an arch suffix to both these files.
https://github.com/harvester/harvester/issues/371
**Test plan:**

suffix os arch to harvester-images-list.txt and image-lists.tar.gz

---

scripts/package-harvester-os

**Problem:**
currently arm builds are not generating squashfs artifacts.
This is caused due to incorrect gating in the original arm support PR which only generates squashfs for amd64 archs.
**Solution:**
**Test plan:**

generate squashfs for arm builds

---

scripts/build
scripts/build-bundle

**Problem:**
Some charts are missed.
**Solution:**
Add then back
https://github.com/harvester/harvester/issues/5337
**Test plan:**
build log:
```
...
Successfully packaged chart and saved it to: /go/src/github.com/harvester/harvester-installer/package/harvester-repo/charts/rancher-logging-103.0.0+up3.17.10.tgz
finish patch ranch-logging chart
pull harvester-vm-import-controller: 0.1.7
pull harvester-pcidevices-controller: 0.3.2
pull harvester-seeder: 0.1.1
...
```

Fix build missed charts

---

pkg/console/tty.go

**Problem:**
For iso based installs, we added logic to skip ttyAMA0 as the serial console runs into resolution issues, and this causes the installer to crash. 
Automatic install fails on arm hosts since the installer checks first console which is generally always returned as ttyAMA0. As a result of which automatic install is never triggered.
**Solution:**
The PR attempts to fix this by skipping ttyAMA0 if
* there are multiple consoles specified
* ttyAMA0 is the first console
* underlying host is an arm64 machine
* 
**Test plan:**

added additional check for first console when booting on arm hosts

---

scripts/archive-images-lists.sh
scripts/package-harvester-os

**Problem:**
The script archive-image-lists.sh lacks architecture awareness and could potentially lead to failures within our CI pipeline, particularly if newer versions (> 1.3.0) have been released.
**Solution:**
Compare the version in `upgrade-matrix.yaml` with v1.3.0, if version >= v1.3.0, which means that version already support different architecture images, and we need to download the image lists tarball from  `https://releases.rancher.com/harvester/{VERSION}/image-lists-{ARCH}.tar.gz`.
https://github.com/harvester/harvester/issues/5313
**Test plan:**
1. Download harvester repo
2. replace [this line](https://github.com/harvester/harvester/blob/master/scripts/build-iso#L12) with `git clone --branch HARV-5313 --single-branch --depth 1 …

Make image list packing architecture-awared

---

.golangci.yaml
Dockerfile.dapper
go.mod
go.sum
pkg/config/coerce.go
pkg/config/cos_test.go
pkg/config/rename.go
pkg/console/console.go
pkg/console/dashboard_panels.go
pkg/console/helper.go
pkg/console/install_panels.go
pkg/console/util.go
pkg/console/util_test.go
pkg/console/webhooks_test.go
pkg/preflight/checks.go
pkg/preflight/checks_test.go
pkg/util/disk.go
pkg/util/disk_test.go
pkg/widgets/dropdown.go
pkg/widgets/panel.go
pkg/widgets/select.go
pkg/widgets/util.go

**Problem:**
Go v1.20 is EOL on 06 Feb 2024.
**Solution:**
Bump golang to v1.21.
https://github.com/harvester/harvester/issues/5310

Bump golang to v1.21

---

scripts/archive-images-lists.sh
scripts/package-harvester-os

backport #682 and #690 to branch v1.3
**Problem**:
The script archive-image-lists.sh lacks architecture awareness and could potentially lead to failures within our CI pipeline, particularly if newer versions (> 1.3.0) have been released.
**Solution**:
Compare the version in upgrade-matrix.yaml with v1.3.0, if version >= v1.3.0, which means that version already support different architecture images, and we need to download the image lists tarball from https://releases.rancher.com/harvester/{VERSION}/image-lists-{ARCH}.tar.gz.
**Related Issue**:
https://github.com/harvester/harvester/issues/5313
**Test plan**:
1. Download harvester repo
2. replace [this line](https://github.com/harvester/harvester/blob/master/scripts/build-iso#L12) with git clone --branch HARV-5313 --single-branch --depth 1 …

Make image list packing architecture awared (backport #682 and #690)

---

scripts/build

**Problem:**
When building against locally modified harvester source with "-v /path/to/local/harvester/repo:/go/src/github.com/harvester/harvester" added to DAPPER_RUNARGS, invocations of `git` run from `scripts/version` inside that path will fail with the error:
fatal: detected dubious ownership in repository at '/go/src/github.com/harvester/harvester'
This in turn breaks the harvester version detection.  HARVESTER_VERSION will be set to an empty string, and HARVESTER_CHART_VERSION will be set to "0.0.0--" which later messes up the harvester charts when `scripts/patch-harvester` is run.  Things do not end well after that.
**Solution:**
Happily, we can fix the above by running:
`git config --global --add safe.directory /go/src/github.com/harvester/harvester`
N/A
**Test …

build: Set git safe.directory /go/src/github.com/harvester/harvester

---

pkg/config/templates/rancherd-10-harvester.yaml

**Problem:**
Harvester ManagedChart is in modified status.
**Solution:**
Ignore the status fields on some Longhorn CRDs.
https://github.com/harvester/harvester/issues/5566
**Test plan:**
- Create a new cluster.
- Run `kubectl get bundles -n fleet-local mcc-harvester`, the `BUNDLEDEPLOYMENTS-READY` should be `1/1` and `STATUS` should be empty. For example:
```
NAME            BUNDLEDEPLOYMENTS-READY   STATUS
mcc-harvester   1/1
```

fix: Harvester management chart is modified

---

pkg/config/templates/rancherd-22-addons.yaml
scripts/build-bundle

This PR bumps the harvester-seeder image tag from v0.1.2; the chart is untouched.

chore: bump harvester-seeder to v0.1.2

---

pkg/config/config.go
pkg/config/cos.go
pkg/config/templates/rancherd-10-harvester.yaml

**Problem:**
Per https://github.com/harvester/harvester/issues/5568
**Solution:**
Update source code and document
https://github.com/harvester/harvester/issues/5568
**Test plan:**
Create new cluster, use a harvester-configuration file (step 13 of https://docs.harvesterhci.io/v1.2/install/index) with below items, after installation, check the embedded LH, the related setting is as expected.
https://longhorn.io/docs/1.5.3/references/settings/#guaranteed-instance-manager-cpu 
```
install:
harvester:
longhorn:
default_settings:
guaranteedInstanceManagerCPU: 6
```
(valid values are in range [0..12], all other values are converted to 12)
LH chart:
```
chart/templates/default-setting.yaml:    {{- if not (kindIs "invalid" .Values.defaultSettings.guaranteedInstanceManagerCPU) }} …
```

Add installation configure of LH GuaranteedInstanceManagerCPU

---

package/harvester-os/files/usr/sbin/harv-install

**Problem:**
https://github.com/harvester/os2/pull/86 adds a global_filter to /etc/lvm/lvm.conf to avoid activing LVM on the host.  Unfortunately, dracut-initqueue runs _very_ early in the boot process (before any of the elemental stages are run), so this filter isn't taken into account on boot, and LVM volumes are still potentially activated.  Later, when we try to run `blkdeactivate` in `harv-install`, it doesn't work, because the filter _is_ active then, so it skips deactivation and then the subsequent disk repartitioning fails.
**Solution:**
We can work around this by setting up a temporary lvm config which has that global_filter stripped out.
https://github.com/harvester/harvester/issues/5398
**Test plan:**
Note: this requires real hardware (I couldn't reproduce …

harv-install: deactivate LVM in spite of global_filter

---

pkg/console/install_panels.go

* if the user inputs DNS servers during the interactive ISO install they are then going to be shown during the confirm install panel
Resolves: feat/confirm-install-panel-show-dns-servers
See also: https://github.com/harvester/harvester/issues/5696
**Problem:**
Show the DNS Servers the user input from the interactive iso install on the confirm installation panel
**Solution:**
When the User is inputing DNS servers in the field seperated by comma on the interactive ISO install, currently, the user "cannot" see those input DNS servers on the final step of the interactive ISO install on the confirm installation panel.  This allows the user to see those DNS servers they input.  If the user did not input anything in the DNS Server section, the DNS servers will not be shown. …

feat: Show DNS Servers on Confirm Install Panel

---

pkg/console/install_panels.go

(cherry picked from commit 8593ff8daf3d6729bf170a23fd10198f262b0d7d)
**Problem:**
The configs specified in the kernel parameters should be merged into installer config for the wipe disk feature to work.
https://github.com/harvester/harvester/issues/5174

fix: merge kernel parameters into global config

---

pkg/console/install_panels.go
pkg/console/network.go

**Problem:**
RKE2 requires a default route to start, some installations are stuck with no obvious message if there is no default route on the system.
**Solution:**
Check the existence of the default route after applying network settings and stop the installation if no default route found. The check will be applied in both ISO and iPXE installation.
https://github.com/harvester/harvester/issues/5675
**Test plan:**
1. Set up a DHCP server and enable the iPXE capability which runs w/o `option routers x.x.x.x`
2. Proceed the Harvester ISO installation with the management network in DHCP mode.
3. Make sure the installer prompt the `No default route found` message and stop the installation
4. Proceed the iPXE automatic installation with pre-configured Harvester configuration …

enhancement: check default route during installation

---

Vagrantfile
pkg/preflight/checks.go
pkg/preflight/checks_test.go

**Problem:**
The current implementation of the preflight memory check uses `MemTotal` from `/proc/meminfo` to try to figure out how much RAM there is.  This number will always be a little bit low, which is confusing ("Why is it reporting only 60GiB when I know I have 64GiB?!?") and means we have to allow a certain amount of wiggle room when determining whether or not the system meets the minimum production requirements.
**Solution:**
This commit makes the following changes:
1. We use `dmidecode -t 19` to get the exact amount of memory installed in the system.  No weird low values, no need for wiggle room.
2. In case the above fails and we have to fall back to `/proc/meminfo`, increase the wiggle room from 5% to 10%.
3. For really low RAM scenarios (e.g. tiny test VMs with <1GiB RAM), …

Use dmidecode to check available RAM in preflight checks

---

pkg/console/install_panels.go
pkg/console/network.go

RKE2 requires a default route to work which is required during installation. The gateway setting will be checked in Static IP mode, but it could be absent in DHCP mode.
Check the existence of the default route after applying network settings and stop the installation if no default route found. The check will be applied in both ISO and iPXE installation.
Link: https://github.com/harvester/harvester/issues/5675
**Problem:**
Per https://github.com/harvester/harvester/issues/5675
**Solution:**
add default route check during installation
https://github.com/harvester/harvester/issues/5675
**Test plan:**
As steps in https://github.com/harvester/harvester-installer/pull/725

[backport 1.3] enhancement: check default route during installation (#725)

---

scripts/test

**Problem:**
https://github.com/harvester/harvester-installer/pull/708 moved pkg/config/templates/rancherd-22-addons.yaml to a separate "addons" repo, and added code to `scripts/build` to clone this repo during build and copy that yaml file to ./pkg/config/templates. So everything works fine if you run `make` or `make ci`.  However, if you just run `make test` by itself (which you might do during development), rancherd-22-addons.yaml isn't available, and the tests fail with:
```
Running tests
--- FAIL: TestConvertToCos_SSHKeysInYipNetworkStage (0.00s)
cos_test.go:71:
Error Trace:	/go/src/github.com/harvester/harvester-installer/pkg/config/cos_test.go:71
Error:      	Received unexpected error:
open templates/rancherd-22-addons.yaml: file does not exist
Test: …
```

build: checkout addons in scripts/test if necessary

---

pkg/console/constant.go
pkg/console/install_panels.go
pkg/console/network.go

**Problem:**
We need to provide the option of allowing system hostnames to be set via DHCP.
**Solution:**
When installing Harvester, if the management interface is configured via DHCP, we will default the system hostname to the client hostname specified by the DHCP server.
For interactive installation, the order of the "Configure hostname" and "Configure network" pages is swapped, so that "Configure network" comes first.  This allows us to set DHCLIENT_SET_HOSTNAME="yes" when applying the management NIC config.  If DHCP is used, and the DHCP server is configured to specify a hostname, the live environment will then automatically have its hostname set to whatever it got from the DHCP server.  Then, on the hostname page, we can default the hostname to that value, which the user is still …

Add ability to set hostname via DHCP during install

---

README.md
Vagrantfile

**Problem:**
This is necessary because the Leap 15.4 package repo, which is mentioned in the README to install `delve` for interactive debugging, is not available anymore.
**Solution:**
Change the package repos.
As the change only affects the development environment of harvester-installer, it has no effect on the installer itself.
n/a

Change package repos in Vagrantfile

---

README.md

**Problem:**
I didn't update the build status badge in README.md as part of https://github.com/harvester/harvester-installer/pull/697
**Solution:**
This PR
https://github.com/harvester/harvester/issues/5327
**Test plan:**
N/A

README.md: point build status badge at GHA workflow

---

pkg/config/templates/rancherd-22-addons.yaml
scripts/images/harvester-additional-images.txt

**Problem:**
Task: https://github.com/harvester/harvester/issues/5947
Image release:
https://github.com/harvester/eventrouter/releases/tag/v0.2.0
**Solution:**
Bump image tag to v0.2.0
**Test plan:**
New install, check eventrouter tag is v0.3.0
Upgrade, check eventrouter tag is v0.3.0
This is a manual backport of:
https://github.com/harvester/harvester-installer/pull/752
and
https://github.com/harvester/addons/pull/1 (only for harvester master-head)

[v1.3] Bump eventrouter to v0.2.0

---

package/harvester-os/Dockerfile
scripts/package-harvester-os

**Problem:**
There were some build issues when we bumped the sle-micro 5.5.
**Solution:**
Use the correct command to build iso successfully.
https://github.com/harvester/harvester/issues/6027
**Test plan:**
TBD

build: remove mkinitrd and fix docker create

---

package/harvester-os/files/usr/sbin/harv-install

Force remove files (rm -f), so the install script doesn't fail if the files don't exist.
**Problem:**
Sometimes the installer may hit a problem where it tries to remove a file that isn't there. If that happens, it shouldn't crash, but rather try to continue and recover.
```
time="2024-06-21T03:28:54Z" level=info msg="[stdout]: sending incremental file list"
time="2024-06-21T03:28:54Z" level=info msg="[stdout]: ./"
time="2024-06-21T03:28:54Z" level=info msg="[stdout]: harvester-images-v1.3.1.txt"
time="2024-06-21T03:28:54Z" level=info msg="[stdout]: harvester-repo-images-v1.3.1.txt"
time="2024-06-21T03:28:54Z" level=info msg="[stdout]: rancher-images-v2.8.3.txt"
time="2024-06-21T03:28:54Z" level=info msg="[stdout]: rke2-images-multus.linux-amd64-v1.27.13-rke2r1.txt" …
```

force remove files

---

package/harvester-os/files/usr/bin/setup-installer.sh

**Problem:**
Currently harvester installer does not initialise on arm instances on equinix metal.
The original arm implementation skipped the serial console /dev/ttyAMA0 in favour of non serial terminals exposed such as /dev/tty1 exposed on the ampere hosts.
Arm hosts in equinix metal only expose /dev/ttyAMA0 via serial-over-ssh. Since there is no alternate terminal exposed the installer does not start.
**Solution:**
The PR introduces a minor change to setup-installer script to favour non /dev/ttyAMA0 terminals if one is present such as on Ampere hosts, and failover to /dev/ttyAMA0 if that is the only option.
**Test plan:**

fix installer not initialising on arm hosts in equinix metal

---

Dockerfile.dapper
README.md
scripts/build
scripts/build-bundle
scripts/test

**Problem:**
It's currently annoying to build ISO images from the harvester-installer repo when you want to also include changes from a local harvester and/or addons repo. You have to manually edit `Dockerfile.dapper` and tweak `DAPPER_RUN_ARGS` to add something like `-v /path/to/local/harvester/repo:/go/src/github.com/harvester/harvester`.
**Solution:**
I've added `LOCAL_HARVESTER_SRC` and `LOCAL_ADDONS_SRC` environment variables to the build, which, if set, will automatically inject the correct `-v /path/to/local/harvester/repo` parameters, so now you can do this:
```sh
$ export LOCAL_HARVESTER_SRC=/path/to/local/harvester/repo
$ export LOCAL_ADDONS_SRC=/path/to/local/addons/repo
$ make
```
I've also done a little minor rewording and made the harvester repo cloning in …

build: Add LOCAL_{ADDONS,HARVESTER}_SRC arguments

---

Dockerfile.dapper
go.mod

**Problem:**
Need to bump golang to v1.22
**Solution:**
This PR
https://github.com/harvester/harvester/issues/6160
**Test plan:**
N/A

Bump golang to v1.22

---

pkg/console/install_panels.go

**Problem:**
Prior to this commit, errors returned from `validateConfig()`, `PrepareWebooks()` and `doInstall()`  would be printed to the console, but not logged.  This meant that if you weren't able to access the console for whatever reason, but _could_ access the log file, you would have no idea what went wrong if one of those function calls failed.
**Solution:**
Call `logrus.Error()` in addition to `printToPanel()`.
Bonus: call `logrus.Info("Installation will proceed (harvester.install.skipchecks = true)")` to make it explicit when preflight checks fail but are intentionally skipped.
https://github.com/harvester/harvester/issues/6214
**Test plan:**
- Do a PXE install, but with an invalid config file (see reproducer in …

Log validateConfig, PrepareWebooks and doInstall errors

---

scripts/build-bundle

**Problem:**
Addon & repo chart version mis-matching (e.g. https://github.com/harvester/harvester/issues/5840)
**Solution:**
Check version matching in the step of `build-bundle`
In amd64 architecture, the mismatching will cause build failure
In arm64 architecture, the mismatching will print some `WARNING` messages but build continue
https://github.com/harvester/harvester/issues/4937
https://github.com/harvester/harvester/issues/5840
**Test plan:**
make iso output:
**amd64**
```
...
charts packed in Harvester repo
total 1.3M
drwxr-xr-x 2 root root 4.0K Jun  3 18:35 .
-rw-r--r-- 1 root root  12K Jun  3 18:35 index.yaml
-rw-r--r-- 1 root root 2.5K Jun  3 18:35 nvidia-driver-runtime-0.1.1.tgz
-rw-r--r-- 1 root root 3.0K Jun  3 18:35 harvester-seeder-0.1.1.tgz
-rw-r--r-- 1 …
```

Add addon version check with the repo

---

scripts/build
scripts/build-bundle

**Problem:**
PR introduces minor changes to installer to leverage the new `generateTemplate` capability added to `harvester/addons`
Prior to this change the addon updates were being managed by updates to version_info file, and also updating the version details in the rancher-22-addons.yaml template file.
**Solution:**
This has been simplified to use the chart versions in version_info file and allow ability to generate template file dynamically. This ensures that chart and image version change is only ever kept in one single location.
addons PR: https://github.com/harvester/addons/pull/4
https://github.com/harvester/harvester/issues/4937
**Test plan:**

leverage generateTemplates capability of harvester/addons

---

scripts/build-bundle

**Problem:**
fix missing harvester addons in arm iso
**Solution:**
PR removes the logic to only package harvester addons in amd64 images. This is now possible as during the move to GH actions, we enabled multi-arch builds for all the default addons.
https://github.com/harvester/harvester/issues/6257
**Test plan:**

enable addons for arm builds

---

.github/workflows/build.yml

**Problem:**
ISOs are only published on pushes to the main harvester repo. Sometimes we need an ISO built when there's only been a change in harvester-installer, for example when doing testing of the head of one of the stable branches, or of master.
**Solution:**
Duplicate the relevant ISO publishing bits from https://github.com/harvester/harvester/blob/master/.github/workflows/build.yml
**Test plan:**

ci: Publish ISO images on branch push

---

scripts/package-harvester-os

**Problem:**
It's not always obvious exactly which version of the harvester-installer code is included in a given build.
**Solution:**
Add the harvester-installer commit hash to `/etc/harvester-release.yaml`. For release builds, this should give us something like the following:
```
os: Harvester v1.3 (ff64884)
```
For local dev builds, it's a bit redundant, but I don't think there's any harm in this:
```
os: Harvester 677447c-dirty (677447c)
```
https://github.com/harvester/harvester/issues/6285
**Test plan:**
Run `cat /etc/harvester-release` and make sure the `os` line includes the harvester-installer commit hash in parentheses.

build: add installer commit hash to /etc/harvester-release.yaml

---

pkg/console/install_panels.go

No need to check the default route if install binaries only.
**Problem:**
https://github.com/harvester/harvester/issues/6306
**Solution:**
Skip the default route check while install with method "Install Harvester binaries only".
https://github.com/harvester/harvester/issues/6306
**Test plan:**
1. Boot from ISO
2. Select "Install Harvester binaries only"
3. Make disk settings and set password
4. Confirm installation pass w/o problem

fix: Installation stopped by "No default route found"

---

pkg/config/templates/rancherd-22-addons.yaml

**Problem:**
last addons update for v1.3 branch is missing addon template updates.
As a result addon definitions are still using older chart versions which are no longer available in the current package.
**Solution:**
**Test plan:**

updated addon templates for v1.3

---

scripts/build-bundle
scripts/images/harvester-additional-images.txt

**Problem:**
https://github.com/harvester/harvester/issues/6289
**Solution:**
1. Update template generation
2. Check image tag
https://github.com/harvester/harvester/issues/6289
**Test plan:**
Peer PR: https://github.com/harvester/addons/pull/14 those 2 PRs can be merged independently.
These additional ENVs will be appended to the version_info file when building, no matter addon side PR https://github.com/harvester/addons/pull/14 is merged or not.
```
RANCHER_LOGGING_CHART_VERSION="103.1.0+up4.4.0"
RANCHER_MONITORING_CHART_VERSION="103.1.1+up45.31.1"
HARVESTER_EVENTROUTER_FULL_TAG="rancher/harvester-eventrouter:v0.3.1"
```
build output:
```
logging chart version is updated to 103.1.0+up4.4.0
monitoring chart version is updated to 103.1.1+up45.31.1
harvester-eventrouter …
```

Update monitoring and logging addon with template generation

---

.github/workflows/build.yml

**Problem:**
https://github.com/harvester/harvester-installer/actions/runs/10316766319 failed.
**Solution:**
This PR, I hope.
**Test plan:**

ci: Use correct dockerhub credential path

---

.github/workflows/build.yml

**Problem:**
ISOs are only published on pushes to the main harvester repo. Sometimes we need an ISO built when there's only been a change in harvester-installer, for example when doing testing of the head of one of the stable branches, or of master.
**Solution:**
Duplicate the relevant ISO publishing bits from https://github.com/harvester/harvester/blob/master/.github/workflows/build.yml
**Test plan:**

ci: Publish ISO images on branch push (v1.4)

---

.github/workflows/build.yml

**Problem:**
ISOs are only published on pushes to the main harvester repo. Sometimes we need an ISO built when there's only been a change in harvester-installer, for example when doing testing of the head of one of the stable branches, or of master.
**Solution:**
Duplicate the relevant ISO publishing bits from https://github.com/harvester/harvester/blob/master/.github/workflows/build.yml
**Test plan:**

ci: Publish ISO images on branch push (v1.3)

---

.github/workflows/build.yml

**Problem:**
ISOs are only published on pushes to the main harvester repo. Sometimes we need an ISO built when there's only been a change in harvester-installer, for example when doing testing of the head of one of the stable branches, or of master.
**Solution:**
Duplicate the relevant ISO publishing bits from https://github.com/harvester/harvester/blob/master/.github/workflows/build.yml
**Test plan:**

ci: Publish ISO images on branch push (v1.2)

---

.github/workflows/build.yml

**Problem:**
https://github.com/harvester/harvester-installer/actions/runs/10381016633 failed
**Solution:**
This PR
**Test plan:**
Merge this PR and make sure an the GHA completes successfully

ci: drop arm64 from manifest-cluster-repo-image

---

pkg/config/templates/rancherd-10-harvester.yaml

**Problem:**
The Harvester maintenance mode is blocked by manually attached volumes and single-replica volumes.
**Solution:**
Change LH default setting to allow node drain on such scenarios.
Refer:
https://github.com/longhorn/charts/blob/v1.6.x/charts/longhorn/values.yaml#L248
https://github.com/longhorn/charts/blob/ad73dc01239b7eeb25ff510ce8358578433d85a5/charts/longhorn/values.yaml#L250
https://github.com/harvester/harvester/issues/6264
https://github.com/harvester/harvester/issues/6266
**Test plan:**
Per issue steps.
After a new installation, get such LH default settings:
```
default-data-path                                                 /var/lib/harvester/defaultdisk                    true      7m19s
...
detach-manually-attached-volumes-when-cordoned …
```

Change LH default settings to fix maintenance mode issues

---

package/harvester-os/files/usr/share/rancher/rancherd/config.yaml.d/50-defaults.yaml
scripts/images/rancher-images.txt

**Problem:**
CVE
**Solution:**
Patch rancher initial shell image
https://github.com/harvester/harvester/issues/6283
**Test plan:**
1. A newly installed cluster:
cluster is ready
2. Expected values are correct
```
$ cat /usr/share/rancher/rancherd/config.yaml.d/50-defaults.yaml
rancherValues:
rancherImagePullPolicy: IfNotPresent
rancherImage: rancher/rancher
rancherImageTag: v2.8.5
noDefaultAdmin: false
features: multi-cluster-management=false,multi-cluster-management-agent=false
useBundledSystemChart: true
bootstrapPassword: admin
hostPort: 0
global:
cattle:
psp:
enabled: false
extraEnv:
- name: CATTLE_SHELL_IMAGE
value: "rancher/shell:v0.1.26"
rancherInstallerImage: rancher/system-agent-installer-rancher:v2.8.5
$ crictl image ls | grep shell
docker.io/rancher/shell …
```

Patch Rancher shell image to v0.1.26

---

scripts/images/rancher-images.txt

**Problem:**
v1.3-rc2 air-gapped ENV encountered such issue:
missing images:
```
rancher/mirrored-prometheus-alertmanager:v0.25.0
mirrored-prometheus-prometheus:v2.42.0
```
**Solution:**
PR https://github.com/harvester/harvester-installer/pull/793 happend to update following images, they are related to `rancher-monitoring` stack not `Rancher`.
```
docker.io/rancher/mirrored-prometheus-prometheus:v2.45.0
docker.io/rancher/mirrored-prometheus-alertmanager:v0.26.0
```
Revert them.
**Test plan:**
`Rancher-monitoring` addon can be enabled successfully on air-gapped env.

Fix rancher-monitoring missing images

---

pkg/config/config.go
pkg/config/config_test.go
pkg/config/cos.go
pkg/config/cos_test.go
pkg/config/templates/rke2-99-z00-harvester-reserved-resources.yaml

**Problem:**
This is a prerequisite pr for implementing CPU Pinning. We need to add the cpu manager configs first. `system-reserved`, `kube-reserved`, `cpu-manager-policy`.
**Solution:**
Introduced two configs files:
- `rke2-99-z00-harvester-reserved-resources.yaml`
-  include two configs`system-reserved` and `kube-reserved`, both of which follow [GKE CPU reservation formula](https://cloud.google.com/kubernetes-engine/docs/concepts/plan-node-sizes) for calculating reserved CPU resources.
- `rke2-99-z01-harvester-cpu-manager.yaml`
-  include cpu manager policy setting, currently the value is "none" (which is the default value)
> [!NOTE]  
> Here I add these files instead of adding configs in 90-harvester-server.yaml or 90-harvester-worker.yaml since we will have 99-max-pods.yaml (after …

Add CPU Manager related configs

---

scripts/package-harvester-os

Skip the hardware check otherwise the installation will be stuck because the build VM doesn't meet the minimum hardware requirement.

fix: fail to build raw images

---

scripts/lib/image

**Problem:**
https://github.com/harvester/harvester/issues/6489
**Solution:**
Allow specify a tag (e.g. for all 3 Harvester related images) via the ENV USE_LOCAL_IMAGES to skip the qualified images directly.
https://github.com/harvester/harvester/issues/6489
**Test plan:**

Extend the usage of build ENV USE_LOCAL_IMAGES

---

.github/mergify.yml

Use Mergify to automatically create backport PRs according to `backport-to/<branch>` labels.

chore: Configure Mergify to open backport PRs by labels [skip ci]

---

scripts/build-bundle

**Problem:**
Bump eventrouter image base from bci 15.5 to 15.6
**Solution:**
Bump eventrouter image base from bci 15.5 to 15.6
https://github.com/harvester/harvester/issues/6568
container image bump: https://github.com/harvester/eventrouter/pull/12
**Test plan:**
1. Install new cluster
2. Enable rancher-logging addon
3. check eventrouter pod is normally running with tag v0.3.2
4.  it's pod log (`kubectl logs -n cattle-logging-system harvester-default-event-tailer-0`) has things like
>{"verb":"ADDED","event":{"metadata":{"name":"pvc-99b647d2-d7d0-46d1-998a-13a3cf3a8f02.17f64d4708a92b3c","namespace":"longhorn-system","uid":"9cc92ef2-77ac-48ac-af74-c5e576664456","resourceVersion":"287702","creationTimestamp":"2024-09-18T09:41:14Z","managedFields":[{"manager":"longhorn-manag …

Bump eventrouter to v0.3.2 with bci 15.6

---

package/harvester-repo/Dockerfile

https://github.com/harvester/harvester/issues/6568

chore: bump bci image to 15.6

---

pkg/config/templates/rancherd-22-addons.yaml

**Problem:**
BCI 15.5 is EOL in the end of the year, related images need to be bumped to BCI 15.6.
**Solution:**
This is a munual backport to v1.3 of PR https://github.com/harvester/harvester-installer/pull/839.
The addon source code and image version organizations are changed on v1.4.
https://github.com/harvester/harvester/issues/6568
**Test plan:**
per https://github.com/harvester/harvester-installer/pull/839

[v1.3]Bump eventrouter to v0.3.2 with BCI 15.6

---

package/harvester-repo/Dockerfile

**Problem:**
This is an enhancement, use nginx instead of root user in harvester-cluster-repo image.
**Solution:**
Use nginx user in harvester-cluster-repo
**Test plan:**
1. `make ci` to build iso, and prepare a single node harvester cluster (easy for testing)
2. Enable addon (e.g. `pcidevices-controller`) and the addon could be successfully installed.

Use nginx user in harvester-cluster-repo image

---

pkg/config/templates/cos-rootfs.yaml

**Problem:**
Currently /lib is mounted directly from the image file, and is readonly filesystem.
For certain driver packages, such as nvidia, a firmware file is needed which needs to be written to /lib/firmware for the driver and GPU to perform correctly. This currently fails, and attempts to leverage https://www.kernel.org/doc/html/v4.18/driver-api/firmware/fw_search_path.html does not seem to result in the correct behaviour.
The PR makes `/lib/firmware` to be remounted as an overlay fs, allowing temporary changes to be stored for drivers to function correctly.
**Solution:**
https://github.com/harvester/harvester/issues/6487
**Test plan:**

add /lib/firmware to list of RW filesystems

---

pkg/console/dashboard_panels.go

**Problem:**
In Fleet v0.10.2, it changes to set Ready condition. However, we checked Processed condition.
https://github.com/rancher/fleet/blob/decbf9ae72eff096b2bee5efe05a92fdcbd5627d/internal/cmd/controller/reconciler/bundle_controller.go#L250
**Solution:**
Change command to check Ready condition.
https://github.com/harvester/harvester/issues/6690
**Test plan:**
1. Create a Harvester cluster.
2. When Harvester is ready, check dashboard show "Ready".

fix(dashboard_panels): change to check ready condition in managedchart

---

pkg/config/templates/rancherd-10-harvester.yaml

**Problem:**
We need harvester-networkfs-manager pod enabled by default.
**Solution:**
Add corresponding config on harvester managedchart
**Test plan:**
make sure the harvester-networkfs-manager is running by default

templates: add harvester-networkfs-manager

---

pkg/console/util.go
pkg/console/util_test.go

**Problem:**
Logic disks managed by the raid controller will have the same serial number. This results in disks being deduplicated and ignored.
**Solution:**
From the sample data available the wwn is unique despite the serial number being the same. 
The PR adds a minor tweak to continue comparing disks even if serial number is same and check for wwn uniqueness.
https://github.com/harvester/harvester/issues/6694
**Test plan:**

fine tune logic to filter disks

---

package/harvester-os/files/system/oem/90_network.yaml

**Problem:**
PR changes the order of nic startup to avoid nic renaming conflicts
**Solution:**
**Test plan:**

change order of interface startup

---

pkg/console/console.go
pkg/console/install_panels.go

**Problem:**
DHCP looks to have flaws with VLAN interfaces.
**Solution:**
Sure the DHCP is working on VLAN interface if VLAN is configured.
This PR has 3 commits:
```
(1) Use VLAN interface if VLAN is configured to do DHCP
(2) Avoid preflight check if node goes to dashboard directly
(3) Pass VID
```
PR https://github.com/harvester/harvester-installer/pull/878 is merged to this one.
Co-authored-by: Kiefer Chang <kiefer.chang@suse.com>
https://github.com/harvester/harvester/issues/6959
https://github.com/harvester/harvester/issues/3428
**Test plan:**
Per issue description
**Local test:**
Installer with this fix, the DHCP discovery frame is encaped with VLAN 100 ( and we did not set a DHCP server on VLAN 100)
Original installer without this fix, the DHCP discovery frame is …

Sure DHCP will work on VLAN interface if VLAN is configured

---

package/harvester-os/files/usr/sbin/harv-install
pkg/console/util.go

**Problem:**
When downloading ISO, the progress bar doesn't show well. The reason is that curl uses `\r` to overwrite and print the progress bar. And the console.log in `/oem/install` is not aligned.
**Solution:**
We should consider the `\r` character as well when scanning. And add a tag to switch different printers to print the messages.
https://github.com/harvester/harvester/issues/5990
**Test plan:**
Install it with PXE, and check progress bar should display correctly.
https://github.com/user-attachments/assets/a278cd26-d7fc-4f45-beb3-362013a74314
Console log in `/oem/install/console.log`
After
Same as Version 1, but I use `"Total   Spent    Left  Speed"` as flag to trigger different printers. Then, we don't have duplicated header in `/oem/install/console.log`. But …

feat: make curl progress bar correctly shows on the gui

---

package/harvester-os/files/etc/systemd/system/rke2-agent.service.d/override.conf
package/harvester-os/files/etc/systemd/system/rke2-server.service.d/override.conf

The bridge-nf-call-iptables should be disabled by network-controller. But rke2 will toggle it back to enable. Need to make sure it stays at disabled.
**Problem:**
https://github.com/harvester/harvester/issues/7041
**Solution:**
persist the bridge-nf-call-iptables across rke2 restart
https://github.com/harvester/harvester/issues/3960
**Test plan:**

Persist the bridge-nf-call-iptables across rke2 restart

---

pkg/console/constant.go
pkg/console/install_panels.go
pkg/console/vip.go

**Problem:**
There is a parity gap between the VIP configuration of the ISO installation and the automatic installation modes. In the automatic installation mode, user can specify the VIP MAC and static IP addresses over DHCP. This allows user to use a static IP address as the cluster's VIP. This option isn't available in the ISO installation mode.
**Solution:**
This PR updates the VIP configuration page of the installation console with a new `MAC Address` field, to allow user to specify the VIP's MAC address in DHCP mode. The installer uses this MAC address to request for the specific static IP address over DHCP. If this field is left blank, the installer falls back to the current behaviour of determining the VIP and MAC address.
On the VIP page, the subsequent input panels that will be …

feat: add VIP mac address input panel

---

pkg/config/templates/rancherd-12-monitoring-dashboard.yaml

**Problem:**
Prometheus VM Metrics are not accurate whatsoever where cpu usage metrics at a percentage level are exceeding 200000% within the Harvester UI VM metrics.
**Solution:**
fix incorrect cpu usage unit, upgrade path fix is here: https://github.com/harvester/harvester/pull/7250
https://github.com/harvester/harvester/issues/7086
**Test plan:**
- Prepare a harvester cluster with this patch
- Enable rancher-monitoring addon
- Prepare some VMs (e.g. 3 VM)
- Goto Grafana UI and wait for a couple of minutes
- Check the value of cpu usage should fall in range [0, 100] in both `Harvester VM Dashboard` and `Harvester VM Info Detail` dashboards (during vm startup, the cpu usage may slightly go over 100%, after a while it should dramatically drop to a low value, like 2%) …

Fix incorrect unit in cpu usage dashboard

---

Dockerfile.dapper
README.md
go.mod
pkg/config/config.go
pkg/console/console.go
pkg/console/spinner.go
pkg/console/util.go
pkg/util/common.go

**Problem:**
Need to bump golang to v1.23. While doing that I found a couple of other little things to clean up which I have also included in this PR as separate commits.
**Solution:**
This PR
https://github.com/harvester/harvester/issues/7336
**Test plan:**
N/A

Bump golang to v1.23 plus some additional cleanup

---

scripts/build
scripts/build-bundle
scripts/test

Update harvester and addons to use v1.5 repos for the v1.5 stable branch.

chore: update to v1.5 branch for harvester and addons repos

---

pkg/util/cmdline.go
pkg/util/cmdline_test.go

Fix parsing management interface configuration from the kernel command line.
The parser now accepts more different specifications for the management interface, including just the systemd name for the device. Additionally, should the configuration not be parseable (e.g. due to a typo), the installer doesn't crash anymore, but rather produces a human readable error.
related-to: harvester/harvester#7470
**Problem:**
**Solution:**
**Test plan:**

fix kernel command line for management interface

---

pkg/config/templates/rancherd-10-harvester.yaml
pkg/config/templates/rancherd-11-monitoring-crd.yaml
pkg/config/templates/rancherd-14-logging-crd.yaml

**Problem:**
**Solution:**
https://github.com/harvester/harvester/issues/7375
**Test plan:**

feat: add timeoutSeconds to ManagedChart

---

pkg/util/cmdline.go
pkg/util/cmdline_test.go

This is a backport of [PR #942](https://github.com/harvester/harvester-installer/pull/942) to v1.5 branch.
Fix parsing management interface configuration from the kernel command line.
The parser now accepts more different specifications for the management interface, including just the systemd name for the device. Additionally, should the configuration not be parseable (e.g. due to a typo), the installer doesn't crash anymore, but rather produces a human readable error.
related-to: https://github.com/harvester/harvester/issues/7470

[Backport v1.5] fix kernel command line for management interface

---

package/harvester-os/files/usr/sbin/harv-install
pkg/config/config.go
pkg/console/constant.go
pkg/console/install_panels.go
pkg/console/util.go
pkg/console/util_test.go
pkg/widgets/dropdown.go

**Problem:**
We introduced a field in Harvester config named `wipeDisks` which when set ran a script in the installer to iterate over all disk devices visible to the host and wipe them.
This ended up being too aggressive, not to mention not all disks may contain old Harvester installations.
**Solution:**
PR introduces two new fields in the harvester config wipeDisksList and wipeAllDisks and drops the old wipeDisks introduced in v1.3
There is an extra panel in disk configuration page. The extra panel contains a drop down menu which gets rendered and populated if installer finds additional disks with existing elemental based installations which are not already used in install device or additional data device.
The extra `Wipe Disks` panels will only be available when there are additional …

Wipe Disks Improvements

---

package/harvester-os/files/system/oem/99_cni_reset.yaml

**Problem:**
Under certain scenarios when a harvester node is hard rebooted the canal cni can leak ip addresses 
https://docs.rke2.io/known_issues#canal-and-ip-exhaustion
Over time these may build up and result in ip address pool exhaustion for a node since.
The only option in such a scenario is to clean up un-used ip leases from `/var/lib/cni/networks/k8s-pod-network`
**Solution:**
PR introduces a minor change to add directives for cni reset in base image. 
This ensures they are rolled out to existing systems as part of the upgrade cycle
https://github.com/harvester/harvester/issues/7471
**Test plan:**
* Install harvester from current changes to a node
* Once harvester is running hard reboot the node
* Once harvester is up and running check the timestamp on the folder …

clean up calico dhcp state on reboots

---

package/harvester-os/files/usr/sbin/harv-install

**Problem:**
If `passive.img` is not a sparse file, it can result in too much disk space being used on the COS_STATE partition which causes problems for upgrades (see related issues).
**Solution:**
After installation, run `fallocate --dig-holes` to make `passive.img` sparse if it's not already.
https://github.com/harvester/harvester/issues/7457
https://github.com/harvester/harvester/issues/7518
**Test plan:**
- Install Harvester
- Post-install, check disk usage of active.img and passive.img. They should be the same (about 1.7G):
```
1.7G	/run/initramfs/cos-state/cOS/active.img
1.7G	/run/initramfs/cos-state/cOS/passive.img
```
- The fact that passive.img shrunk from 3.1G to 1.7G should be recorded in the install log, e.g.:
```
time="2025-02-11T11:59:38Z" level=info …
```

fix: ensure passive.img is sparse after install

---

pkg/config/cos.go
pkg/console/util.go

**Problem:**
When Harvester is installed with a single disk shared between OS and data, we set the COS_STATE parittion size to 15G. When using a separate data disk, we just use the Elemental default partition layout, which only gives COS_STATE of 8G. This causes problems with upgrades due to lack of space.
**Solution:**
This commit ensures we set a 15G COS_STATE parition in both of the above cases.
- https://github.com/harvester/harvester/issues/7457
- https://github.com/harvester/harvester/issues/7493
**Test plan:**
- Install Harvester with a shared OS/data disk. Check the COS_OEM, COS_RECOVERY and COS_STATE partition sizes:
```
NAME    LABEL             SIZE
[...]
vda                       500G
├─vda1                      1M
├─vda2  COS_OEM            50M          <-- …
```

fix: use same COS_* partition sizes regardless of seaparate data disk

---

package/harvester-os/files/usr/share/rancher/rancherd/config.yaml.d/50-defaults.yaml

**Problem:**
Rancher added new setting `agent-tls-mode` which breaks custom CA feature.
**Solution:**
Set the setting to `system-store` to fix the error.
https://github.com/harvester/harvester/issues/7453
**Test plan:**
1. Build with harvester-installer to create an ISO.
2. Start first node.
3. Check whether value of `agent-tls-mode` setting is `system-store`.
4. Setup `ssl-certificates` setting.
5. Create second node to join first node without error.

feat: add agentTLSMode to rancherValues

---

pkg/config/cos.go
pkg/console/util.go

**Problem:**
Currently when externalDisk support is not enabled, the installer adds a default kernel argument `multipath=off` via `third_party_kernel_arguments`.
This works fine, however it breaks CSI's needing multipath since it cannot be enabled due to the kernel argument.
Disabling `multipath=off` from `third_party_kernel_args` breaks the boot, when OS has been installed to nvme, as multipath attempts to create multiple paths for nvme disks.
**Solution:**
To fix this a minor change has been made to default kernel argument being passed when multipath is not needed. This allows dracut to still boot with nvme disks as it ignores multipath module packaged in dracut, while allowing multipathd to be enable subsequently
In addition a default multipath config is added to ignore longhorn based …

change multipath default behaviour

---

pkg/console/install_panels.go

**Problem:**
#725 introduces a bug wherein if an automated deployment (after a binaries-only installation) using user-data is initiated and does not use DHCP, the installation fails with the error "No default route found. Please check the router setting on the DHCP server" regardless of the "Gateway" settings.  This is because the check is performed before a static network is set up.
**Solution:**
Add a couple of "if" checks to determine if this is a DHCP installation.  If not, skip the default route check.
#725 #734 
**Test plan:**
Using this user-data file on an attached CDROM or USB stick, successfully perform an automated install:
```
#cloud-config
token: token
os:
ssh_authorized_keys:
- ssh-rsa ...        # replace with your public key
password: p@ssword   # …
```

Fix Default Route check when not using DHCP

---

pkg/config/templates/cos-rootfs.yaml

**Problem:**
Our OS image includes `/etc/machine-id`, `/etc/iscsi/initiatorname.iscsi`, `/etc/nvme/hostid` and `/etc/nvme/hostnqn`. This means that those files will be identical on every single Harvester node installed from a given ISO image. This is wrong.
`/etc/machine-id` is meant to be unique per host, see e.g.:
https://manpages.opensuse.org/Tumbleweed/systemd/machine-id.5.en.html
Likewise, the iSCSI initiator name and NVMe hostid/hostnqn need to be unique when accessing external storage via iSCSI or NVMe over fabrics.
**Solution:**
https://github.com/harvester/os2/pull/190 ensures that those files are _not_ included in our OS image, and will be instead generated on first boot. This harvester-installer PR is also required to ensure `/etc/nvme` persists correctly. …

fix: persist /etc/nvme

---

pkg/config/cos.go
pkg/console/util.go

change default kernel argument to disable multipath and overwrite multipathd system unit definition to allow multipathd to still be run after boot
**Problem:**
PR https://github.com/harvester/harvester-installer/pull/938 changed kernel arguments to disable multipathd during boot. The original idea was to allow end users to still enable multipathd post boot for 3rd party CSI.
However the change seems to have broken boot in kvm when using ide, scsi and sata buses. The same issue has also been noticed on HP DL360's when using a raid controller.
**Solution:**
* revert default argument to disable multipathd back to `multipath=off`
* override `multipathd.service` file via `/etc/systemd/system`, where we drop the condition check for `multipath=off` …

change default setup for multipathd

---

pkg/console/install_panels.go

Problem:
https://github.com/harvester/harvester-installer/pull/725 introduces a bug wherein if an automated deployment (after a binaries-only installation) using user-data is initiated and does not use DHCP, the installation fails with the error "No default route found. Please check the router setting on the DHCP server" regardless of the "Gateway" settings. This is because the check is performed before a static network is set up.
Solution:
Add a couple of "if" checks to determine if this is a DHCP installation. If not, skip the default route check.
Related Issue:
https://github.com/harvester/harvester-installer/pull/725 https://github.com/harvester/harvester-installer/pull/734
Test plan:
Using this user-data file on an attached CDROM or USB stick, successfully perform an automated …

Fix Default Route check when not using DHCP (backport #876)

---

pkg/config/cos.go
pkg/console/util.go

**Problem:**
PR contains cherry-picked commits related to 
https://github.com/harvester/harvester-installer/pull/938
https://github.com/harvester/harvester-installer/pull/988
The first PR changed default multipathing behaviour to `rd.multipath=0` and disabled multipath for longhorn devices.
This seemed to have cause issues with booting on certain devices.
The second behaviour revert to `multipath=off` and changed the multipath systemd unit to start even if `multipath=off` is added to kernel arguments
**Solution:**
https://github.com/harvester/harvester/issues/7622
https://github.com/harvester/harvester/issues/7438
**Test plan:**

Backport v1.5 change multipath behaviour

---

pkg/console/network.go

The PR improves nic filtering when iscsi sessions are detected.
With this change, in case a vlan interface is used for an iscsi session, then the parent interface is filtered from the list of interfaces and is no longer visible in the list of interfaces
If there is no iscsi session then the behaviour of the installer remains unchanged.
**Problem:**
v1.4.0 introduced support for external iscsi disks to be used as install disks. Changes were made in the installer to skip interfaces which were being used for the iscsi session. In environments where vlans are in use for accessing the iscsi disks, then dracut sets up a vlan interface which is subsequently used for iscsi login and subsequent sessions.
Our current logic did not pick this up and the parent interface being used for the vlan …

improve interface filtering when iscsi session is detected

---

package/harvester-os/files/usr/sbin/harv-dummy-iface

**Problem:**
When installing Harvester with the install-binary-only mode, and the artifacts (including the ISO image, kernel, initrd, and rootfs) are provided through network, the installation fails in an early stage with an error message `exit status 2` on the installer dashboard.
**Solution:**
Adding a dummy default route to an already well-configured node causes the issue. A default route cannot be added if one already exists. Adding a simple default route checker to fix the issue.
harvester/harvester#7732
**Test plan:**
1. Build a Harvester ISO image with this PR included (for QAs, please use the master-head image after the PR is merged)
2. Set up a suitable environment (courtesy to @irishgordo for below steps, with some adaptation)
- For devs, please put the built …

fix: skip adding dummy route if a default one exists

---

scripts/build-bundle
scripts/hack/patch-harvester-chart

**Problem:**
pr rolls back the changes dropped in backport PR https://github.com/harvester/harvester-installer/pull/965 as these are still needed for v1.4.x. This rollback is needed to ensure we can keep using upstream kubevirt v1.3 images for harvester v1.4.x. In addition to the rollback, the PR also updates patch-harvester-chart to use kubevirt v1.3.1 images and tweak replacement logic to match harvester v1.4.2 chart requirements
**Solution:**
https://github.com/harvester/harvester/issues/7735
**Test plan:**
* Install harvester v1.4-head to an arm node
* post install verify virt-operator is using upstream kubevirt v1.3.1 images
* basic tests like vm creation should be successful

re-add harvester chart patching for harvester v1.4.x builds

---

pkg/config/cos.go
pkg/config/templates/rke2-91-harvester-cdi.yaml

**Problem:**
We encounter the permission issue when using Longhorn v2 volume with CDI
**Solution:**
Set `device_ownership_from_security_context` to true for better permission handling.
https://github.com/harvester/harvester/issues/1199
**Test plan:**
Please see the test plan on https://github.com/harvester/harvester/pull/7640

config: add rke2 config to improve the device permission

---

pkg/util/cmdline.go
pkg/util/cmdline_test.go

This is a backport of [PR #942](https://github.com/harvester/harvester-installer/pull/942) to v1.4 branch.
Fix parsing management interface configuration from the kernel command line.
The parser now accepts more different specifications for the management interface, including just the systemd name for the device. Additionally, should the configuration not be parseable (e.g. due to a typo), the installer doesn't crash anymore, but rather produces a human readable error.
related-to: https://github.com/harvester/harvester/issues/7470

[Backport v1.4] fix kernel command line for management interface

---

pkg/config/cos.go
pkg/config/templates/rancherd-config.yaml

**Problem:**
Follow up https://github.com/harvester/harvester-installer/pull/931. 
I found out that hostname was overwritten at some points. We've set up the hostname in live stage when installing. 
https://github.com/harvester/harvester-installer/blob/dd139f8bc7a12590edd84e64a4aada03e98487c1/pkg/console/network.go#L72-L80
> In contrast to similar projects such as Cloud Init, Yip does not keep records or caches of executed stages and steps, all stages and its associated configuration is executed at every boot.
> Reference: https://elemental.docs.rancher.com/cloud-config-reference/
It won't take any effect if the file isn't saved.  From the source codes, we can tell this live stage file is saved in `/tmp` during installation instead of `/oem` and `/system/oem` folder.
**Solution:**
When …

fix: pass hostname to rancherd and elemental config in network stage

---

scripts/version-rke2

Bump RKE2 to v1.31.7+rke2r1
https://github.com/harvester/harvester/issues/7948
**Test plan:**
* Create an airgapped 3-node cluster without error.
* Upgrade from v1.4.2 without error.

feat: bump RKE2 to v1.31.7+rke2r1

---

pkg/config/cos.go
pkg/config/templates/wicked-setup-bond.sh
pkg/config/templates/wicked-setup-bridge.sh

**Problem:**
During Harvester installation, the system attempts to add all VLAN IDs to the management bond/bridge. With Mellanox ConnectX-6 NICs (which support 512 hardware-offloaded VLANs and have hardware VLAN offloading enabled by default), this causes boot log warnings and prevents management VLAN 2301 from being added to the hardware offloaded VLAN list.
**Solution:**
Add only configured vlans to the mgmt-br and mgmt-bo
https://github.com/harvester/harvester/issues/7650
**Test plan:**
1.Select vlan id during harvester-installation
2.configure and proceed with installation
3.Once installed, verify "bridge vlan show"
mgmt-br and mgmt-bo should list the below for example
bridge vlan show
port vlan-id
mgmt-br 1 PVID Egress Untagged
2021
mgmt-bo 1 PVID Egress Untagged …

Add only vlan specified by user to mgmt-br and mgmt-bo during installation

---

package/harvester-os/files/system/oem/99_cni_reset.yaml

`/var/lib/cni/networks/k8s-pod-network/` is not fully cleandup when node/cluster reboots.
Fix stage file definition.
https://github.com/harvester/harvester/issues/8150
1. Restart node/cluser
2. Check node/nodes, the `/var/lib/cni/networks/k8s-pod-network` path is not existing or only has files with timestamp after node/cluster rebooting.
It is validated on both v1.5.0 and v1.4.2 cluster.

Fix cni pod network cache reset

---

pkg/config/cos.go
pkg/console/install_panels.go

Problem:
The default bond mode set during harvester installation using seeder or ipxe is balance-tlb
Expected Behavior:
The recommended or default bond mode is Active backup
Solution:
Set the default mode to Active backup in harvester-installer when no bond options are specified by user.
Note:This is not applicable to harvester installed in manual mode as install panel defaults to "Active-Backup" and the value cannot be empty
This is related to https://github.com/harvester/harvester/issues/8042

Set default mode to Active-Backup for bond

---

scripts/images/rancher-images.txt

3 images are missing by default and air-gapped upgrade is affected adding them will ensure v1.4.3 to v1.5.* upgrade is smooth
upgradeLog refers to some none-pre-existing images due the the bump of Rancher version, the air-gapped cluster is affected; and the fix on v1.5.0 is too big to backport
add the missing images on v1.4.3, to ensure v1.4.3 to v1.5.* upgrade is not blocked by the missing images on air-gapped env.
https://github.com/harvester/harvester/issues/8052
v1.4.2 has listed this as a known issue https://github.com/harvester/docs/pull/759
1. Install v1.4.3 cluster, single-node cluster is ok
2. Setup an air-gapped env or check the container images via `crictl image ls`, following images are on each node:
```
ghcr.io/kube-logging/fluentd:v1.15-ruby3 …
```

Add the missing images for upgradeLog

---

pkg/console/install_panels.go
pkg/console/util.go

Issue documented in https://github.com/harvester/harvester/issues/8201
At the conclusion of the configuration phase of installation, the user is prompted to continue the installation with a Yes/No prompt. If "No" is selected, the machine is automatically rebooted without giving the user a chance to change the configuration settings. This should be clarified so users do not incorrectly select No thinking they can change the configuration.
If the installation fails, the user is told to login as rancher/rancher and to view the console log. However, the rancher user must use sudo in order to view the log file.
- Change the "No" option at the end of the configuration phase to "No (Reboot)".
- Add sudo to the command to view the log file.
N/A

Enhancement: Small tweaks to clarify install prompts

---

Vagrantfile

Install missing open-iscsi package
Related to: https://github.com/harvester/harvester/issues/8258

[BUG] Harvester-installer can not be run in Vagrant box because of missing iscsiadm executable

---

pkg/config/config.go
pkg/config/templates/rke2-90-harvester-server.yaml

**Solution:**
Allow users to add other endpoints to `tls-san`.
https://github.com/harvester/harvester/issues/7716
**Test plan:**
1. Clone https://github.com/harvester/ipxe-examples.
2. Modify `ansible/roles/harvester/templates/config-create.yaml.j2` to add `sans` like
```yaml
sans:
- example.com
```
3. Create a harvester cluster with ISO from this branch.
4. After first node is ready, check there is `example.com` and VIP in the certificate.
```
> openssl x509 -in /var/lib/rancher/rke2/server/tls/serving-kube-apiserver.crt -text -noout
Certificate:
Data:
Version: 3 (0x2)
Serial Number: 927360019122894648 (0xcdea50626b83738)
Signature Algorithm: ecdsa-with-SHA256
Issuer: CN = rke2-server-ca@1740650146
Validity
Not Before: Feb 27 09:55:46 2025 GMT
Not After : Feb 27 …
```

feat: add sans to HarvesterConfig

---

scripts/patch-monitoring-logging

The harvester-eventrouter image still remains at v1.5.0-dev.0.
Manually bump it to v1.5.1-rc4.
harvester/harvester#8503
This PR supersedes #1053 for v1.5.1 releases for schedule urgency. In the long run, we'll have a unified way to manage the harvester-eventrouter's version, like what we proposed in #1053.

chore: bump harvester-eventrouter to v1.5.1-rc4

---

pkg/config/templates/patch/rancher-monitoring/105.1.2+up61.3.2/nginx-config.yaml

Rancher names the imported cluster from `c-m-*` to `c-*`
After bumping Rancher to v2.11.2, the Rancher->Harvester can't load grafana
Update the grafana nginx proxy setting to filter the imported cluster name.
https://github.com/harvester/harvester/issues/8498
Upgrade path processing will be added to `harvester` repo from another PR.

Update grafana nginx proxy to sync with Rancher

---

.github/mergify.yml

- Also remove the EoL v1.3 capability
We need that capability because we will have the v1.6 branch for the upcoming release.
Add those capability for mergify configuration

chore: add new pr-backport capability for v1.6

---

pkg/config/templates/wicked-setup-bond.sh
pkg/config/templates/wicked-setup-bridge.sh

Problem:
Adding vid 1 to bridge vlan will add vid=1 as tagged vlan to mgmt interface.
This will replace the default PVID=1 behaviour on mgmt interface.
When user does not configure any vlan id or configured vlan id as 1,skip configuring vid=0 or vid=1 on wicked scripts, so that the default PVID=1 is retained on the mgmt interface.
https://github.com/harvester/harvester/issues/8515
1.Install Harvester manually without any vlan id or vlan id=1
2.Check if harvester nodes are setup correctly and ready.

Skip bridge vlan add when vid less than 2

---

README.md

* adjusting the README to call out the deep Docker dependency
Resolves: doc/adj-readme
We don't address a deep dependency to Docker.
Other tools like `nerdctl` aren't compliant enough to work with Harvester.
Call out in the README the prerequisite.
N/A
N/A
N/A

doc: Adjust README

---

pkg/config/config_test.go
pkg/config/testdata/rancherd-22-fake-addons.yaml
pkg/config/testdata/rancherd-22-good-addons.yaml
pkg/config/testdata/rancherd-22-not-templated-addons.yaml
scripts/test

The addon repo fetching and processing are unified now, update the test related part.
1. Unify `make test`
2. Add test code upon addon tempate file, if some fields are note well templated, report error
https://github.com/harvester/harvester/issues/6289
Both `make` and `make test` can run smoothly
To avoid future backport conflicts, this PR is still backported to v1.6, but need to update the add on repo branch in `script/test`

Add test upon addon templated files

---

pkg/config/templates/rancherd-10-harvester.yaml

Since https://github.com/longhorn/longhorn/commit/d41740d1, longhorn's defaultValues must be strings.
Quote the numeric values.
https://github.com/harvester/harvester/issues/9223
Deploy harvester, make sure there are no errors as in the description of the related issue

fix: stringify longhorn numeric defaultValues

---

.github/workflows/build.yml

My last commit on this only published the harvester-installer container image on branches, not on tags, but the latter is necessary to get correctly versioned images for releases.
Add publishing on tags
https://github.com/harvester/harvester/issues/3418
Wait 'til the next sprint release and see if we get a correctly tagged harvester-installer container image in https://hub.docker.com/r/rancher/harvester-installer/tags. Actually, probably better to manually tag an interim dev version (e.g. v1.7.0-dev-20250930) release to verify sooner :-)

fix: publish harvester-installer container image on tag

---

.github/workflows/build.yml

https://github.com/harvester/harvester-installer/pull/1155 was missing the push tag trigger
Add the push tag trigger
https://github.com/harvester/harvester/issues/3418
Same as https://github.com/harvester/harvester-installer/pull/1155

fix: really publish harvester-installer container image on tag
