pkg/console/util.go, scripts/image-list.txt
=> update chart values and add network image

pkg/console/util.go
https://github.com/rancher/harvester/issues/251
=> Add service lb labe for management node

go.mod, pkg/console/util.go, vendor/k8s.io/apimachinery/pkg/util/rand/BUILD, vendor/k8s.io/apimachinery/pkg/util/rand/rand.go, vendor/modules.txt
change generated hostname from k3os to harvester
=> Use generated harvester hostname

pkg/console/constant.go, pkg/console/dashboard_panels.go, pkg/console/install_panels.go, pkg/console/util.go
https://github.com/rancher/harvester/issues/259
=> Remove node role option

pkg/config/config.go, pkg/console/constant.go, pkg/console/install_panels.go, pkg/console/util.go, pkg/console/util_test.go
https://github.com/rancher/harvester/issues/284
Problem:
Cert validation fails when ssh key URL is added because the server time on the init phase is out of date.
Solution:
Do ssh key import in the runtime phase.
=> Import sshkeys in runtime phase

Dockerfile.dapper, k3os/images/10-gobuild/gobuild, k3os/images/20-progs/Dockerfile, k3os/scripts/images, scripts/build
https://github.com/rancher/harvester/issues/315
1. Pass harvester version to the k3os build flags.
2. Prepare offline images based on dependencies versions on the harvester side.
=> Fix inconsistent versions

scripts/build
https://github.com/rancher/harvester/issues/331
=> Add virtio container disk image

scripts/build
Looks like a typo.
Fix https://github.com/rancher/harvester-installer/issues/27.
=> Fix image repository and tag validation

pkg/config/config.go
=> Fix format

scripts/build
Fix CI failure: https://drone-publish.rancher.io/rancher/harvester-installer/30/1/2
The yq version installed by https://github.com/rancher/harvester-installer/blob/master/Dockerfile.dapper#L7 has changed
=> update yq syntax from v3 to v4

k3os/images/00-base/Dockerfile, k3os/overlay/sbin/k3s-restarter
1. add `yq`
2. (harvester) after promote node to master, use `yq` to add `--disable local-storage` into k3sArgs
3. use `rc-service ccapply restart ` to generate /etc/init.d/k3s-service and restart k3s
https://github.com/rancher/harvester/issues/455
https://github.com/rancher/harvester/issues/259
=> Use yq to promote node

pkg/console/install_panels.go, pkg/util/os.go
=> Fix installation halted reboot

pkg/console/dashboard_panels.go
1.  rancher/harvester#462 
After restart node, pods of `helm-install-harvester` will be deleted, the current status will alway  `Setting up Harvester`,
Use `get job` instead of `get po` and only the first node check if `Setting up  Harvester`.
2.  rancher/harvester#458
If  harvester pod has multiple replicas, the current status will show `Runing Runing`,
`sort -u`
3. if harvester pod's status phase is empty, show nothing instead of `Unknown`
=> Fix current status

pkg/console/install_panels.go, pkg/console/util.go
Checking for server URL availability can ensure invalid IP is discovered at an earlier stage instead of allowing for installation.
Relate to https://github.com/rancher/harvester/issues/472
=> Validate server URL when joining existing cluster

pkg/console/dashboard_panels.go, pkg/console/util.go
Change Service type to NodePort and use 30443
rancher/harvester#459
**Related PR:**
rancher/harvester#468
=> Change Service type to NodePort

pkg/console/install_panels.go
https://github.com/rancher/harvester/issues/484
=> Fix unexpected textbox in node join

k3os/images/10-k3s/Dockerfile, scripts/build
=> Bump k3s to v1.20.4+k3s1

pkg/console/testdata/create-cc.yaml, pkg/console/util.go
=> Disable servicelb and traefik

Dockerfile.dapper, scripts/build
=> Use ctr to save offline images

Dockerfile.dapper
Only ctr v1.3.0+ support export multiple images
https://github.com/containerd/containerd/commit/4754d2aeee1d1b978baf84b645979e92f59bdaae#diff-860d6311d47abf7e41d5bfc8b5b2d9f81ab18fc13097954a052d4cfa36836677
=> Fix ctr version, need v1.3.0 at least

scripts/build
After disable local-storage, servicelb, traefik, theirs image can be removed
iso file will just 2G
rancher/harvester#508
=> Remove unused image and add size check

pkg/console/install_panels.go
Fix backward and validate display bug on install panels
1. If the user selects Join mode and enters Management Address and then returns and reselects Create mode, the serverURL in the configuration is not cleared.
2. If the user moves between the password and password confirmation box, the display of the password is not preserved.
3. The Proxy address configuration could not be cleared
4. Cannot clear display of sshkey address configuration
5. https://github.com/rancher/harvester/issues/490#issuecomment-791298151
rancher/harvester#471
rancher/harvester#490
=> Fix backward and validate display bug on install panels

pkg/console/dashboard_panels.go
1. Show Running if one pod Running at least
2. Use node ip if get first ready master node's internal ip failed
**Relate issue**
rancher/harvester#459
rancher/harvester#353
**Relate PR**
rancher/harvester#497
=> Fix dashboard

pkg/console/install_panels.go
1. Validate config url
2. Show hostname and ssh key url on confirm content
3. Set confirm content in confirmV.PreShow
rancher/harvester#514
=> Add config url validation

go.mod, pkg/console/install_panels.go
=> Fix configure network failed

.drone.yml
https://github.com/rancher/harvester/issues/503
Do publish on daily cron events to keep artifacts up to date when related components like network-controller are updated.
=> Publish on cron event

pkg/console/testdata/create-cc.yaml, pkg/console/util.go
change k3s cluster cidr to avoid ip conflict
rancher/harvester#512
=> Change k3s cidr

pkg/console/install_panels.go
=> Fix doudle is

pkg/console/dashboard_panels.go
Add a Ready  status (harvester and rancher  are both Ready) to prompt the correct time to log in
rancher/harvester#597
=> Check rancher status

pkg/console/constant.go, pkg/console/install_panels.go
**Related issues**
rancher/harvester#613
=> Fix cluster token note

k3os/main.go, k3os/pkg/cli/install/install.go, pkg/config/read.go, pkg/config/schemas_test.go, pkg/console/dashboard_panels.go, pkg/console/install_panels.go, pkg/console/util.go, pkg/console/webhooks.go, pkg/console/webhooks_test.go
=> Fix management url

pkg/console/install_panels.go
=> Fix network key arrow up

k3os/images/00-base/Dockerfile
=> Add debug tools

pkg/console/install_panels.go
=> Add dhcp failed warnning

pkg/console/testdata/create-cc.yaml, pkg/console/testdata/join-cc.yaml, pkg/console/util.go
https://github.com/rancher/harvester/issues/665
=> Remove /dev/loop directory in runcmd

pkg/console/testdata/create-cc.yaml, pkg/console/testdata/join-cc.yaml, pkg/console/util.go
harvester/harvester#651
harvester/harvester#730
=> Update api group

Dockerfile.dapper, README.md, go.mod, k3os/images/10-gobuild/gobuild, k3os/main.go, k3os/pkg/cli/install/install.go, main.go, pkg/config/read.go, pkg/config/schemas_test.go, pkg/console/console.go, pkg/console/dashboard_panels.go, pkg/console/install_panels.go, pkg/console/tty.go, pkg/console/util.go, pkg/console/util_test.go, pkg/console/validator.go, pkg/console/validator_test.go, pkg/console/webhooks.go, pkg/console/webhooks_test.go, scripts/build
=> Fix repo reference

scripts/build
https://github.com/harvester/harvester/issues/789
=> fix broken cert-manager

scripts/build
Add support-bundle-utils image to ISO
=> Add support-bundle-utils image to ISO

scripts/build
Fix invalid cert-manager chart
https://drone-publish.rancher.io/harvester/harvester/275/3/2
=> Fix invalid cert-manager chart

pkg/config/config.go, pkg/config/k3os.go, pkg/console/install_panels.go, pkg/console/testdata/create-cc.yaml, pkg/console/testdata/create.yaml, pkg/console/testdata/join-cc.yaml, pkg/console/testdata/join.yaml, pkg/console/util.go, pkg/console/util_test.go, pkg/util/common.go
Add `os.write_files`.
Doc is also updated in https://github.com/harvester/harvester/pull/862
Related Issues:
https://github.com/harvester/harvester/issues/690
=> Support write_files in Harvester configuration

pkg/console/install_panels.go
Related issue harvester/harvester#800.
=> Wrap the install panel to display entire output

manifests/rancher.yaml
https://github.com/harvester/harvester/issues/922
Depend on PR: https://github.com/harvester/harvester/pull/998
Pinned to a specific commit in case upstream master-head is broken or has incompatible changes.
=> Bump rancher to master-head

manifests/rancher.yaml
https://github.com/rancher/rancher/issues/33745
=> disable features in embedded rancher

scripts/build-bundle
Preload the image for https://github.com/harvester/harvester/pull/1162
=> Bump support-bundle-kit to v0.0.3

manifests/harvester.yaml
Related to https://github.com/harvester/harvester/pull/1145
=> Enable harvester-node-disk-manager by default

manifests/harvester.yaml, pkg/config/config.go, pkg/config/constants.go, pkg/config/cos.go, pkg/config/templates/harvester-config.yaml, pkg/config/templates/rke2-90-harvester-server.yaml, pkg/console/constant.go, pkg/console/dashboard_panels.go, pkg/console/install_panels.go, pkg/console/validator.go, pkg/console/vip.go, pkg/console/vip_test.go, scripts/build-bundle
issue: https://github.com/harvester/harvester/issues/632
=> Support VIP

manifests/harvester.yaml, pkg/config/constants.go, pkg/config/templates/harvester-config.yaml, pkg/console/dashboard_panels.go, pkg/console/validator.go
- Fix VIP expose svc
- Support case-insensitive value for network modes
issue: 
https://github.com/harvester/harvester/issues/1186
https://github.com/harvester/harvester/issues/1187
Related PR:
https://github.com/harvester/harvester/pull/1188
=> Fix VIP expose svc

package/harvester-os/Dockerfile, package/harvester-os/files/etc/cos/bootargs.cfg, package/harvester-os/files/system/oem/90_network.yaml, package/harvester-os/iso/boot/syslinux/syslinux.cfg, pkg/config/cos.go, pkg/console/install_panels.go
https://github.com/harvester/harvester/issues/1197
**NOTE**: The UX in the network config dialog needs to be improved.
It takes time to configure IPs, using a spinner will be better.
=> Make network interface names predictable

pkg/console/install_panels.go, pkg/console/validator.go
issue: https://github.com/harvester/harvester/issues/1187
=> Support case insensitive for network method and vip mode

scripts/version-rke2
Bump RKE2 to rke2-v1.21.4-rc1+rke2r4
=> Bump RKE2 to rke2-v1.21.4-rc1+rke2r4

pkg/console/constant.go, pkg/console/install_panels.go, pkg/console/util.go, pkg/console/util_test.go
related https://github.com/harvester/harvester/issues/935
=> feat(install_panels): add NTP servers panel

pkg/console/dashboard_panels.go
issue: https://github.com/harvester/harvester/issues/1210
=> Get management URL from rancher-expose svc for agents

pkg/console/install_panels.go
issue https://github.com/harvester/harvester/issues/1248
=> fix(install_panels.go): change default ntp server to SUSE

pkg/console/install_panels.go, pkg/console/util.go
issue: https://github.com/harvester/harvester/issues/935
Enable NTP time sync if NTP servers can be connected.
=> feat(install_panels): enable ntp server after settings

pkg/console/install_panels.go, pkg/console/util.go
* log NTP validation error
issue: https://github.com/harvester/harvester/issues/1248
=> fix(install_panels): add log for NTP validation

pkg/console/util.go
issue: https://github.com/harvester/harvester/issues/1248
=> fix(util): prolong ntp timeout deadline

pkg/config/config.go, pkg/config/cos.go, pkg/console/constant.go, pkg/console/install_panels.go, pkg/console/util.go, pkg/console/validator.go
Remove `DNSNameservers` in `Network`.
issue: https://github.com/harvester/harvester/issues/1296
=> Move DNS setting to optional panel

scripts/build-bundle
https://github.com/harvester/harvester/issues/1392
=> Update windows VMDP driver image

package/harvester-os/files/usr/sbin/harv-install
issue: https://github.com/harvester/harvester/issues/1413
* Create a node.
* Create another node to join the first node.
* Check `/etc/rancher/rke2/rke2.yaml` is nonexistent.
=> fix(harv-install): remove tmporary rke2.yaml

scripts/build-bundle, scripts/bump-rancher, scripts/images/allow.yaml, scripts/lib/http, scripts/lib/image
- Fetch rancher image list and populate a image list with selected images.
- Update rancher version in the bootstrap chart.
=> Add a script to update Rancher dependencies

pkg/config/config.go, pkg/config/cos.go
Address https://github.com/harvester/harvester/issues/1541
=> Revert "Expose network.defaulRoute to yaml config"

scripts/build-bundle
Related:
harvester/harvester#1524
rancher/support-bundle-kit#27
=> Bump support-bundle-kit to v0.0.4

pkg/config/templates/rancherd-10-harvester.yaml, pkg/config/templates/rke2-90-harvester-server.yaml
https://github.com/harvester/harvester/issues/761
=> Enable ingress controller

pkg/config/config.go, pkg/config/cos.go, pkg/config/templates/rancherd-10-harvester.yaml, pkg/config/templates/wicked-ifcfg-bond-master, pkg/config/templates/wicked-ifcfg-eth, pkg/config/templates/wicked-ifcfg-vlan, pkg/console/validator.go
issue: https://github.com/harvester/harvester/issues/1390
=> feat: add vlan option to network

pkg/console/dashboard_panels.go
issue: https://github.com/harvester/harvester/issues/1633
* Build Image.
* Install to the first node.
* Install to other two nodes.
=> fix(dashboard_panels): get vip from ingress-expose

pkg/config/templates/rancherd-10-harvester.yaml
Address https://github.com/harvester/harvester/issues/1380#issuecomment-988260681
Set unlimited request size and disable request buffering(https://github.com/kubernetes/ingress-nginx/issues/6242)
=> Update proxy options for ingress

scripts/package-harvester-os
address https://github.com/harvester/harvester/issues/1627
=> Bump harvester-os version to 20211213

pkg/config/templates/rancherd-10-harvester.yaml, scripts/build-bundle
Issue: https://github.com/harvester/harvester/issues/1644
Depends on: https://github.com/harvester/harvester/pull/1680
=> Add harvester-crd chart

package/harvester-os/files/usr/share/rancher/rancherd/config.yaml.d/50-defaults.yaml, scripts/images/rancher-images.txt, scripts/images/rancherd-bootstrap-images.txt, scripts/version-rancher
Bump Rancher to v2.6.3-harvester1
=> Bump Rancher to v2.6.3-harvester1

scripts/build-bundle, scripts/lib/image
=> Fix awk expression in normalize_image

scripts/build-bundle
Signed-off-by: Weihang Lo <weihang.lo@suse.com>
=> Bump support-bundle-kit to v0.0.5

pkg/console/install_panels.go, pkg/console/network.go
Add argument "hostname" to `applyNetwork` function to set up hostname before configuring network.
=> Use yip to set hostname

pkg/console/util.go
Use context to interrupt cos-install-shutdown script
- https://github.com/harvester/harvester/issues/1761
=> Fix: CTRL-C prevents rebooting after installation

scripts/build-bundle
The URL has been updated due to a recent change of https://github.com/rancher/charts.
=> Fix rancher-monitoring-crd URL

scripts/build-bundle
related issue: https://github.com/harvester/harvester/issues/1727
depend on PR: https://github.com/harvester/harvester/pull/1771
=> get support bundle image from harvester chart

pkg/config/config.go, pkg/console/validator.go
related to https://github.com/harvester/harvester/issues/1739
=> validate system settings to avoid unexpected settings

pkg/config/templates/rancherd-21-harvester-clusternetworks.yaml
assign incorrect apiVersion
already correct it
=> change the apiVersoin to correct path

scripts/package-harvester-os
=> Bump base OS to 20220302

scripts/package-harvester-os
=> Bump OS to 20220311

Dockerfile.dapper
for https://github.com/harvester/harvester-installer/blob/678334d014b87ddeea6bcb6f7739150b60ba569a/scripts/version#L9
https://github.com/harvester/harvester/issues/1817
=> Expose DRONE_BRANCH to dapper

pkg/config/config.go
Add `release-download-url` to the Harvester system settings
Related issue: 
https://github.com/harvester/harvester/issues/2091
Related PR:
https://github.com/harvester/harvester-installer/pull/256
https://github.com/harvester/docs/pull/134
=> Add release-download-url setting

scripts/patch-harvester
Signed-off-by: futuretea <Hang.Yu@suse.com>
https://github.com/harvester/harvester/issues/2048
=> Dynamic Harvester image repo

package/harvester-os/files/usr/share/rancher/rancherd/config.yaml.d/50-defaults.yaml, scripts/images/rancher-images.txt, scripts/images/rancherd-bootstrap-images.txt, scripts/version-rancher
**Description:**
Bump Rancher to `v2.6.4-harvester2`.
=> Bump Rancher to v2.6.4-harvester2

scripts/package-harvester-os, scripts/version-rke2
Depends on https://github.com/harvester/os2/pull/35 (Note I include a temporary image in commits)
**Related issue**: https://github.com/harvester/harvester/issues/2112
=> Downgrade RKE2 to v1.21.11+rke2r1

package/harvester-os/files/usr/sbin/harv-install, package/harvester-os/iso/boot/grub2/grub.cfg
related issue: https://github.com/harvester/harvester/issues/2115
And this is just a temp workaround for https://github.com/rancher-sandbox/cOS-toolkit/pull/1220
=> Patch GRUB config: Add --no-floppy option

package/harvester-os/files/system/oem/09_ca.yaml, pkg/config/templates/cos-rootfs.yaml
Add persistent path `/etc/pki/trust/anchors` for SSL and boot command `update-ca-certificates`.
https://github.com/harvester/harvester/issues/2175
=> add persistent paths

pkg/console/install_panels.go
related backport issue:  https://github.com/harvester/harvester/issues/2375
parent pr: https://github.com/harvester/harvester-installer/pull/282
=> [Backport v1.0.3] VIP panel: wrap info panel

pkg/console/dashboard_panels.go
please refer https://github.com/harvester/harvester/issues/2087
Test case in https://github.com/harvester/harvester/issues/2087
It will check the interface with the default route to have the primary/first IP from it.
If not, it will fall back to harvester-mgmt and get IP from it.
1. build harvester-installer with `make`
2. copy harvester-installer with `scp bin/harvester-installer rancher@<IP>:<PATH>
3. Switch harvester console to TTY2 or other (press CTRL+ALT+F2)
4. execute harvester-installer in current TTY `DEBUG=true HARVESTER_DASHBOARD=true TTY=/dev/tty <PATH>/harvester-installer`
5. check the screen has Node IP and IP address (refer the figure below)
=> console: dashboard: show node ip for identify nodes

package/harvester-os/files/usr/sbin/harv-install
Backport of https://github.com/harvester/harvester/issues/2450
Original PR: https://github.com/harvester/harvester-installer/pull/281
Test plan: https://github.com/harvester/tests/issues/351
=> Deactivate LVM and MD devices before installation

scripts/package-harvester-os
=> Bump baseOS to 20220705

.drone.yml
=> Add v1.0 branch to daily builds

pkg/console/dashboard_panels.go
please refer https://github.com/harvester/harvester/issues/2087
Test case in https://github.com/harvester/harvester/issues/2087
It will check the interface with the default route to have the primary/first IP from it.
If not, it will fall back to harvester-mgmt and get IP from it.
1. build harvester-installer with `make`
2. copy harvester-installer with `scp bin/harvester-installer rancher@<IP>:<PATH>
3. Switch harvester console to TTY2 or other (press CTRL+ALT+F2)
4. execute harvester-installer in current TTY `DEBUG=true HARVESTER_DASHBOARD=true TTY=/dev/tty <PATH>/harvester-installer`
5. check the screen has Node IP and IP address (refer the figure below)
=> [Backport v1.0.3] console: dashboard: show node ip for identify nodes

package/harvester-os/files/etc/cos/bootargs.cfg
related to https://github.com/harvester/os2/pull/44
=> audit: enable audit during booting up

Dockerfile.dapper, package/harvester-os/files/etc/cos/bootargs.cfg, scripts/build-bundle
- https://github.com/harvester/harvester-installer/pull/306
- https://github.com/harvester/harvester-installer/pull/305
=> Batched backports 0718

scripts/package-harvester-os
=> os2: bump os2 version

package/harvester-os/files/usr/share/rancher/rancherd/config.yaml.d/50-defaults.yaml
=> Disable rancher host port 8443

scripts/package-harvester-os
=> Bump os2 to 20220802

pkg/console/install_panels.go
related: https://github.com/harvester/harvester/issues/2472
=> update default bond mode to active-backup

pkg/console/dashboard_panels.go
Currently, there's much information sprawl on the dashboard console without structure. It's hard to grasp the key information at the first glance for new users.
This PR groups them into two sections:
1. **Harvester Cluster** section: contains cluster-wide information such as management URL and cluster status
2. **Node** section: contains the information regarding the node itself such as hostname, IP address, and node status
Related issue: harvester/harvester#2402
=> Re-format dashboard layout for better readability

pkg/console/constant.go, pkg/console/install_panels.go
Put emphasis on the importance of configuring NTP servers for cluster
stability. Also, provide clearer instruction and consequence regarding
the invalid input.
Signed-off-by: Zespre Chang <zespre.chang@suse.com>
Related issue: harvester/harvester#2367
=> fix(install_panels): enhance the messages displayed on NTP server panel

scripts/package-harvester-os
add package ca-certificates, ca-certificates-mozilla for update-ca-certificates commands
related: https://github.com/harvester/harvester/issues/2709
=> baseos: bump baseos version with additional ca package

pkg/console/install_panels.go
Per the [discussion](https://github.com/harvester/harvester/issues/2367#issuecomment-1233919081) in harvester/harvester#2367, adjust the wording for emphasis.
Related PR: #326
Signed-off-by: Zespre Chang <zespre.chang@suse.com>
=> fix(install_panels): adjust the wording regarding NTP config

pkg/config/config.go, pkg/config/testdata/harvester-config.yaml, pkg/console/install_panels.go
Rewrite the scheme version in automatic/non-automatic mode
Only assign Scheme Version in non-automatic mode 
and load scheme version from config.yaml directly in automatic mode.
=> Rewrite the scheme version in automatic/non-automatic mode

scripts/version-rke2
Related issue: https://github.com/harvester/harvester/issues/2785
=> Bump RKE2 to v1.23.10+rke2r1

scripts/package-harvester-os
=> baseos: bump baseos

pkg/config/cos.go, pkg/config/templates/rancherd-22-vm-import-controller.yaml, scripts/build-bundle
Inital work to add vm-import-controller helm chart, images and addon to the harvester iso.
=> initial commit for vm-import-controller-addon

pkg/config/cos.go, pkg/config/templates/rancherd-22-addons.yaml, scripts/build-bundle
PR introduces changes to package up pcidevices-controller as an addon in the harvester-installer
=> package pcidevices addon

package/harvester-os/Dockerfile, package/harvester-os/files/etc/dracut.conf.d/02-config-migration.conf, package/harvester-os/files/etc/systemd/system/cos-setup-initramfs.service.d/override.conf, package/harvester-os/files/etc/systemd/system/initrd.target.requires/config-migration.service, package/harvester-os/files/lib/systemd/system/config-migration.service, package/harvester-os/files/usr/sbin/migration.sh, package/harvester-os/files/usr/sbin/migration/migrate_harv_mgmt_to_mgmt_br.sh
Migrate harvester-mgmt to mgmt-br and mgmt-bo
It will be executed before cos-setup-initramfs.service
=> vlan: migrate harvester-mgmt to mgmt-br and mgmt-bo

pkg/config/templates/rancherd-22-addons.yaml, scripts/build-bundle
PR introduces changes to the pcidevices helm chart and image to be packaged with harvester.
=> upgrade chart and image for pcidevices controller

scripts/package-harvester-os
Create an image list tarball
```
$ tar -tf dist/artifacts/image-lists.tar.gz
image-lists/
image-lists/harvester-extra-e350174-dirty.txt
image-lists/harvester-images-e350174-dirty.txt
image-lists/rancher-images-v2.6.4-harvester3.txt
image-lists/rke2-images.linux-amd64-v1.22.12-rc3-rke2r1.txt
image-lists/rke2-images-multus.linux-amd64-v1.22.12-rc3-rke2r1.txt
image-lists/harvester-repo-images-0464777-dirty.txt
image-lists/rancherd-bootstrap-images-e350174-dirty.txt
```
=> Generate image list tarball

package/rke2/Dockerfile, scripts/build-bundle
=> Workaround: patch rke2-canal chart in rke2-runtime image

pkg/config/templates/rancherd-22-addons.yaml
PR introduces the experimental label for pcidevices controller.
Related to: https://github.com/harvester/harvester/issues/3003
=> experimental label for pcidevices controller

scripts/package-harvester-os
=> baseos: add hwinfo, usbutils

scripts/version-rke2
Related issue: https://github.com/harvester/harvester/issues/2927
=> Bump RKE2 to v1.24.7+rke2r1

pkg/config/templates/rancherd-22-addons.yaml, scripts/build-bundle
**Description:**
Bump the pci-devices chart to v0.2.1. formal release.
=> Bump pci-devices chart to v0.2.1

scripts/package-harvester-os
=> baseos: upgrade baseos

pkg/config/templates/rancherd-22-addons.yaml, scripts/build-bundle
=> Bump pcidevices to v0.2.2

package/harvester-os/files/etc/sysctl.d/ipv6.conf
Related issue: https://github.com/harvester/harvester/issues/2962
Signed-off-by: Canwu Yao <yaocanwu@gmail.com>
=> Disable ipv6

pkg/config/templates/rancherd-22-addons.yaml, scripts/build-bundle
related issue: https://github.com/harvester/harvester/issues/3159
=> chart: bump pci-device/vm-import chart

scripts/package-harvester-os
RPM packages changes since the last version:
```
PACKAGE                     IMAGE1 (docker.io/rancher/harvester-os:20221109)        IMAGE2 (docker.io/rancher/harvester-os:20221123)
-dracut                     049.1+suse.238.gd8dbb075-150200.3.60.1, 1.2M            049.1+suse.247.gfb7df05c-150200.3.63.1, 1.2M
-hwdata                     0.360-150000.3.48.1, 8.4M                               0.363-150000.3.51.1, 8.6M
-iputils                    s20161105-8.3.1, 207.2K                                 s20161105-150000.8.6.1, 199.3K
-kernel-default             5.3.18-150300.59.98.1, 166.9M                           5.3.18-150300.59.101.1, 166.9M
-krb5                       1.19.2-150300.8.3.2, 2M                                 1.19.2-150300.7.7.1, 2M
-libX11-6 …
```
=> Bump OS to 20221123

.drone.yml
Backport of https://github.com/harvester/harvester-installer/pull/392
=> [Backport v1.1] Drone: specify branches to trigger pipelines

.drone.yml
Related issue: https://github.com/harvester/harvester/issues/3352
Let's have the file changed in the master and backported to v1.1 branch.
=> CI: Publish artifacts on v* branches 

Dockerfile.dapper, package/harvester-repo/Dockerfile
https://github.com/harvester/harvester/issues/3149
=> Bump SLE BCI image to 15.4

Dockerfile.dapper, package/harvester-repo/Dockerfile
**Related issue:**
[#3149](https://github.com/harvester/harvester/issues/3149)
=> [v1.1 backport] Bump SLE BCI image to 15.4

pkg/config/templates/rancherd-22-addons.yaml, scripts/build-bundle
PR introduces changes for introducing new version of pcidevices controller
=> increment version of pcidevices-controller

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/codeql.yml, .github/workflows/scan.yml, .golangci.json, Dockerfile.dapper, pkg/config/config.go, pkg/config/cos.go, pkg/console/console.go, pkg/console/install_panels.go, pkg/console/util.go, pkg/console/validator.go, pkg/console/webhooks.go, pkg/util/cmdline.go, pkg/widgets/dropdown.go, pkg/widgets/panel.go, pkg/widgets/select.go
**Description:**
- add codeql and trivy scanning
- fix golangci-lint
=> Add code scanning and fix golangci-lint

pkg/config/templates/rancherd-22-addons.yaml, scripts/build-bundle
**Problem:**
PR introduces changes to bump up pcidevices controller to v0.2.4-rc2
**Solution:**
**Test plan:**
=> update installer to pcidevices controller v0.2.4-rc2

scripts/package-harvester-os
**Problem:**
Some packages of harvester base os need to update
**Solution:**
bump harvester base os to the latest
**Test plan:**
**Additional appendix:**
The whole updated packages are below.
```
Packages found only in docker.io/rancher/harvester-os:20230406:
NAME            VERSION                   SIZE
-mokutil        0.5.0-150400.3.3.1        96.7K
-openssl        1.1.1l-150400.1.5         246B
PACKAGE                   IMAGE1 (docker.io/rancher/harvester-os:20230328)        IMAGE2 (docker.io/rancher/harvester-os:20230406)
-glibc                    2.31-150300.41.1, 6.2M                                  2.31-150300.46.1, 6.2M
-glibc-locale-base        2.31-150300.41.1, 11.2M                                 2.31-150300.46.1, 11.2M
-grub2 …
```
=> build: bump base os to 20230406

package/harvester-os/files/usr/share/rancher/rancherd/config.yaml.d/50-defaults.yaml
**Solution:**
Enable `multi-cluster-management` feature.
https://github.com/harvester/harvester/issues/2679
**Test plan:**
1. Create a new cluster.
2. Check `mult-cluster-management` feature. It should be `true`.
=> feat(rancherd): enable mcm (Warning: only works for new cluster)

pkg/config/templates/rancherd-22-addons.yaml, scripts/build-bundle
**Problem:**
PR to bump up pcidevices controller to v0.2.4-rc3
**Solution:**
**Test plan:**
=> upgrade pcidevices controller to v0.2.4-rc3

pkg/config/templates/rancherd-22-addons.yaml, scripts/build-bundle
**Problem:**
change pcidevices addon to new version v0.2.4
**Solution:**
**Test plan:**
=> bump up pcidevices chart to v0.2.4

pkg/config/config.go, pkg/config/config_test.go
Set the max-pods to 200 as per [issue 2707](https://github.com/harvester/harvester/issues/2707). 
For the upgrade path: https://github.com/harvester/harvester/pull/3815
=> Set max-pods default to 200 [Fixes harvester/harvester#2707]

pkg/config/templates/rancherd-22-addons.yaml, scripts/build-bundle
**Problem:**
Bump pcidevices controller to v0.2.5-rc1
**Solution:**
**Test plan:**
=> update pcidevices to v0.2.5-rc1

package/harvester-os/files/usr/share/rancher/rancherd/config.yaml.d/50-defaults.yaml, pkg/config/templates/rancherd-config.yaml, scripts/version-rke2
**Problem:**
Bump RKE2 v1.25.x.
**Solution:**
Bump RKE2 v1.25.x.
https://github.com/harvester/harvester/issues/3747
**Test plan:**
=> Bump rke2 v1.25.9+rke2r1

scripts/build, scripts/build-bundle
Use the v1.2 branch to build the correct ISO.
=> Use v1.2 branch from the harvester/harvester repo

package/harvester-os/files/usr/share/rancher/rancherd/config.yaml.d/50-defaults.yaml
Reverts harvester/harvester-installer#468
=> Revert "feat(rancherd): enable mcm (Warning: only works for new cluster)"

pkg/config/templates/rancherd-22-addons.yaml, scripts/build-bundle
**Problem:**
PR introduces harvester-seeder addon packaging in installer.
**Solution:**
**Related Issue:** https://github.com/harvester/harvester/issues/2318
**Test plan:**
=> addition of seeder addon

scripts/hack/patch-rancher-logging, scripts/hack/patch-rancher-monitoring, scripts/hack/patch-rancher-monitoring-crd
Remove unused intermediate chart directories
Before:
```
total 1.2M
drwxr-xr-x 5 root root 4.0K Jun 22 00:14 .
drwxr-xr-x 1 root root 4.0K Jun 22 00:23 ..
-rw-r--r-- 1 root root 161K Jun 22 00:14 harvester-0.0.0-master-173b0824.tgz
-rw-r--r-- 1 root root  55K Jun 22 00:14 harvester-crd-0.0.0-master-173b0824.tgz
-rw-r--r-- 1 root root 2.7K Jun 22 00:14 harvester-pcidevices-controller-0.2.5-rc1.tgz
-rw-r--r-- 1 root root 2.6K Jun 22 00:14 harvester-vm-import-controller-0.1.4.tgz
-rw-r--r-- 1 root root  12K Jun 22 00:14 index.yaml
drwxr-xr-x 3 root root 4.0K Jun 22 00:14 rancher-logging
-rw-r--r-- 1 root root  15K Jun 22 00:14 rancher-logging-102.0.0+up3.17.10.tgz
-rw-r--r-- 1 root root  82K Jun 22 00:14 rancher-logging-crd-102.0.0+up3.17.10.tgz
drwxr-xr-x 5 root root 4.0K Jun 22 00:14 …
```
=> Remove unused intermediate chart directories

pkg/config/templates/rancherd-22-addons.yaml, scripts/images/harvester-additional-images.txt
**Problem:**
https://github.com/harvester/security/issues/31
**Solution:**
https://github.com/harvester/harvester/pull/4251
https://github.com/harvester/harvester/pull/4251
**Test plan:**
=> Bump eventrouter to v0.1.1 and replace repo

package/harvester-os/Dockerfile
https://github.com/harvester/security/issues/36#top
=> feat: update wharfie to v0.6.3

pkg/config/templates/rancherd-22-addons.yaml, scripts/build-bundle
**Problem:**
PR bumps up following addons for v1.1.3
* vm-import-controller: v0.1.6
* pcidevices-controller: v0.2.6
* 
**Solution:**
**Test plan:**
=> update addon versions for v1.1.3

ci/run_vagrant_install_test.yml, ci/terraform/check_files.sh, package/harvester-os/files/usr/sbin/harv-install
**Problem:**
The boot stuck on the grub might be because of the search for a non-existent file.
(With specific Hardware, like BOSS-S1 raid card)
**Solution:**
Manually create these files with the installation
https://github.com/harvester/harvester/issues/4784
**Test plan:**
Make sure the boot is not stuck on the bare metal with the BOSS-S1 raid card.
=> install: manually create custom grub file

scripts/images/harvester-additional-images.txt
Remove busybox.
https://github.com/harvester/harvester/issues/4839
**Test plan:**
Provision 3-node harvester in airgap environment. (Need to work with https://github.com/harvester/harvester/pull/4852)
=> feat: remove busybox

scripts/version-rke2
This reverts commit fb3c52d723dfb9085a59eeb235c17ea15719d833.
=> Revert "Bump RKE2 to v1.24.17+rke2r1"

scripts/images/harvester-additional-images.txt
Remove unused image.
https://github.com/harvester/harvester/issues/4839
**Test plan:**
Test 3-node harvester can be provisioned in an airgap environment.
=> feat: remove alpine:3

README.md
=> chore: Update copyright year [CI SKIP]

.github/workflows/vagrant-install.yaml
Run the tests on branch merged and daily.
=> ci: run vagrant-install workflow on branch merged and daily

.gitignore, README.md, Vagrantfile
I wrote this up while learning the codebase, so thought I'd better add it to the README file as an aid to future contributors.  This PR also adds a Vagrantfile for faster dev/test of the interactive part of the installer.
=> README.md: Add details of the ISO build and system install process

pkg/config/templates/rancherd-22-addons.yaml, scripts/build-bundle
**Problem:**
PR introduces addon updates for:
* seeder
* pcidevices-controller
* vm-import-controller
It also introduces the new addon for `nvidia-driver-toolkit`
**Solution:**
**Test plan:**
=> addon updates

README.md
Just following up https://github.com/harvester/harvester-installer/pull/648#pullrequestreview-1866996442
=> README.md: Add remote debug information for VS Code

pkg/console/install_panels.go
... and clear the error message when necessary.
**Problem:**
Error message is not cleared and validation is only done before page change is triggered.
**Solution:**
The error message is cleared when necessary and the validation of the `Persistent size` is done immediately when the input field loses focus (enter or key-down).
https://github.com/harvester/harvester/issues/5096
**Test plan:**
- Go to the disk setup page
- Choose `Use the installation disk` for `Data disk`
- Go to the `Persistent size` field and enter a value < 150GiB
- Press `Enter` or `Key-Down`
- The error message `Partition size is too small. Minimum 150Gi is required` must be displayed
- Changing value to >= 150GiB the error message must disappear.
=> Immediately validate the persistent size

Dockerfile.dapper, package/harvester-os/Dockerfile, package/harvester-os/arm/grub.cfg, package/harvester-os/arm/manifest.yaml, package/harvester-os/files/usr/bin/setup-installer.sh, package/harvester-os/files/usr/sbin/harv-install, pkg/config/cos.go, pkg/config/templates/rancherd-23-multus-config.yaml, scripts/build-bundle, scripts/hack/patch-harvester-chart, scripts/package-harvester-os
**Problem:**
PR introduces experimental support for arm hosts
**Solution:**
https://github.com/harvester/harvester/issues/371
**Test plan:**
=> Arm build support

pkg/config/templates/rancherd-22-addons.yaml
**Problem:**
we should use the same tag as the baseos image
**Solution:**
Use the same tag as the baseos image
None
**Test plan:**
None
=> config/templates: update nvidia-driver-toolkit tag

pkg/config/templates/patch/rancher-monitoring/102.0.0+up40.1.2/nginx-config.yaml
**Problem:**
This is a manual backport of https://github.com/harvester/harvester-installer/pull/665, refer it.
**Solution:**
Add processing for all cases.
https://github.com/harvester/harvester/issues/5236
**Test plan:**
Refer: https://github.com/harvester/harvester-installer/pull/665
=> Fix grafana in all scenarios

scripts/archive-images-lists.sh
related to https://github.com/harvester/harvester/issues/5313
this is a followup in https://github.com/harvester/harvester-installer/pull/682
=> Fix if condition in archive-images-lists.sh

pkg/config/templates/rancherd-12-monitoring-dashboard.yaml
**Problem:**
`No data` on VM Metrics.
**Solution:**
Fix the changed metrics name.
https://github.com/harvester/harvester/issues/5442
https://github.com/harvester/harvester/issues/5439
**Test plan:**
Per issue description.
=> Fix no data on VM Metrics

scripts/version-rke2
https://github.com/harvester/harvester/issues/5596
=> Bump RKE2 to v1.26.15+rke2r1

.github/workflows/codeql.yml, .github/workflows/vagrant-install.yaml
Fix action warnings like: https://github.com/harvester/harvester-installer/actions/runs/8917167826
=> fix: address action warnings

scripts/build
Fix the wrong version of harvester images/charts used while packaging v1.3 ISO.
=> Use v1.3 branch in the harvester repo

scripts/build-bundle
**Problem:**
**Solution:**
https://github.com/harvester/harvester/pull/5787
**Test plan:**
=> fix: ignore openshift-origin-oauth-proxy image

scripts/images/harvester-additional-images.txt
**Problem:**
Task: https://github.com/harvester/harvester/issues/5947
Image release:
https://github.com/harvester/eventrouter/releases/tag/v0.2.0
Hold this PR until the image is released.
**Solution:**
Bump image
https://github.com/harvester/harvester/issues/5947
**Test plan:**
=> Bump eventrouter image to v0.2.0

scripts/build, scripts/build-bundle
=> Move harvester and add-on repos to the v1.4 branches

pkg/config/templates/patch/rancher-monitoring-crd/103.0.3+up45.31.1/patch-values-shell-version.diff, pkg/config/templates/patch/rancher-monitoring/103.0.3+up45.31.1/patch-values-shell-version.diff, scripts/images/rancher-images.txt
**Problem:**
https://github.com/harvester/harvester/issues/6283
**Solution:**
Bump shell version to elimate/reduce CVE
manually cherry-pick from PR https://github.com/harvester/harvester-installer/pull/766
https://github.com/harvester/harvester/issues/6283
**Test plan:**
=> Patch shell version to v0.1.26

.github/workflows/build.yml
**Problem:**
https://github.com/harvester/harvester-installer/actions/runs/10316266508/job/28558102641 failed.
**Solution:**
This PR, I hope.
**Test plan:**
=> ci: Add permissions section to ISO build

.github/workflows/build.yml
**Problem:**
https://github.com/harvester/harvester-installer/actions/runs/10373032086 failed.
**Solution:**
This PR. No, really. I'm sure this will finally be the last one.
**Test plan:**
=> ci: Use correct google credential path

.github/workflows/build.yml
**Problem:**
https://github.com/harvester/harvester-installer/actions/runs/10379435433/job/28737593509 failed.
**Solution:**
This PR.
**Test plan:**
=> ci: use matrix.arch in docker-publish-harvester-cluster-repo

.github/workflows/build.yml
**Problem:**
https://github.com/harvester/harvester-installer/actions/runs/10379745962 failed.
**Solution:**
This PR.
**Test plan:**
=> ci: Use correct dockerhub credential path (2)

scripts/images/harvester-additional-images.txt
**Problem:**
Bump eventrouter image tag to v0.3.2
**Solution:**
https://github.com/harvester/harvester/issues/6568
**Test plan:**
Upgrade PR: https://github.com/harvester/harvester/pull/6613
=> [v1.3] Bump eventrouter to v0.3.2

scripts/version-rke2
Bump RKE2 to v1.29.9+rke2r1
**Related Issue**
https://github.com/harvester/harvester/issues/6584
=> Bump RKE2 to v1.29.9+rke2r1

package/harvester-os/Dockerfile
=> Bump wharfie to v0.6.7

package/harvester-os/files/system/oem/99_modules.yaml, scripts/hack/patch-harvester-chart
**Problem:**
PR introduces the following changes:
* updates kubevirt to v1.2.2 for arm builds
* adds a directive to load dm_crypt via /system/oem/ mount to ensure change is propagated to both new installs and the upgrade path.
**Solution:**
https://github.com/harvester/harvester/issues/6827
**Test plan:**
=> minor updates

package/harvester-os/Dockerfile
**Problem:**
Backport of https://github.com/harvester/harvester-installer/pull/887
**Solution:**
**Test plan:**
=> feat(upgrade): upgrade wharfie cli to v0.6.8 (backport #887)

package/harvester-os/Dockerfile
**Problem:**
**Solution:**
Bump wharfie cli to [`v0.6.8`](https://github.com/rancher/wharfie/releases/tag/v0.6.8) to solve https://github.com/rancher/wharfie/pull/32 which generates issues with VEXed entries and Trivy scanning.
**Test plan:**
=> feat(upgrade): upgrade wharfie cli to v0.6.8

.github/workflows/build.yml
**Problem:**
**Solution:**
https://github.com/harvester/harvester/issues/6711
**Test plan:**
=> feat(ci): cancel in progress CI if there is new commit in a same PR

scripts/version-rke2
Bump RKE2 to v1.28.15+rke2r1
https://github.com/harvester/harvester/issues/7186
**Test plan:**
Create a 3-node cluster without error.
=> feat: bump RKE2 to v1.28.15+rke2r1

pkg/config/templates/rancherd-22-addons.yaml, scripts/build-bundle
**Problem:**
harvester-seeder addon has a new image version for harvester v1.3 branch.
**Solution:**
Update harvester-seeder addon to v0.3.3
https://github.com/harvester/harvester/issues/6590
**Test plan:**
N/A
=> Update harvester-seeder addon

.github/mergify.yml
Check the correct amd64 build jobs.
Sample PR: https://github.com/harvester/harvester-installer/pull/918
=> fix: mergify auto approval rules [skip ci]

.github/workflows/build.yml
Support SLSA3.
https://github.com/harvester/harvester/issues/6205
**Test plan:**
=> feat: add provenance for harvester-cluster-repo

.github/workflows/build.yml
**Problem:**
Fix failed build on master branch.
https://github.com/harvester/harvester-installer/actions/runs/12687470051/job/35418827223
**Solution:**
Add setup QEMU and Docker Buildx.
Successful build: https://github.com/harvester/harvester-installer/actions/runs/12740077579/job/35504727554?pr=928
https://github.com/harvester/harvester/issues/6205
=> fix(ci): SLSA3 support

pkg/console/install_panels.go, pkg/console/validator.go
**Problem:**
When using static mode VIP, the installer is blocked.
**Solution:**
Set proper VipMode value.
https://github.com/harvester/harvester/issues/7362
**Test plan:**
Install Harvester in any mode, it should success.
=> Set VipMode value in static mode

pkg/config/templates/rancherd-10-harvester.yaml
**Problem:**
Harvester managedchart is marked as harvester-snapshot-validation-webhook modified
**Solution:**
Add those dynamic resources (updated each time chart is updated) to diff path of managedchart.
https://github.com/harvester/harvester/issues/7442
**Test plan:**
1. Update harvester managedchart, observe the managedchart is not complained.
BTW: additional fix is needed in upgrade path.
=> Add snapshot-validation-webhook related resources to diff

pkg/config/templates/rancherd-12-monitoring-dashboard.yaml
**Problem:**
Fix incorrect Grafana CPU Usage panel
**Solution:**
Fix incorrect Grafana CPU Usage panel in installer, upgrade path fix pr: https://github.com/harvester/harvester/pull/7528
https://github.com/harvester/harvester/issues/7086
**Test plan:**
https://github.com/harvester/harvester/issues/7086#issuecomment-2632801527
=> Fix incorrect Grafana CPU Usage panel

.github/mergify.yml
Merge backport PRs if CI passed and got 1 more approval from developers.
=> Automatically merge backport PRs [skip ci]

scripts/patch-monitoring-logging
Signed-off-by: Zespre Chang <zespre.chang@suse.com>
=> chore: bump harvester-eventrouter to v1.5.1

scripts/build, scripts/build-bundle, scripts/test
Bump v1.6 harvester/addon branch
Bump v1.6 harvester/addon branch
=> scripts: bump to v1.6 harvester/addon branch

pkg/config/config.go, pkg/config/cos.go, pkg/config/templates/rancherd-15-kubeovn-operator-crd.yaml, scripts/build, scripts/build-bundle, scripts/images/harvester-additional-images.txt
PR introduces the following components:
* kubeovn-operator-crd managed chart which is configured by installer on new installs
* kubeovn-addon which can be used to enable/configure kubeovn for your cluster
https://github.com/harvester/harvester/issues/7413
To test build an iso from this PR or use master once the change is merged
* Install a new node with harvester
* Post installation users should find a `kubeovn-operator-crd` managed chart installed by default
* Users should also find a new `kubeovn-operator` addon
* Enabling the addon should enable and deploy the kubeovn-operator, and also create a default `configuration` which will trigger setup of kubeovn on harvester
=> introduce kubeovn addon

pkg/console/install_panels.go, pkg/console/util.go
https://github.com/harvester/harvester/issues/8620
Remove the function returning hardcoded values.
https://github.com/harvester/harvester/issues/8620
* CI should pass, I guess.
* Running `make` on my dev setup is taking obnoxiously long. I'll update here if/when it succeeds.
=> Remove `harvesterInstalled` function

scripts/images/rancher-images.txt
https://github.com/harvester/harvester/issues/8552
* Install harvester in airgapped environment.
=> fix: fleet image

Dockerfile.dapper, go.mod, pkg/console/validator.go
Bump golang 1.24
Bump golang 1.24
https://github.com/harvester/harvester/issues/8728
=> common: bump go v1.24

scripts/images/rancher-images.txt
https://github.com/harvester/harvester/issues/9119
=> fix: airgap installation
